aws/aws-ofi-nccl

Makefile
Fix the top level Makefile to always use the $CUDA_HOME variable
This fixes linkage errors when compiling the test binaries.
=> Use $CUDA_HOME when linking test binaries

src/nccl_ofi_net.c
N/A
Fix the bug in the NCCL/OFI plugin. This bug doesn't allow us to work with OFI/psm2 provider and other providers that require `FI_CONTEXT` mode.
And + minor code cleanups (excessive `goto` operators has been removed)
=> OFI-NCCL: Plugin doesn't work with OFI providers that require FI_CONTEXT mode

.travis.yml
When building against new NCCL release, build complained of running out
of virtual memory. Fix this by running build in a serial fashion i.e.
without `-j` flag.
This patch also does some minor cleanups and use ubuntu's openmpi
package rather than building from source.
=> CI: Fix failing travis build due to upgrade in NCCL2.4

README.md, src/nccl_ofi_net.c
All calls to fi_av_insert() pass a non-NULL fi_addr_t and use that
returned address for subsequent libfabric calls. It's therefore safe to
use either AV type, so the av_type attr can be left zeroed (i.e.,
FI_AV_UNSPEC) to let the provider choose whichever it prefers.
=> OFI-NCCL: Remove FI_AV_TABLE requirement

README.md, src/nccl_ofi_net.c
AWS squashed "efa" and "ofi_rxr" provider so support plugin to use the
squashed provider from latest releases.
=> OFI-NCCL: Change AWS provider to support latest EFA

src/nccl_ofi_net.c
Three patches to merge.
```
1) OFI-NCCL: Fix missing completion check for connect API
2) OFI-NCCL: Remove unnecessary free in completion process
```
1) resolves issue #18 but 2) is also necessary for some providers.
=> OFI-NCCL: Fix missing completion check for connect API

README.md, include/nccl_ofi.h, include/stack.h, src/nccl_ofi_net.c
This PR introduces 4 new patches to the master branch
```
OFI-NCCL: fix resource leak
OFI-NCCL: fix tag value overflow
OFI-NCCL: fix memory leak
OFI-NCCL: fix compiler warning
```
The following patch is cherry-picked from aws branch in order to make master up to date.
```
Documentation: Modify README.md to support latest libfabric and NCCL versions
```
=> [master] OFI-NCCL: fix resource leak

README.md, RELEASENOTES.md, configure.ac, src/nccl_ofi_net.c, tests/nccl_connection.c, tests/nccl_message_transfer.c, tests/ring.c, tests/test-common.h
This PR adds several commits which adds the following support:
* Add NCCL v2.6.x support
* Modify tests to validate NCCL v2.6.x support, memory registration/deregistration.
* Use fid_mr for memory handle.
* Check NCCL API return codes in tests.
* Enable/disable printing of trace message
=> [Aws] Add support for NCCL 2.6 and some improvements in tests

README.md, RELEASENOTES.md, configure.ac, src/nccl_ofi_net.c, tests/nccl_connection.c, tests/nccl_message_transfer.c, tests/ring.c, tests/test-common.h
This PR adds several commits which adds the following support:
* Add NCCL v2.6.x support
* Modify tests to validate NCCL v2.6.x support, memory registration/deregistration.
* Use fid_mr for memory handle.
* Check NCCL API return codes in tests.
* Enable/disable printing of trace message
=> Add support for NCCL 2.6 and some improvements in tests

src/nccl_ofi_net.c
RDMAV_FORK_SAFE environment variable makes the rdma-core library
fork-safe. This significantly increases cost of memory registration when huge
pages are enabled.
To prevent data corruption, the EFA provider registers an atfork handler
which will abort the process whenever it believes rdma-core is not
fork-safe.
NCCL applications heavily re-use the buffers for communication and
thus are not sensitive to increased memory registration costs.
To prevent NCCL based applications from getting aborted when using
fork(), plugin explicitly enables RDMAV_FORK_SAFE environment variable.
cr https://code.amazon.com/reviews/CR-27719603
By submitting this pull request, I confirm that my contribution is …
=> OFI-NCCL: Enable RDMAV_FORK_SAFE environment variable

src/nccl_ofi_net.c
For NCCL versions (v2.7.8 and less), flush() should exit sooner when
receiving 0-sized requests. We do not need to submit read requests or
test completions for 0-sized flush commands.
=> OFI-NCCL: Return success for 0-sized flush messages

src/nccl_ofi_net.c
Plugin users can disable flush operations when using GPUDirect by using
`OFI_NCCL_GDR_FLUSH_DISABLE` environment variable.
When that happens, return NULL request to NCCL to avoid testing
completion for command which hasn't been issued.
=> OFI-NCCL: Return NULL request when flush is disabled

src/nccl_ofi_net.c
Plugin users can disable flush operations when using GPUDirect by using
`OFI_NCCL_GDR_FLUSH_DISABLE` environment variable.
When that happens, return NULL request to NCCL to avoid testing
completion for command which hasn't been issued.
=> [aws] OFI-NCCL: Return NULL request when flush is disabled

src/nccl_ofi_net.c
```
commit c67e9bede5deae9ce17290b7a4c07bf08e7d2e58 (HEAD -> master, rajachan/cleanups)
Author: Raghu Raja <craghun@amazon.com>
Date:   Tue Mar 23 21:11:05 2021 +0000
Initialize *provider to NULL
This prevents a garbage value in the branch that determines the need to
free the info object.
Signed-off-by: Raghu Raja <craghun@amazon.com>
commit f3d1a0eebb0384617c43dfcc05ffc7422ff669b6
Author: Raghu Raja <craghun@amazon.com>
Date:   Tue Mar 23 21:04:03 2021 +0000
Fix leak of list_temp memory.
Signed-off-by: Raghu Raja <craghun@amazon.com>
commit d45010f98f06f896ef7399bc38a6c34d922c78c4
Author: Raghu Raja <craghun@amazon.com>
Date:   Tue Mar 23 20:55:10 2021 +0000
Remove dead return code variable
`ret` is set in the error path, but never used.
Signed-off-by: Raghu Raja <craghun@amazon.com>
``` …
=> Code cleanups

topology/p4d-24xl-topo.xml
NCCL 2.9.6 added a couple of new attributes to the `pci` nodes in the topology file.  NCCL attempts to read any attributes that are not supplied in the file from sysfs.  However, this fails for the dummy PCI switch nodes because they don't actually exists in sysfs.  As a result NCCL fails to initialize.
Fix this by supplying dummy values for the dummy nodes.  The real device nodes have actual values (verified on a P4D system).
A better fix may be to make NCCL not attempt to read these values nodes with PCI switch device class, however that would require a new NCCL release.  Changing the topology file keeps the impact isolated to the NCCL plugin.
=> Add attributes required by NCCL 2.9.6 to P4D topology file

include/nccl_ofi.h, src/nccl_ofi_net.c
The plugin requests fork safe behavior from Libfabric.  This causes memory registrations to call `madvise` `MADV_DONTFORK` on the underlying pages.  However, there is no special handling for buffers that are not page-aligned (both in starting address and size): `rdma-core` will simply round to a page boundary.  This means that the data that happens to share a page with a registered buffer will not be propagated to a child when the parent forks.
=> Use page-aligned buffer for flush

README.md, src/nccl_ofi_net.c
Currently, aws-ofi-nccl requests FI_PROGRESS_AUTO in the
control and data progress mode of fi_info's hints. However,
EFA does not really support FI_PROGRESS_AUTO and will fail the
fi_getinfo call if user request it in future versions.
See https://github.com/ofiwg/libfabric/issues/7313.
aws-ofi-nccl does not really need FI_PROGRESS_AUTO, so it's safe
to set the fi_progress_mode as unspec in hints of fi_info so it
can use the default progress mode of the provider.
Signed-off-by: Shi Jin <sjina@amazon.com>
(cherry picked from commit 26cc1eac2b58b920137cb669a5f156cf89ef84eb)
=> [aws] Set the fi_progress_mode as unspec in the hints of fi_info

src/nccl_ofi_net.c
This makes use of compatibility checks in Libfabric and only enables
the feature when it is needed.  When running with a newer kernel with
copy-on-fork support and recent rdma-core, additional fork safety
support is not required and so the variable is silently ignored.
Using FI_EFA_FORK_SAFE instead of FI_EFA_FORK_SAFE does the right
thing on both new and legacy systems.
NCCLOFI-273
Use FI_EFA_FORK_SAFE environment variable instead of RDMAV_FORK_SAFE
Tested with all relevant providers on P4 instances
=> Use FI_EFA_FORK_SAFE environment variable to enable fork safety support

include/nccl_ofi.h, src/nccl_ofi_net.c, tests/nccl_connection.c, tests/nccl_message_transfer.c, tests/ring.c, tests/test-common.h
NCCL 2.12 Preview PR (https://github.com/NVIDIA/nccl/pull/624/commits/906eb4135c99c30d3a01648233840d3c49cacce2) introduces a new version V5 of the Net Plugin API.
This PR introduces the following major changes to support NCCL v2.12
* Add support for non-blocking connect/accept.
* Add API changes for irecv/isend (Currently, we do not support grouped receives)
* Set intranode latency for EFA networks
* Modify tests to support v2.12 testing and plugin configurations.
*Testing*
These changes have been tested with EFA provider on AWS EC2 infrastructure for NCCL v2.11 and NCCL v2.12.
Test include single and multi-node testing of plugin unit tests and all_reduce test from NCCL-tests benchmark suite.
By submitting this pull request, I confirm …
=> Add support for NCCL v2.12

include/nccl_ofi.h
This patch ensures that comm and req structure changes only applies to
NCCL v2.12 to ensure backwards compatibility.
=> OFI-NCCL: Bound structure changes to NCCL v2.12

src/nccl_ofi_net.c
*Issue #, if available: https://github.com/aws/aws-ofi-nccl/issues/98
Parts of #81 fix were missed during work on new features. Reintroduced
=> Allow ofi_iflush without memory registration if provider does not request it

src/nccl_ofi_net.c
Issue: *https://github.com/aws/aws-ofi-nccl/issues/102*
When exposing multirail devices, underlying providers typically set name of "virtual" ultiail device to NULL, while keeping speed field filled. Strdup of NULL leads to segfault.
=> Fix crash in case if underlying provider exposes multirail devices

src/nccl_ofi_net.c
Fix crash in case the underlying provider exposes multirail devices
Multirail devices commonly have a NULL name.  Do not assume that a name
has been provided by Libfabric
=> Merge multirail device name fix from master

src/nccl_ofi_net.c
An error entry may not be written immediately when a request fails and `fi_cq_read` returns -FI_EAVAIL.  In this case, `fi_cq_readerr` will return `-FI_EAGAIN`.  Do not fail if this occurs and retry instead.
=> Retry fi_cq_readerr if it returns -FI_EAGAIN

RELEASENOTES.md, configure.ac, src/nccl_ofi_net.c, topology/Makefile.am, topology/p4de-24xl-topo.xml
This patch adds the right system topology for P4De platform. The
topology file is very similar to already available P4D topology
with minor changes to GPUs device IDs (80G support).
This patch also introduces refactoring to topology update logic
to enable less painful addition of new platforms.
=> OFI-NCCL [Experimental]: Add P4De topology

RELEASENOTES.md, configure.ac
P64270667
Use `AC_PROG_CC_STDC` macro to automatically insert `-std=c99` into `CFLAGS` when needed. This takes care of a regression introduced in `v1.2.0` and all future issues.
=> Fix CentOS 7 build regression (master)

src/nccl_ofi_net.c
=> Fix EFA_NIC_DUP when only a single GPU is visible

src/nccl_ofi_net.c
In a non-blocking accept, it is possible for a listenComm to
progress and transition to an accepted state between two calls to
ofi_iaccept, for example if other calls to the plugin call the
progress function.
Signed-off-by: Sylvain Jeaugey <sjeaugey@nvidia.com>
=> Fix reuse check in ofi_iaccept

src/nccl_ofi_net.c, tests/Makefile.am
No issue logged.
The `max_tag` bitmask indicates which bits that can be used in a user tag. The next highest bit is used to denote a control message. Presently, the control message bit is set by OR'ing the negation of `max_tag`. However, this also sets the ignored bits and some providers flag this as an error. This patch sets only the control message bit in the tag.
There also is a minor update to the Makefile to allow setting `CC` used to build the tests. This is needed on systems where `CC=cc` is used to build MPI code.
=> Update Control Message Tag Bits

README.md, include/nccl_ofi_param.h, src/nccl_ofi_net.c
When using EFA provider with no GDR support, the number of network
connections are determined by the number of GPUs in the system. This
works well for systems with 8 GPUs.
However, there could be cases such as Pytorch XLA which only supplies
one GPU for each process using `CUDA_VISIBLE_DEVICES`. This results in
more collective comms time as the network hardware is under-utilized.
This patch allows users to configure the number of network connections
independent of the number of GPUs in the system.
Signed-off-by: Harish Tummalacherla <hartum@amazon.com>
=> OFI-NCCL [Experimental]: Allow configuring number of connections for EFA_NIC_DUP

Makefile.am, configure.ac
Fail if mpicc is not in the path and if --with-mpi= is not specified.
Fail in the configure, rather than the compile, if mpicc is not available.
=> Fail if mpicc is not in the path and if --with-mpi= is not specified.

README.md
The new config option --disable-tests allows skipping the tests directory when
building.  Include documentation of that option in the README.
=> Update README for disable tests.

README.md, include/nccl_ofi_param.h, src/nccl_ofi_net.c
None
Add support for implementing flush operations as a call to `cudaDeviceFlushGPUDirectRDMAWrites` on CUDA 11.3 and later. User must enable this by setting `OFI_NCCL_CUDA_FLUSH_ENABLE`.
=> Add support for CUDA GDR flush

src/nccl_ofi_net.c
In two cases, the error string expects two arguments, but the argument list
omits the numeric error code.
Signed-off-by: Ryan Hankins <rqh@amazon.com>
=> Fix error code value message for de-register.

include/nccl_ofi_param.h, src/nccl_ofi_net.c
None.
The PR extends the OFI memory registration modes supported by aws-ofi-nccl to include `FI_MR_ENDPOINT`, `!FI_MR_PROV_KEY`, and `!FI_MR_VIRT_ADDR`. Supporting application-specified registration keys required the addition of a key allocator.
This PR is a subset of #140.
=> Extend fi_read to support additional MR modes

src/nccl_ofi_net.c
None
Reqest `FI_THREAD_SAFE` threading support from the libfabric provider. This is required for multithreaded NCCL usage models (e.g. running NCCL perf tests with `-t ##`).
=> Request FI_THREAD_SAFE from the provider

src/nccl_ofi_net.c
None.
aws-ofi-nccl uses the latest plugin version in the NCCL installation `nccl_net.h`. The aws-ofi-nccl code currently supports the v5 interface, but will build as v6 with NCCL 2.13.x and later leaving the `regMrDmaBuf` field uninitialized. This has been benign since the C standard guarantees static objects are initialized to zero. But, it's a good example of why it's safer to make the plugin version explicit, rather than picking up the latest version from the NCCL header.
=> Add support for NCCL v2.13

src/nccl_ofi_net.c
Two changes to adjust the behavior around memory registration to work with the EFA provider.
=> Make master work with EFA provider again

README.md, configure.ac, doc/tracing.md, include/tracepoint.h, src/Makefile.am, src/nccl_ofi_net.c, src/tracepoint.c
Add LTTNG Tracing to the plugin, including instructions and configuration option.
Signed-off-by: Ryan Hankins <rqh@amazon.com>
LTTNG Tracing can be enabled at compile time as described in the included documentation
=> Add LTTNG Tracing to the plugin, including instructions and configuration option.

README.md, include/nccl_ofi.h, include/nccl_ofi_param.h, src/nccl_ofi_net.c
The number of completion queue entries we read in one call to fi_cq_read() should be based on performance parameters that are independent of the maximum number of in flight requests, so remove the coupling between the two.  In practice, this number should be tuned based on experimentation, but 4 is a good starting number.
The previous implementation could cause stack overflows, due to the large array being built every time to ofi_process_cq, so this patch fixes an immediate pain point.
=> Reduce count for fi_cq_read()

RELEASENOTES.md, configure.ac
Update the release version and the release notes in prep for the 1.5.0aws release.
=> Prep for 1.5.0aws release

src/platform-aws.c
Signed-off-by: Michael Axtmann <axtmannm@amazon.com>
Environment variable NCCL_TOPO_FILE is only set by plugin if variable undefined. This allows users to provide their own topology files to NCCL even though plugin would like to provide a topology file as well.
=> Avoid topology update if NCCL_TOPO_FILE is already set

include/stack.h
*Issue*
Following error occurs if include/stack.h is included in multiple compilation units.
.libs/*.o: In function `free_stack':
src/../include/stack.h:43: multiple definition of `free_stack'
.libs/nccl_ofi_net.o:src/Aws-ofi-nccl/src/../include/stack.h:43: first defined here
*Solution*
Add inline allocate_stack(..) and free_stack(..) in include/stack.h
=> Inline allocate_stack(..) and free_stack(..) in include/stack.h

include/nccl_ofi_param.h, src/nccl_ofi_net.c
The parameter lookup code always took a lock, which is really slow in the common case.  The flush parameter is used in the critical path, so this is not an awesome behavior.  This patch uses an initialized variable to signal whether or not the full lookup path is required.
While testing, I found that we didn't actually error check the integer converstion properly or the strdup properly, so this patch also fixes those two issues.
=> Shortcut parameter lookup to avoid lock

include/nccl_ofi.h, src/nccl_ofi_net.c, src/platform-aws.c
Two changes with the goal of skipping setting environment variables on Neuron.  The first uses local filtering instead of `FI_PROVIDER` for selecting the efa provider.  The second removes two configuration settings (NCCL_PROTO and fork save) that the Neuron team has asked us to avoid setting, in order to avoid calling setenv().
=> Skip setting environment variables on Neuron

include/stack.h
*Issue:*
Linking fails with error "undefined reference to `free_stack'" when the code is compiled without optimizations, e.g., without "-O3" in configure.ac.
Add static keyword to function free_stack(..) in include/stack.h
=> Fix error "undefined reference to `free_stack'" while linking

include/tracepoint.h, src/tracepoint.c
Rename HAVE_LTTNG HAVE_LIBLTTNG_UST to be consistent with configure.ac refactoring
HAVE_LTTNG changed to HAVE_LIBLTTNG_UST with the configure.ac changes, so update it in the source as well.
=> Rename HAVE_LTTNG HAVE_LIBLTTNG_UST to be consistent with configure.ac refactoring

configure.ac, m4/check_pkg_cuda.m4, m4/check_pkg_libfabric.m4, m4/check_pkg_mpi.m4, tests/nccl_message_transfer.c, tests/ring.c
Two semi-related portability changes.
First, in response to https://github.com/aws/aws-ofi-nccl/issues/183, remove the use of C99 in the tests, which use mpicc instead of $CC, making it difficult to use AC_PROG_CC / AC_PROG_CC_STDC to set the C version to C99 or later.
Second, fix issues found while testing when using Autoconf 2.70 or later.
=> Fix build compatibility issues

configure.ac
Set next release candidate version as v1.6.1 for v1.6.x branch.
=> [v1.6.x] v1.6.1 - set next release candidate version

configure.ac
To avoid confusion from release branch version(v1.6.0) and master development branch version, 
We are going to use "dev" suffix.
So, now, v1.6.0 released. so master branch version will be "v1.6.1-dev".
=> Update master branch version to v1.6.1-dev

src/nccl_ofi_net.c
Don't mark the request as completed until after accessing `req->lComm`.
=> Fix potential use after free issue

configure.ac, include/nccl_ofi.h, include/nccl_ofi_hcopy.h, src/Makefile.am, src/hcopy.c, src/nccl_ofi_net.c
@rashikakheria I'd like to add a new branch called `v1.6.0-hcopy` to make the HMEM copy overrides using GDRCopy available to users of aws-ofi-nccl. This patch overrides the `copy_from_hmem_iov` and `copy_to_hmem_iov` to directly use GDRCopy. This can be helpful with providers that don't have GDRCopy support or have some issue in GDRCopy support that needs to be worked around.
Could you please push a branch called `v1.6.0-hcopy` at the same location as the `v1.6.0` tag? Once the branch has been created, we can change the base branch of this PR to that branch instead of `v1.6.x`.
Thanks!
=> HMEM copy overrides using GDRCopy

configure.ac
1.6.1 won't be released from the master branch, so set the version to something without a version number in it (which means it will never be wrong...).
=> Update dev branch version

include/nccl_ofi.h, m4/check_pkg_libfabric.m4, src/platform-aws.c
fi_ext.h was introduced in Libfabric 1.13.0, so is not available in some versions of Libfabric that are supported by the plugin. All the features we use in fi_ext.h are already protected by compatibility checks, so only include fi_ext.h where it is needed and when available.
=> Only include fi_ext.h when needed

configure.ac, m4/check_pkg_libfabric.m4
Add test for older Libfabric and fail configure with an obvious error message, rather than amorphous compile errors.
If MPI isn't found, disable the functional tests (if not explicitly enabled) rather than causing compile errors.
=> Fix missing MPI or old Libfabric checks

configure.ac
rc1 has escaped, make way for rc2
=> Update version to 1.7.0rc2-aws

src/nccl_ofi_rdma.c
When allocating the send and recv communicators, we were allocating memory for a comm structure instead of a comm rail structure as part of the flexible array in both structures.  The comm structure is bigger than the rail structure (at least, with Libfabric 1.18.1), so this was wrong but harmless.
=> Allocate correct structure for rails

src/nccl_ofi_sendrecv.c
While the return path resets the request state to REQ_CREATED, the allocation path does not.  This means that there is an uninitialized variable usage the first time a request is used.
=> Initialize send/recv request state

src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
Backport both the fix to allocate the right rail size in the rdma transport and to properly initialize state in the sendrecv transport for the v1.7.x branch.
=> Backport 2 cleanups from master

src/platform-aws.c
During topology discovery, the NVLS detection code and AWS don't see eye to eye and cause memory corruption.  The investigation of the issue is on-going, but for now, disable NVLS to avoid memory corruption.
=> Temporarily disable NLVS on AWS platforms

src/platform-aws.c
Backport https://github.com/aws/aws-ofi-nccl/pull/218 to v1.7.x-aws
=> Backport NVLS workaround patch

src/nccl_ofi_rdma.c
This bug causes a segfault in some error conditions during RDMA protocol initialization, but otherwise shouldn't affect normal execution.
Check for NULL device before freeing substructures in error case
=> Check for NULL `device` in error handling

src/nccl_ofi_rdma.c
This bug causes a segfault in some error conditions during RDMA protocol initialization, but otherwise shouldn't affect normal execution.
(cherry picked from commit ee46396e5bfb8e0694d02799e308cad807389491)
=> Check for NULL `device` in error handling (cherry-picked from master)

include/nccl_ofi.h, src/nccl_ofi_net.c
support_gdr is a global variable which should declared as extern to prevent linking issues.  
Fix commit b9351fe28 ("Delay GDR detection to account for 1.18 API")
=> Fix compilation, declare support_gdr as extern

.gitignore, include/nccl_ofi.h, include/nccl_ofi_cuda.h, m4/check_pkg_cuda.m4, src/Makefile.am, src/nccl_ofi_cuda.c, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c, tests/functional/Makefile.am, tests/functional/cuda_check.c
CUDA 12 changed the libcudart major version number, but did not break the API of any of the interface functions that we use.  Rather than force everyone to build multiple versions of the plugin for moving between CUDA 11 and CUDA 12, dynamically load the libcudart.so dependency and reference the few CUDA symbols we use via function pointers.
Tested the functional tests and megatron-lm successfully.  Also added a direct call to a CUDA function in the plugin to verify that the new cuda_check test will throw a link-time error in that case.
=> Dynamically load cuda dependency

tests/functional/Makefile.am
The cuda_check functional test is really a link test, to make sure that we did not leak cuda symbols into the plugin.  It doesn't make sense for users to run it, so don't install it.
=> Don't install cuda_check test

include/Makefile.am
When we added ofi_nccl_cuda.{c,h}, forgot to update the makefile to include the headers.  This fixes "make dist".
=> Add ofi_nccl_cuda.h to dist tarball

src/nccl_ofi_freelist.c
In an error condition (memory registration failed) freelist frees the wrong pointer. We shouldn't be hitting this in normal conditions.
=> [freelist] Fix invalid free in error handling

README.md, include/nccl_ofi_sendrecv.h, src/nccl_ofi_net.c, src/nccl_ofi_sendrecv.c
Closes #204 
- Adds FI_CONTEXT2 to the list of data transfer context structures in the readme
- Changes the declaration of fi_context to become an array of two fi_context structs
- Adds FI_CONTEXT2 as a mode hint that is passed to the provider to infer support for FI_CONTEXT2
- Changes memset of ctx to extend for array of two ctxs, will still support initial behavior for fi_context
=> Add support for FI_CONTEXT2

src/nccl_ofi_freelist.c, src/nccl_ofi_rdma.c
1. If memory allocation fails, don't leave a dangling pointer in the freelist.
2. Check for non-NULL pointer before freeing `bounce_fl_item`.
=> Fix error-case memory handling in freelist and RDMA protocol

src/nccl_ofi_net.c
Topology should be freed regardless if RDMA init failed or succeed. As it's not needed after RDMA init call.
=> init: Free topology also when RDMA init fails

include/nccl_ofi.h, include/nccl_ofi_freelist.h, include/nccl_ofi_math.h, src/nccl_ofi_freelist.c, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_scheduler.c, src/nccl_ofi_sendrecv.c, src/nccl_ofi_topo.c
Change freelist to allocate memory in a page-aligned fashion, to work around zeroing out in the child on a fork.  Since this is the second time we've had this issue, also force a check so that internal allocations are page aligned.
=> Force allocation of registered memory to be page-aligned

src/nccl_ofi_cuda.c
When we refactored the CUDA code to support dlopen/dlsym instead of directly linking against CUDA, I missed a place where the FlushGPU code needed protecting against old versions of CUDA.  This patch allows the plugin to build against all versions of CUDA 11.
=> cuda: Support versions of CUDA prior to 11.3

src/nccl_ofi_freelist.c
Fix a bug where the number of padded freelist entries is wrongly calculated based on the entry count instead of the entry size.
=> Bugfix: Use freelist entry size to calculate padding

tests/unit/freelist.c, tests/unit/scheduler.c
The freelist and scheduler unit tests were recently broken by the change to freelist to allocate page-size boundary regions when growing.  Fix the unit tests by specifying the system page size (which is initialized during the core init function).
This is really a temporary fix, but we need to do some refactoring of the code base to better handle unit testing.  Until we do that, this works well enough.
=> freelist: Fix unit test initialization

src/platform-aws.c
Series of changes to clean up some code duplication and unnecessary global variable usage in the platform-aws file.  Also fix a couple bugs in using Libfabric APIs and handling edge cases around Libfabric versions.
Refs #241 
=> Refactor the platform-aws code

configure.ac, tests/unit/Makefile.am, tests/unit/scheduler.c
The unit tests themselves do not have any accelerator-specific constraint, we just needed some build config updates to link to the right archive.
Testing: `make check` with an `--enable-neuron` config runs to completion.
=> testing: Allow Neuron unit tests to build and run

README.md
Closes #255 
Improves readme documentation with respect to building the performance nccl-tests
=> Adding extra info for building nccl-tests

README.md, configure.ac, include/nccl_ofi_freelist.h, include/nccl_ofi_memcheck.h, include/nccl_ofi_memcheck_asan.h, include/nccl_ofi_memcheck_nop.h, include/nccl_ofi_memcheck_valgrind.h, m4/check_enable_sanitizer.m4, m4/check_pkg_valgrind.m4, m4/check_var_redzone.m4, src/nccl_ofi_freelist.c, src/nccl_ofi_rdma.c, tests/unit/freelist.c
* Add undefined behavior sanitizer (UBSAN) and memcheck frameworks (ASAN and Valgrind) as configure options.
* Add fine-grained memory access checks and redzones to freelist (in case memory checks are enabled)
This PR also fixes some memory leaks detected by the memcheck frameworks. 
=> Add ability to build with memcheck framework and undefined behavior sanitizer

src/platform-aws.c, topology/Makefile.am, topology/g5.48xl-topo.xml
G5.48xlarge has two NUMA nodes, so we have to provide GPU/NUMA mapping for optimal performance.
=> Add static topology file for platform g5.48xlarge

src/nccl_ofi_rdma.c
This PR fixes a bug that occurred when `fi_read` returns `FI_EAGAIN` in the case where a pending eager copy request fails to get reposted. The error code has been returned wrongly even though the request is returned to the pending requests queue.
This PR consists of two commits. The first commit fixes the bug, the second commit refactors and simplifies the code which has been made possible by the bug fix commit.
=> Bugfix: Correctly handle FI_EAGAIN return code when reposting a pending eager copy fails

src/nccl_ofi_freelist.c
Assert that we do not exceed entry limit in the freelist, and remove `<=` comparison on the unsigned `allocation_count`
Closes #236
=>  freelist: remove <= comparison on the unsigned allocation_count 

include/Makefile.am
A recent commit added new files that were not added to the relevant Makefile.am files, breaking "make dist".  Fix that.
=> dist: Add recent headers to Makefile.am

README.md, RELEASENOTES.md, src/nccl_ofi_freelist.c, src/nccl_ofi_rdma.c, src/platform-aws.c, tests/unit/freelist.c, tests/unit/scheduler.c, topology/Makefile.am, topology/g5.48xl-topo.xml
Backport the following PRs and update RELEASENOTES for the 1.7.3 release.
* https://github.com/aws/aws-ofi-nccl/pull/256
* https://github.com/aws/aws-ofi-nccl/pull/257
* https://github.com/aws/aws-ofi-nccl/pull/262
* https://github.com/aws/aws-ofi-nccl/pull/267
* https://github.com/aws/aws-ofi-nccl/pull/268
* https://github.com/aws/aws-ofi-nccl/pull/270
=> Backports for 1.7.3 release

src/nccl_ofi_api.c, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c
* Remove ofi_log_function from nccl_ofi_net.c. This resolves a multiple definition compiler error.
* Fix return values, we were erroneously returning errors in non-error situations.
=> Fix recent regressions in ring functional test

include/nccl_ofi_freelist.h, include/nccl_ofi_rdma.h, src/nccl_ofi_freelist.c, src/nccl_ofi_rdma.c, tests/unit/freelist.c
Since bounce buffers are the source of an RDMA read operation, we need
them to be 128B aligned for LL/LL128 protocols to work properly on local
reads.
=> Add parameter to align freelist entries

README.md, include/nccl_ofi_param.h, src/nccl_ofi_net.c, src/platform-aws.c
Running without GDR on P4+ instances is not currently supported, so fail in this case.
Also, warn if setting `FI_OPT_CUDA_API_PERMITTED=false` fails, forcing fallback to non-GDR.
=> Fail if GDR support is disabled on supported instances

README.md, src/nccl_ofi_net.c
This requests node-local communication capability from the OFI provider, which can be used for various reasons, including
* GDR detection
* Functional tests
* Platforms without NVLink
* When `NCCL_SHM_DISABLE=1`
=> Add FI_LOCAL_COMM to requested OFI caps

src/nccl_ofi_net.c
This was incorrectly changed to -ENOTSUP, causing failure when using TCP provider.
=> Return 0 when supplying default NIC props

include/nccl_ofi_param.h
empirical testing on P5 indicates that throughput is generally improved with a larger round robin threshold, although some sizes of larger messages for reduce-scatter and allgather were worse at 512 KiB.  So set the threshold to 256 KiB, which offers good improvements across the board, with no regression points.
=> Increase default round robin threshold to 256 KiB

README.md
For performance, we recommend running OFI-NCCL workloads without CPU binding. Add instructions for doing so with MPI and Slurm.
=> Add note about CPU binding to README

src/nccl_ofi_net.c
The Libfabric version is often useful when debugging.
=> Print Libfabric version as INFO when plugin starts

include/nccl_ofi.h, src/nccl_ofi_api.c, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
Clean up two NCCL resource limits we weren't handling properly.  First, our handling of multirecv and max outstanding requests was a mess, so follow NCCL's guidance, with the exception that we'll continue to support 128 outstanding instead of the most recent limit of 32.  If NCCL wants to give us more data, we'll take it.
Second, we were using entirely the wrong value for the max number of communicators.  That value is independent of the number of endpoints the domain supports and entirely dependent on tag space.
=> Cleanup NCCL resource limit handling

include/nccl_ofi_api.h, src/nccl_ofi_api.c, src/nccl_ofi_interface_nvidia.c
Finish cleanup from db64dbe and remove the init_v3 function.  Since we no longer try to match our request count to exactly what NCCL will use (which is good, since NCCL doesn't really obey that anyway), there's no point in an init_v3 function and we can remove it.
=> Remove unneeded compatibility init

src/nccl_ofi_api.c
When the api is calling itself for backwards compatibility interfaces, return codes are already translated from -errno to ncclResult_t codes, so don't do it a second time.
=> More return code cleanups

src/nccl_ofi_rdma.c
Fix three nits in the rdma protocol:
1) use static initializer for the topo lock mutex
2) Fix some prints that printed a misleading device id
3) clean up scoping and confusing use of dev_id and num_rails.
=> Clean up a couple of coding nits in the rdma protocol

src/nccl_ofi_rdma.c
For some reason, we set MAX_COMMS independently of the number of tag bigs (really, communicator ID bits) that we set aside, so change that to directly compute the MAX_COMMS value.
Also, when we were reporting the maximum number of communicators to NCCL, we were computing this value again from the tag bits rather than using the MAX_COMMS constant.  So fix that.
=> rdma: compute MAX_COMMS and use it everywhere

src/nccl_ofi_net.c, src/platform-aws.c
The patch-series contains 2 commits.
The 1st commit fixes a false warning due to parsing NCCL_PROTO env var with case sensitivity.
The 2nd commit changes the parse of OFI_NCCL_PROTOCOL to be case insensitive to be more consistent with how NCCL parse string env vars.
=> Compare env vars string parameters in case insensitive manner

include/nccl_ofi_cuda.h, m4/check_pkg_cuda.m4, src/nccl_ofi_cuda.c, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c, tests/functional/nccl_message_transfer.c, tests/functional/ring.c, tests/functional/test-common.h
Links the CUDA Driver library ("libcuda.so") to the OFI NCCL plugin instead of the CUDA Runtime library ("libcudart.so"), and replaces all CUDA Runtime API calls with their functional equivalents in the CUDA Driver API.
This commit prepares for adding dma-buf support for memory registration to the OFI NCCL plugin. The CUDA Runtime API does not have a function for generating a dma-buf handle from GPU memory, which as of the time of this commit is needed to verify that Libfabric supports dma-buf. NCCL itself uses the CUDA Driver API function "cuMemGetHandleForAddressRange" to generate dma-buf handles, so this commit prepares the OFI NCCL plugin to also be able to utilize the "cuMemGetHandleForAddressRange" function.
By submitting this pull request, I confirm that my contribution is made …
=> Replace CUDA Runtime API with Driver API

src/nccl_ofi_interface_neuron.c
a128996 recently introduced an abstraction to handle property differences across the API versions and removing the versioned definitions from the core code. This commit fixes the missing definition for neuron builds.
=> neuron: Fixes missing definition of nccl_ofi_properties_t

configure.ac
On systems without hwloc, configuration with `--enable-neuron`  completes successfully even if CHECK_PKG_HWLOC fails to find hwloc's devel library. The build later fails during compilation. This commit fixes the issue by requiring hwloc for any device build. This also fixes a typo in an unused value.
=> configure: Require hwloc for both Neuron and CUDA builds.

include/Makefile.am, include/nccl-headers/nvidia/tuner.h, include/nccl_ofi_tuner.h, src/Makefile.am, src/tuner/nccl_ofi_model.c, src/tuner/nccl_ofi_tuner.c
This commit introduces a custom tuner plugin for NCCL that bypasses the cost function used by NCCL today. The existing cost function is a combination of empirically derived costs, lat/bw reported by network plugins, and other coefficients that are unexplainable. These defaults seem to work well for IB, but not for EFA. The tuner is currently built and used only when running on AWS.
In this initial implementation, a simple Hockney model is used as a starting point, and only AllReduce is supported. Once we prove out the viability of the tuner plugin in selecting algorithm switch points, we can extend this to LogGP-based models to account for protocol specifics used in the aws-ofi-nccl plugin (such as the eager->rendezvous switch and the cost of control message exhange).
At the time of this …
=> nccl_ofi_tuner: Tuner component for aws-ofi-nccl

src/nccl_ofi_sendrecv.c
commit 60af0cce7d118742138cf26accbe37a3bba98014 
Author: Raghu Raja <raghunch@amazon.com>
Date:   Thu Jan 25 19:24:27 2024 +0000
bugfix: Fix a memleak when creating send_comm
ret_s_comm's allocation leaks when the connection info struct can not be
allocated.
Signed-off-by: Raghu Raja <raghunch@amazon.com>
commit d16d9d7deb9d9e0b25f08e5bc92af422cf671f31
Author: Raghu Raja <raghunch@amazon.com>
Date:   Thu Jan 25 19:01:12 2024 +0000
bugfix: Remove dereference to a NULL ptr
Signed-off-by: Raghu Raja <raghunch@amazon.com>
=> Misc fixes

README.md
AL1 is dead.  Let's not claim support for it.
=> Remove Amazon Linux 1 reference

src/Makefile.am
With my testing so far, I was explicitly preloading libnccl-net.so. This meant `ofi_log_function`, which was declared and allocated in nccl_ofi_api.c,  was available for the tuner to hook into NCCL's logger and reuse our logging macros. Folks who were relying on the right LD paths to be set — so that a dlopen() of  libnccl-net.so from NCCL would find the right library — ran into issues with missing `ofi_log_function` symbol (even when the network plugin was opened and loaded). I would have expected both cases to behave the same. Until I understand the difference, fixing the tuner sources to explicitly include nccl_ofi_api.c.
=> tuner: Fix nccl_ofi_tuner lib build

src/Makefile.am, src/tuner/nccl_ofi_tuner.c
NCCL dlopen()s ext-net plugins and tuner plugins with `RTLD_LOCAL`, so the symbols from loading libnccl-net.so is not available to the tuner by default. Declaring a separate logger for the tuner while being able to reuse the logging macros addresses this issue without having to add in the entirety of nccl_ofi_api.c objects into the tuner.
This properly addresses the issue that was patched with 64482e8.
=> tuner: Use a separate logger for tuner

src/tuner/nccl_ofi_model.c
=> tuner: Move overzealous print from WARN to TRACE level

.gitignore, configure.ac, include/Makefile.am, include/nccl_ofi.h, include/nccl_ofi_idpool.h, include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, m4/check_gcc_builtin.m4, src/Makefile.am, src/nccl_ofi_idpool.c, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c, tests/unit/Makefile.am, tests/unit/idpool.c
*Issue:*
The communicator ID, which is used as tag for tagged operations and is carried in the immediate value in WRITE operations, is always incremented and never reused.
This can be a problem especially for the RDMA protocol, which has only 12 bits for the communicator ID, so there is a possibility that we run out of IDs.
This PR makes changes to the way the RDMA protocol selects the communicator ID.
With these changes the ID is picked from a pool belonging to the endpoint and returned to the pool once the communicator is closed.
The pool keeps track of the used IDs by keeping a bit array and using a find-first-set operation to pick an available ID.
Also, with these changes the recv communicator ID in the RDMA protocol is no longer the same as the listen …
=> Allocator for communicator ID and MR keys

src/platform-aws.c
Some environments (e.g., pytorch) statically link NCCL. In these environments our current logic for checking NCCL version doesn't work, and we ended up erroneously disabling NVLS even when using a new enough NCCL version.
So, skip the version check if we can't load the NCCL dynamic library
=> Skip NVLS version check if NCCL *.so not found

src/tuner/nccl_ofi_tuner.c
=> tuner: Prevent double-free of dangling global context

m4/ax_platform_aws.m4, src/nccl_ofi_net.c
Libfabric prior to 1.18.0 did not have a way to disable CUDA calls, relying on a bunch of side-channel ways that were provider specific. Most providers don't make CUDA calls, although the shm utility provider does use CUDA.  Since EFA uses the shm provider, this could go sideways. Rather than try to deal with all the side channel corner cases to disable CUDA, just require Libfabric 1.18.0 or later when using the EFA provider or building on AWS.
=> Disable Libfabric < 1.18.0 when using EFA

include/nccl_ofi_log.h, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
Following the same pattern as NCCL, don't evaluate all the TRACE prints in the plugin unless enabled at configure time.  The configure flag already exists, and was used in the (non-performance) tests, but was not used in the code itself.
=> Make TRACE logs compile-time disabled

configure.ac, include/Makefile.am
Two fixes to the release dist generation. We were generating an empty dist even after fixing the UID issue.
With these changes:
```
<snip>
============================================================================
Testsuite summary for aws-ofi-nccl GitHub-dev
============================================================================
============================================================================
<snip>
=========================================================
aws-ofi-nccl-GitHub-dev archives ready for distribution:
aws-ofi-nccl-GitHub-dev.tar.gz
=========================================================
```
These will be cherry-picked to the v1.8.x-aws branch once merged.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> dist generation fixes

src/nccl_ofi_rdma.c
The idpool is freed when refcnt goes to zero, so it should be initialized again when refcnt increases.
=> Move idpool init to endpoint refcnt+ stage

.github/workflows/distcheck.yaml
During the 1.8.0-aws release, we realized the distribution generation had been broken for a while. Adding quick sanity checks as a Github Action to prevent this from happening in the future.
Runs to completion in 2 minutes.
=> ci: Add quick distribution checks to CI

.github/workflows/distcheck.yaml, src/nccl_ofi_api.c, src/nccl_ofi_rdma.c
=> Cherrypicks for v1.8.x-aws

RELEASENOTES.md, configure.ac
=> Release v1.8.1-aws

src/nccl_ofi_rdma.c
=> fix: Close the libfabric domain before closing the fabric

include/nccl_ofi.h, include/nccl_ofi_freelist.h, include/nccl_ofi_topo.h, src/nccl_ofi_freelist.c, src/nccl_ofi_net.c, src/nccl_ofi_ofiutils.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c, src/nccl_ofi_topo.c
The majority of this PR is removing the use of NCCL error codes in the core of the library, since we only use Libfabric error codes / -errno error codes to simplify reasoning about what error code is what.  This is a follow-on to last year's commit that made the change, since it looks like we missed a couple hundred places.
While cleaning that up, I noticed a place where we double initialized a mutex.  While harmless, it's also wrong, so clean that up as well.
=> Cleanup usage of NCCL error codes

.github/workflows/distcheck.yaml, CONTRIBUTING.md
extend distcheck workflow to run a second build under CodeChecker and report defects. Better configuration and fixes of reported defects will follow in a separate series, so for now, do not fail CI based on the existence of a report.
=> ci(github): run CodeChecker on PRs

src/tuner/nccl_ofi_tuner.c
ncclInvalidArgument is present both in neuron and nvidia whereas ncclInvalidUsage is only present in neuron headers. Callsite just wraps the value in ncclcheck and the meaning isn't meaningfully changed, so prefer the portable one.
=> fix(build): tuner: prefer ncclInvalidArgument

include/nccl_ofi.h, include/nccl_ofi_rdma.h, include/tracepoint.h, src/nccl_ofi_ofiutils.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
Switching to using untagged send/recv operations in the RDMA protocol. Tags were used for connection request and response, while control messages and eager messages used tag 0. The data previously present in the tag has been moved to the message itself. 
In addition, the control message is now using send() instead of senddata(), and the data is carried directly in the message.
Switching to untagged ops means that libfabric won't pre-select the message provided to the recv, so all SENDs are received into bounce buffers now.
This PR also removes the Send-After-Send ordering requirement from libfabric.
~~The only case where out-of-order sends can be a problem is if a receiver sends a connect response followed by a control message, and they arrive in the opposite order on the sender side. To …
=> Switch to untagged send/recv and remove SAS ordering requirement in the RDMA protocol

include/nccl-headers/error.h, include/nccl-headers/net.h, include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, include/tracepoint.h, src/nccl_ofi_idpool.c, src/tuner/nccl_ofi_model.c, src/tuner/nccl_ofi_tuner.c
Without this, we were incorrectly including neuron headers instead of CUDA ones when HAVE_CUDA was not defined. Also fail compilation if neither definition was found rather than having a fall-through case.
=> tuner: Fix missing config.h include

include/nccl_ofi_msgbuff.h, src/nccl_ofi_msgbuff.c, src/nccl_ofi_rdma.c, tests/unit/msgbuff.c
*Issue #*
The RDMA protocol is currently using 12 bits for the communicator ID, limiting the number of communicators to 4K, which can be hit in large deployments.
This PR is hanging the number of bits used for the communicator ID from 12 to 18 to reduce
the chance of running out of comm IDs. To fit the comm ID in the immediate data,
the message sequence number has been reduced from 16 bits to 10, which is still
more than enough since usually the number of inflight messages is not that high.
The msg_seq_num space can be further reduced if needed.
With the 16 bits msg_seq_num the msgbuff relied on the wraparound of 16 bits integers,
so to reduce the number of bits of msg_seq_num we need to make the wrapping around
explicit and implement a subtraction to deal with …
=> Extend range of communicator IDs for the RDMA protocol

RELEASENOTES.md, configure.ac
=> Setup 1.9.x release branch

src/nccl_ofi_rdma.c, tests/functional/nccl_message_transfer.c, tests/functional/ring.c
nccl_message_transfer and ring tests are overwriting in the cleanup the error value
returned from previous calls. This is making the tests quite worthless,
because if a function fails the returned error will be overwritten by the
deallocate_buffer call, so if the deallocation is successful, the tests
succeeds. This PR fixes that by using a different variable for the
return values in the cleanup and makes the test fail if either a function
call fails, or the cleanup fails, or both.
While testing this, I also noticed that we were ignoring the return value of 
send_close(), so I am also fixing that.
=> Fixes to error path in tests

include/nccl-headers/nvidia/tuner.h, include/nccl-headers/nvidia/tuner_v1.h, include/nccl-headers/nvidia/tuner_v2.h, include/nccl_ofi_tuner.h, src/tuner/nccl_ofi_model.c, src/tuner/nccl_ofi_tuner.c
=> Support new tuner API

src/platform-aws.c
This would prevent failures when NVLS size is smaller than the NVLSTree chunksize or silent fallback to a lower value, if NCCL were to change defaults.
=> Ensure NVLS and NVLSTree chunksizes are matched

src/tuner/nccl_ofi_tuner.c
This is a useful print to debug issues with algorithm selection at scale without having to rebuild the plugin. While the actual costs calculated are more developer-focused and can stay under TRACE, the final choice should be available to INFO when the TUNING debug subsystem is enabled.
NCCL 2.20 moved their algo/proto selection print from a TRACE to INFO for this reason as well.
=> Move the tuner's selecting debug print to INFO level

configure.ac, src/Makefile.am, tests/functional/Makefile.am, tests/unit/Makefile.am
Build the plugins (tuner and net) as DSOs instead of shared libraries  by adding the `-module -avoid-version` flags to the library LDFLAGS.
Fix up a couple of issues that fall out of that change.
=> Build plugins as DSOs intead of shared libraries.

configure.ac
The tuner uses the log2 function that is defined in libm, but we were relying on someone else to pull in libm, which is technically wrong.  Checking for what library provides libm fixes this issue, with the side effect of adding a -lm to the link line for the libnccl-net plugin.  This is not strictly needed, but linkers also will do the right thing most of the time and not actually include that dependency in the list of libraries that must be loaded for the plugin.  So this is a lot less configure code compared to each plugin having its own LIBS list, for the same outcome.
=> Add -lm to library list for plugins

m4/check_pkg_cuda.m4
Work around an issue building in containers due to libcuda.so being stubbed out by only checking for libcuda if functional tests are built, and disabling the functional tests by default.
=> Work around container build issue

.gitignore, include/nccl_ofi.h, src/nccl_ofi_api.c, src/nccl_ofi_net.c, src/nccl_ofi_ofiutils.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c, src/nccl_ofi_topo.c, tests/unit/scheduler.c
```
a15e2c7 nit: silence clangsa warnings on pointer mismatch
ff22381 nit: remove extraneous assignment to self
7ae42c7 nit: test: unit: fix early-return leaks
2eacffd fix: net: strlen(NULL) is UB
9e79a7f fix: net: get_provider: always set return count
1cc9939 fix: topo: dont ignore errno
fe829de fix: api: initialize ofi_accept return value
```
Fixes various reports found in [clang-static-analyzer/CodeChecker reporting](https://github.com/aws-nslick/aws-ofi-nccl/actions/runs/8002290167). Others remain.
=> static analyzer fixes

.github/workflows/distcheck.yaml, include/Makefile.am, m4/ax_platform_aws.m4
b1bc116 (HEAD -> fix-dist, rajachan/fix-dist) build: Add headers that were missing in the distribution
176555b ci: Add --enable-platform-aws to Github distcheck action
60e3f8f m4: Pass enable-aws-platform config to distcheck's config
---
Confirmed with a Github distcheck build in my repo's actions that the AWS platform config is now included.
=> Fix for #382

configure.ac, m4/check_pkg_cuda.m4
2cebf50 cuda: Tie libcuda check and tests
ea2f19b Add -lm to library list for plugins
1475da5 Add libpthread to library list
=> Cherry-picks for 1.9.x-aws

.github/workflows/distcheck.yaml, include/Makefile.am, m4/ax_platform_aws.m4
b93bfbd build: Add headers that were missing in the distribution
c467d39 ci: Add --enable-platform-aws to Github distcheck action
306a4ad m4: Pass enable-aws-platform config to distcheck's config
=> More cherry-picks for 1.9.x-aws 

include/nccl_ofi.h, include/nccl_ofi_param.h, include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c, src/platform-aws.c
On Neuron, create the domain in the endpoint structure.  On P-series, keep it in the device structure.  This is because, on Neuron, we lock when accessing the domain, so retaining separate domains per thread and per endpoint reduces contention
Create an accessor method, get_domain(), that abstractly accesses the endpoint by protocol and architecture.
=> Separate the domain, and abstract access to the domain.

src/nccl_ofi_rdma.c
Move call to `prepare_recv_conn_resp_req` before entry point of `COMM_SEND_CONN` stage.
This resolves a potential memory leak where `prepare_recv_conn_resp_req` is called multiple times on EAGAIN.
=> rdma: (fix) memory leak: don't alloc `recv_conn_resp_req` on EAGAIN

configure.ac, include/Makefile.am, include/nccl_ofi_rdma.h, include/nccl_ofi_tracepoint.h, include/tracing_impl/lttng.h, include/tracing_impl/nvtx.h, m4/check_pkg_lttng.m4, m4/check_pkg_nvtx.m4, src/nccl_ofi_net.c, src/nccl_ofi_ofiutils.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
Add support for NVTX tracepoints (RDMA protocol only). Enabled at compile-time with `--with-nvtx`.
Re-vamped version of #363 from Nick.
=> Add NVTX tracing support

src/tuner/nccl_ofi_tuner.c
The context parameter to `nccl_ofi_tuner_get_coll_info` had an erroneous dereference.
=> fix(tuner): remove spurious deref from context arg

src/nccl_ofi_rdma.c
According to libfabric specs, the len field in a completion entry only applies to completed receive operations. We were using it for send completions as well, which is currently working in the EFA provider, but there is no guarantee that this will be true in the future and for other providers. This PR is fixing this issue.
=> rdma: (fix) do not use cq_entry.len in send completions

src/tuner/nccl_ofi_tuner.c
The context parameter to `nccl_ofi_tuner_get_coll_info` had an erroneous dereference.
(cherry picked from commit 4c9a063e2a16c01e29ad08e9e83180d24d7ea5dc)
=> v1.9.x: fix(tuner): remove spurious deref from context arg

configure.ac
We've already made changes to this branch so it is no longer 1.9.1.
=> 1.9.x: Bump version to 1.9.2a1-aws

.ci/aws/Jenkinsfile, .ci/aws/aws_ofi_nccl_pr_ci.yaml
Stop AWS CI from timing out when under heavy load (24 hours should allow 12 PRs to be submitted at the same time without timing out).
=> .ci/aws: Increase timeout + minor edit

include/nccl_ofi_rdma.h, src/nccl_ofi_rdma.c
This PR has 3 fix commits:
1. According to libfabric specs, the buf field in a recv completion entry
only applies when the receive buffer was posted with the `FI_MULTI_RECV` flag.
So we shouldn't use it, and rely on the bounce buffer address instead.
2. There were error cases when `create_send_comm` would return an error before freeing
the allocated resources first. This fixes the error path to avoid that.
3. A mostly aesthetic change. 
The message type is an enum that goes on the wire in conn/conn_resp/ctrl messages.
For this reason we want the datatype size to be fixed, so we can typedef
`nccl_ofi_rdma_msg_type_t` to `uint16_t` rather than explicitly assign the enum to a
`uint16_t`.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> rdma: do not use cq_entry.len in send completions, plus fix memory leak

include/tracing_impl/lttng.h, m4/check_pkg_lttng.m4, src/tracepoint.c
* m4: typo: `check_pkg_found` => `check_pkg_define`
* tracepoint.c: typo in include path
* tracing_impl/lttng.h: Fix header guards as required by LTTNG
=> fix(lttng): fix LTTNG support in master branch

.ci/aws/aws_ofi_nccl_pr_ci.yaml
Compile aws-ofi-nccl in debug to enable asserts, and make the CI more effective at catching bugs.
=> .ci/aws: Compile aws-ofi-nccl in debug

.ci/aws/aws_ofi_nccl_pr_ci.yaml
Compile aws-ofi-nccl in debug to enable asserts, and make the CI more effective at catching bugs.
(cherry picked from commit 3d88b88bdef0de37b2ac1d13e23d27487b3a7c17)
=> [v1.9.x-aws].ci/aws: Compile aws-ofi-nccl in debug

include/tracing_impl/lttng.h, tests/unit/scheduler.c
Reverts recent lttng fix due to breaking builds where lttng is available via /usr/include, but not requested at configure time.
Fixes a warning on a unit test with some compilers by initializing a null pointer.
=> revert, unit fix

.ci/aws/Jenkinsfile
Add p3dn testing to Jenkins.  This PR will not work until p3dn capacity arrives in the account.
=> .ci/aws: Add p3dn testing to Jenkins

.ci/aws/Jenkinsfile, .ci/aws/common.groovy
- Include full instance type name in job name (size limit was for pcluster, not being used)
- Milestones force kill after 20s, so move cleanup to before we start a new job
- This is a temporary solution b/c it causes us to not be able to add more resources to the server, will figure out a better solution 
=> .ci/aws: Kill all clusters of same instance type/region on lock acquisition

.ci/aws/Jenkinsfile
The p5's that the CI was using in us-east-1 are no longer available.  Migrate p5 testing to af-south-1.
=> .ci/aws: Move p5 ODCR to af-south-1

.ci/aws/Jenkinsfile
(cherry picked from commit 31d2c083f8009a836bda95ff712fc1819e238a77)
=> [v1.9.x-aws].ci/aws: Move p5 ODCR to af-south-1

.ci/aws/Jenkinsfile, .ci/aws/common.groovy
* Always make kill_all_clusters() succeed
* There is a race that currently exists where cleanup is started by an aborted job, and when the new job comes in, and runs kill_all_clusters(), it fails b/c the previous cleanup finishes half way through the new cleanup.  By making this script always succeed, we will continue executing the pipeline, which is the desired behavior in this situation.
* Wait until ODCR has enough capacity to run jobs before we attempt to launch
* The p3dn ODCR is not immediately refilling the available instance count after all the instances have been terminated.  This has put a race condition in our code which sometimes causes us to get ICE'ed.  Attempt  to fix the ICE by waiting till the ODCR has the required capacity before attempting to launch instances with it. …
=> .ci/aws: Jenkins CI Stability Fixes

src/tuner/nccl_ofi_tuner.c, tests/unit/static/current_tuner_decisions.csv
Our tests showed that the tuner is currently making the wrong decision at 4GB on 16 P5s, which caused a regression. This is a temporary workaround to force NVLSTREE while we work to make the model more accurate.
=> tuner: prefer NVLSTREE on 16 nodes at 4GB

.github/codechecker.yaml, .github/codechecker_skips.txt, .github/workflows/distcheck.yaml, include/Makefile.am, include/nccl_ofi_rdma.h, include/nccl_ofi_tracepoint.h, include/tracing_impl/lttng.h, m4/check_pkg_lttng.m4, src/nccl_ofi_net.c, src/nccl_ofi_ofiutils.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c, src/tracepoint.c, src/tuner/nccl_ofi_tuner.c, tests/unit/scheduler.c
Cherry-picked commits (newest on top):
- [tuner: prefer NVLSTREE on 16 nodes at (3GB, 5GB\]](https://github.com/aws/aws-ofi-nccl/commit/83f8fa96c93375b8aede8f74b20a484dc5762060)
- [ci(github): add an al2023 build](https://github.com/aws/aws-ofi-nccl/commit/309d83495910db22a118d14f06f053d98bfc468c)
- [ci(github): add an lttng build](https://github.com/aws/aws-ofi-nccl/commit/a653337ec332d8b8c01b3f59210b1935d3e7afe4)
- [ci(github): split codechecker to separate job](https://github.com/aws/aws-ofi-nccl/commit/dc79f83d6c728bc9461ee5ef256f8ece74ab843d)
- [ci(github): add a configuration file for codechecker](https://github.com/aws/aws-ofi-nccl/commit/3bd89acfa8461d9157b72e6cf46e446f5e7eef95)
- [ci(github): add concurrency block](https://github.com/aws/aws-ofi-nccl/commit/6bf425eab77833215d87900 …
=> Cherry-picks for 1.9.2-aws

.ci/aws/Jenkinsfile, CODEOWNERS
* This changes pins our alinux2 ami to a fixed manually prebuilt AMI.  This is a work around for our image builder problems where we can only build a p3dn ami on a p3dn.
* Adds a 5 minute sleep before launching p3dn's as an attempt to fix the p3dn ICE'ing issues
=> .ci/aws: Add stable p3dn testing into CI

src/nccl_ofi_interface_nvidia.c
NCCL's v7 plugin APIs added the sendDevComm/recvSendComm parameter to
connect/accept. We are not using it, but it can happen that NCCL calls
connect/accept with this parameter equal to NULL, so we need to be careful
before dereferencing the double pointer. Since IB and other plugins are
just ignoring this parameter, we will do the same.
=> fix: check if DevComm is valid before setting it

include/Makefile.am, include/nccl_ofi_deque.h, include/nccl_ofi_freelist.h, include/nccl_ofi_param.h, include/nccl_ofi_pthread.h, src/Makefile.am, src/nccl_ofi_idpool.c, src/nccl_ofi_msgbuff.c, src/nccl_ofi_pthread.c, src/nccl_ofi_rdma.c, src/nccl_ofi_scheduler.c, src/nccl_ofi_sendrecv.c, src/platform-aws.c, src/tuner/nccl_ofi_tuner.c
This patch series fixes two issues with locking in the code base.  First, we were inconsistent about whether or not we checked error codes from pthread_mutex_{lock,unlock} and whether or not the error checking was in an OFI_UNLIKELY check.  With this patch, there's no checking return codes from the newly added wrappers, and we will abort() if any lock/unlock fails (since there's really no recovery from that).
Second, while it's really nice to be able to enable error checking locks when debugging changes to locking, so add an environment variable (that effectively defaults to "not enabled") to allow error checking mutexes, which (with the first change) will abort() as soon as we goof up locking.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> Mutex behavior cleanup / improvements

.gitignore, configure.ac, include/Makefile.am, include/nccl_ofi.h, include/nccl_ofi_config_bottom.h, include/nccl_ofi_deque.h, include/nccl_ofi_pthread.h, src/nccl_ofi_cuda.c, src/nccl_ofi_deque.c, src/nccl_ofi_freelist.c, src/nccl_ofi_idpool.c, src/nccl_ofi_msgbuff.c, src/nccl_ofi_pthread.c, src/nccl_ofi_scheduler.c, src/nccl_ofi_topo.c
While working on the pthread wrapper patch (https://github.com/aws/aws-ofi-nccl/pull/431), I got caught up in having to include nccl_ofi.h (and then breaking some bits) for OFI_LIKELY, which lead me down a rabbit hole.
=> Cleanup nccl_ofi.h / utility macros.

include/nccl_ofi.h, include/nccl_ofi_rdma.h, src/nccl_ofi_api.c, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
As part of some work to clean up the threading model implementation (in particular, we really need a domain concept as the point of thread ownership, given the desire to move to FI_THREAD_DOMAIN), this patch series fixes a simple bug, removes some dead code, and adds a more well rounded interface for plugin and device classes.
=> Class interface cleanups for plugin and device structures

src/nccl_ofi_rdma.c, tests/functional/nccl_message_transfer.c, tests/functional/test-common.h
This adds the support for the case when the size of the recv() is less than the size of the send(). 
In non-eager sends, when the ctrl msg arrives with a remote length less than the size in the send call, we reduce the size of the send request. The test function for the send will return the smaller size. This implicates that we delay creating the schedule to when we have the control message, instead of when the send is called.
In eager mode, the send transmits the amount of data passed with the send, but the recv side will truncate the data before starting the copy from the bounce buffer to the user buffer. The ctrl message will notify the sender of the reduced size, so the sender will know (when calling test()) of the truncation.
By submitting this pull request, I confirm that my …
=> rdma: support recv size < send size

src/nccl_ofi_rdma.c, tests/functional/nccl_message_transfer.c, tests/functional/test-common.h
Additional cherry-picked commits (newest on top):
- [tests: nccl_message_transfer to test different sizes](https://github.com/aws/aws-ofi-nccl/commit/b1e7d65a02b57e97cc3e66ccd2c76cef9c5745d3)
- [rdma: support recv size < eager send size](https://github.com/aws/aws-ofi-nccl/commit/65c1122204b47201ad323f76118f82719cf804ed)
- [rdma: support recv size < non-eager send size](https://github.com/aws/aws-ofi-nccl/commit/5f2c4073a14ccc1e69308127b2dd12cf55799202)
=> More cherry-picks for 1.9.2-aws

src/nccl_ofi_interface_nvidia.c
Additional cherry-picked commit:
- [fix: check if DevComm is valid before setting it](https://github.com/aws/aws-ofi-nccl/commit/98cf01188ada270bcc1decebf6ac97fccbf10d8b)
=> One more cherry-pick for 1.9.2-aws

.ci/aws/aws_ofi_nccl_pr_ci.yaml
=> .ci/aws: Add aws-ofi-nccl functional tests to ci

src/nccl_ofi_interface_nvidia.c, src/nccl_ofi_sendrecv.c, tests/functional/nccl_message_transfer.c, tests/functional/test-common.h
1. Set `regIsGlobal = 0` always until we resolve perf (see comment in commit)
2. Test recv size<send size (in functional test) only if regIsGlobal=1
3. sendrecv: (fix) do not use cq_entry.len in send completions
=> Three patches in support of upcoming release

.ci/aws/aws_ofi_nccl_pr_ci.yaml, src/nccl_ofi_interface_nvidia.c, src/nccl_ofi_sendrecv.c, tests/functional/nccl_message_transfer.c, tests/functional/test-common.h
* Set regIsGlobal=0
* Remove send truncation from functional test for `regIsGlobal=0`
* Fix SENDRECV protocol size result (cq_entry.len not valid in send completions)
=> [v1.9.x-aws] regIsGlobal=0 and related fixes

include/nccl_ofi_tracepoint.h, include/tracing_impl/lttng.h, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
This adds dev_id to NCCL_OFI_TRACE_COMPLETIONS trace point, which enables collecting SEND/RECV completions per dev_id. Adding dev_id is also aligned with existing NCCL_OFI_TRACE_SEND/NCCL_OFI_TRACE_RECV trace points that already have dev_id to the trace.
=> rdma: add dev_id to req completion LTTNG trace point

configure.ac
The use of OFI_NCCL_ARCHIVE was removed in commit: f1a015c916060efc3849331e93a33f6bce80d1cb
(Build plugins as DSOs instead of shared libraries)
Remove the reference to it from configure.ac.
=> Remove unused reference to OFI_NCCL_ARCHIVE in configure.ac

include/nccl_ofi_config_bottom.h, include/nccl_ofi_tuner.h, src/nccl_ofi_interface_neuron.c, src/nccl_ofi_interface_nvidia.c
enables builds with `-fvisibility=hidden` to work correctly, at least
under some compilers.
The end-goal is to get cross translation unit optimization and LTO working well,
to negate some of the negative impacts of our usage of globals
=> tree: set export symbol visibility

include/nccl_ofi_pthread.h
> ../include/nccl_ofi_pthread.h: In function 'nccl_net_ofi_mutex_trylock_impl':
> ../include/nccl_ofi_pthread.h:75:45: error: 'EBUSY' undeclared (first use in this function)
>    75 |         if (OFI_UNLIKELY(ret != 0 && ret != EBUSY)) {
-------
*Issue #, if available:* n/a
*Description of changes:* add a missing include
=> pthread: add missing errno include

m4/check_pkg_libfabric.m4, src/nccl_ofi_rdma.c, src/platform-aws.c
To use the zero-copy path in the EFA provider, for fi_send/fi_recv operations, we need:
1. to have no ordering requirements (already satisfied)
2. to not use tagged operations (already satisfied)
3. to set the FI_OPT_MAX_MSG_SIZE endpoint option to a value less than mtu. Since the larger messages we exchange with fi_send/fi_recv are eager messages, we need them to be less than the mtu, which is satisfied with the current default eager threshold size of 8KB.
This commit is setting the FI_OPT_MAX_MSG_SIZE option to the max size we use for fi_send/fi_recv operations, only for AWS platforms, since this is not needed for other providers.
=> Use the zero-copy path in the EFA provider for the RDMA protocol

include/Makefile.am, include/nccl_ofi.h, include/nccl_ofi_platform.h, src/nccl_ofi_net.c, src/nccl_ofi_ofiutils.c, src/nccl_ofi_rdma.c, src/platform-aws.c
Some providers (including EFA) rely on having a consistent ordering of
rail indices for best performance.
On EFA, ensure plugin's multi-rail protocol consistently sorts rails in order of
VF index for best performance.
=> Add platform hook to sort rails and EFA implementation

src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
When there is a completion error, the plugin is calling fi_cq_strerror() to get a string message corresponding to the specific error. However, there are errors that are not recognized by libfabric, and that function will just return "Unknown error". This PR is adding the prov_errno value, together with the string representation, to the error log statement, to make it easier to debug such cases.
=> Log prov_errno number in case of completion errors

.github/workflows/distcheck.yaml
=> test: Have GitHub workflows build functional tests

configure.ac, include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, src/nccl_ofi_api.c, src/nccl_ofi_cuda.c, src/nccl_ofi_deque.c, src/nccl_ofi_freelist.c, src/nccl_ofi_idpool.c, src/nccl_ofi_msgbuff.c, src/nccl_ofi_net.c, src/nccl_ofi_ofiutils.c, src/nccl_ofi_rdma.c, src/nccl_ofi_scheduler.c, src/nccl_ofi_sendrecv.c, src/nccl_ofi_topo.c, src/platform-aws.c, src/tuner/nccl_ofi_tuner.c, tests/functional/nccl_connection.c, tests/functional/nccl_message_transfer.c, tests/functional/ring.c, tests/unit/freelist.c, tests/unit/idpool.c, tests/unit/msgbuff.c, tests/unit/scheduler.c
```
Unmerged into upstream/master (10)
e516a88 build: enable -W++-compat in "picky compiler"
f270cbf topo: use const char* where possible
92350cb api: listen: use retval_translate
784801d cuda: use typeof() to avoid void* cast error
cee0479 tree: prefer empty brace initializer to {0}
e4b7f49 tree: prefer static inline to static
94f92c0 tree: pthread: cast getspecific calls to types
3e996b2 topo: don't use hwloc inline structs
b43b883 tree: cast void*s from allocators
c0aa2bf transports: create invalid states, types.
```
Series of changes fixing build issues with `-Wc++-compat`, which is an exclusive-to-C option that looks for C-isms that are disallowed under C++. There are other issues that this doesn't fix (mainly, gotos that skip over initializers), but this is …
=> fix -Wc++-compat errors

.gitignore, include/Makefile.am, include/contrib/uthash.h, include/contrib/utlist.h, include/nccl_ofi_ep_addr_list.h, include/nccl_ofi_param.h, include/nccl_ofi_rdma.h, src/Makefile.am, src/nccl_ofi_ep_addr_list.c, src/nccl_ofi_ofiutils.c, src/nccl_ofi_rdma.c, tests/unit/Makefile.am, tests/unit/ep_addr_list.c
This patch changes the plugin's endpoint creation behavior as follows:
1. All send communicators will use the same endpoint.
2. When creating an endpoint for receive communicators, first check if
any existing endpoint is not already connected to the source endpoint.
Only create a new recv endpoint if all existing endpoints are already
connected to the source endpoint.
Also has some supporting refactoring commits.
=> Separate endpoints for recv communicators from same source endpoint

.github/workflows/distcheck.yaml
CI started failing in the past few days unexpectedly. We need to work around AL2 glibc being older than expected for the node binary that the github clone action needs. Originally, pinning to an older version (v3 instead of v4) was sufficient. Now, we need to add an environment variable that allows it to continue to use node16 (which works fine against al2 glibc) instead of upgrading to node20 (where al2 glibc is too old). 
=> ci: add another workaround for ancient al2 glibc

.ci/aws/aws_ofi_nccl_pr_ci.yaml
Since I have write access to aws-ofi-nccl, the Jenkins changes that I make will be executed for this PR.  You can see the logs on this PR to determine if they are better or worse.
=> .ci/aws: Disable verbose printing in order to easily see error

configure.ac
A recent patch added -Werror=c++-compat whenever picky compilers was enabled.  Because picky compilers are enabled by default, we accidently set -Werror=c++-compat for both developers and end users.
This patch undoes that change, but also sets -Werror any time a .git directory in the source directory.  Since release tarballs do not include a .git directory, this effectively limits setting -Werror to developers.
=> Set -Werror for "developers", remove for others

src/tuner/nccl_ofi_tuner.c
The strtoll manual says:
> the calling program should set errno to 0 before the call, and then determine
> if an error occurred by checking whether errno has a nonzero value after the
> call.
When reading the `NCCL_BUFFSIZE` environment variable, the tuner was calling `strtoll` without setting errno first. So, even when `strtoll` was successful, the tuner was most of the time seeing `errno=EAGAIN` set by some previous function, and for this reason was considering buffsize to be the default value of 4MB. This was a problem when, by chance, errno was zero for some rank, so the buffsize was correctly set for some rank and not the others, which caused the tuner to make different algorithm choices for different ranks, causing the test to hang. This commit is setting `errno=0` before the …
=> tuner: (fix) setting errno=0 before strtoll

src/nccl_ofi_api.c
The plugin was printing the "Initializing aws-ofi-nccl" log statement twice per rank, once in `nccl_net_ofi_init()` and again, immediately after, in `nccl_net_ofi_create_plugin()`.
This PR is removing the first one.
=> log: removed double "Initializing aws-ofi-nccl" log

.gitignore, include/Makefile.am, include/nccl_ofi.h, include/nccl_ofi_mr.h, include/nccl_ofi_param.h, src/Makefile.am, src/nccl_ofi_interface_nvidia.c, src/nccl_ofi_mr.c, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c, tests/unit/Makefile.am, tests/unit/mr.c
With user buffer registration capability, when a network plugin reports support for regIsGlobal, NCCL does maintain a cache of registration handles (originally registered with a loopback communicator). At the time of a send, it still calls into the regMr hook of the network plugin for the actual communicator that will be used for the data transfer (in case the net plugin requires communicator-specific state for the registration). With regIsGlobal guarantee, it is possible for NCCL to reuse the handle it has cached, but it does not do that today. This commit introduces a MR cache that is similar in design to NCCL's internal cache (with a linear search in the cache to find a registration that fully covers the list of pages of the buffer in question) to avoid redundant (and expensive) …
=> Introduce a memory registration cache for the net plugin

.ci/aws/Jenkinsfile
Will help stabilize CI and reduce runtime.
=> .ci/aws: Use prebuilt AMI with latest EFA Installer

src/nccl_ofi_rdma.c
When RDMA protocol is used with domain-per-thread feature enabled, protocol initialization segfaults since fid_domain member variable of device is accessed even though fid_domain is only stored in plugin endpoint structure in case domain-per-thread feature is used.
Fix bug by accessing fid_domain member of plugin endpoint structure instead.
=> rdma: (fix) Use ep domain to create fi endpoint resources

include/nccl_ofi_param.h
For most use cases of interest, the eager protocol hurts performance more than it helps on Neuron platforms.  So we set the default eager size to 0 by default when on Neuron, skipping the eager protocol.
We should make this platform specific rather than the large hammer to set default values from the platform file today, which is something that we should really fix.  But, as always, we're a little short on time, so this will do for now.
=> neuron: Disable rdma eager messages by default

src/nccl_ofi_rdma.c
When RDMA protocol is used with domain-per-thread feature enabled, protocol initialization segfaults since fid_domain member variable of device is accessed even though fid_domain is only stored in plugin endpoint structure in case domain-per-thread feature is used.
Fix bug by accessing fid_domain member of plugin endpoint structure instead.
Signed-off-by: Michael Axtmann <axtmannm@amazon.com>
(cherry picked from commit 947f56f7a7530a42e4474e16b322fdf69268f54d)
=> Cherry pick commit: rdma: (fix) Use ep domain to create fi endpoint resources

include/nccl_ofi_param.h
For most use cases of interest, the eager protocol hurts performance more than it helps on Neuron platforms.  So we set the default eager size to 0 by default when on Neuron, skipping the eager protocol.
We should make this platform specific rather than the large hammer to set default values from the platform file today, which is something that we should really fix.  But, as always, we're a little short on time, so this will do for now.
(cherry picked from commit bfc2e7c877f4eca2ca574cdf8c8662ede68e6e33)
=> (v1.10.x backport) neuron: Disable rdma eager messages by default

include/nccl_ofi_param.h
This patch increases CQ read count to 16.
Experiments turned out that reading up to 16 (instead of 4) CQ entries at once improves performance.
=> param: increase CQ read count to 16 for performance

include/nccl_ofi_rdma.h, src/nccl_ofi_rdma.c, tests/functional/nccl_connection.c, tests/functional/nccl_message_transfer.c, tests/functional/ring.c
The RDMA protocol connection establishment code currently doesn't wait for the connect response msg (from `accept()` side) before completing.
This can lead to a situation where `connect()` completes, and the corresponding `accept()` hangs because the connect side does not have enough recv buffers available to receive the connect response msg from the accept side.
We particularly see a deadlock in zero-copy mode, where plugin is responsible for posting all receive buffers, likely because plugin posts fewer receive buffers than Libfabric does.
This commit makes `connect` wait to return a valid `s_comm` until the connect response message is received. It also removes code in `send` and `send_close` to handle cases where the `s_comm` connection is not yet complete; these cases aren't necessary …
=> rdma: wait for connect response msg in connect()

include/nccl_ofi_param.h
Backport: This patch increases CQ read count to 16.
Experiments turned out that reading up to 16 (instead of 4) CQ entries at once improves performance.
Signed-off-by: Michael Axtmann <axtmannm@amazon.com>
(cherry picked from commit 346be40c777c996932e9474d781dc6fb8dafbc56)
=> Backport to 1.10.x-awsparam: increase CQ read count to 16 for performance

include/nccl_ofi_rdma.h, src/nccl_ofi_rdma.c
Previous patches to the plugin called `fi_cancel` to explicitly cancel all posted receive ops. Libfabric in zero-copy mode will not support `fi_cancel`. So, instead, close the endpoint without canceling the outstanding receives.
Versions of Libfabric before 1.22 will erroneously issue cancel events for ops that are posted to the endpoint when it is closed (see https://github.com/ofiwg/libfabric/pull/10139). For backward compatibility, ignore these events if we get them in the CQ.
This reverts commits 0f07c2e2f062e1d2e028b796902d0ce6069dda4d and f7003c42777d68f695e2b1e02b28b90ef866550b.
=> rdma: ignore cancel events instead of using `fi_cancel`.

.github/workflows/distcheck.yaml
(cherry picked from commit acceaa31b30e13089d2b742eff80b3964b4d75fc)
=> [v1.9.x-aws] ci: add another workaround for ancient al2 glibc

.github/workflows/distcheck.yaml
(cherry picked from commit 16eece68143c91c85b4cf1d5b34f818ad27a3b75)
=> (v1.9.x backport) .github/workflows: Remove EPEL from AL2 b/c it doesn't exist anymore

m4/check_pkg_libfabric.m4, src/nccl_ofi_ofiutils.c
For a bunch of reasons (detailed in the code), there's no upside to leaving shared memory enabled, and we really need it disabled for correctness when flush() is needed, so that the flush operation flows through the NIC.  Therefore try to disable shared memory whenever possible.
=> Disable Libfabric shared memory when possible

m4/check_pkg_libfabric.m4, src/nccl_ofi_ofiutils.c
For a bunch of reasons (detailed in the code), there's no upside to leaving shared memory enabled, and we really need it disabled for correctness when flush() is needed, so that the flush operation flows through the NIC.  Therefore try to disable shared memory whenever possible.
(cherry picked from commit 234d1a055d21a28ec14608d3accb18b963f1953c)
=> v1.10.x-aws cherry-pick: Disable Libfabric shared memory when possible

m4/check_pkg_libfabric.m4, src/nccl_ofi_ofiutils.c
For a bunch of reasons (detailed in the code), there's no upside to leaving shared memory enabled, and we really need it disabled for correctness when flush() is needed, so that the flush operation flows through the NIC.  Therefore try to disable shared memory whenever possible.
(cherry picked from commit 234d1a055d21a28ec14608d3accb18b963f1953c)
=> (v1.9.x backport) Disable Libfabric shared memory when possible

include/nccl_ofi_param.h
We decided not to include this patch in the 1.10 release. It did not have a significant perf impact on P5 platform.
This reverts commit 3cc3af2260f18bf9291fbb4f940a7b62ac905d7c.
=> [v1.10.x-aws] Revert "param: increase CQ read count to 16 for performance"

.ci/aws/Jenkinsfile
=> .ci/aws: Bump NCCL Version to v2.22.3-1

src/platform-aws.c
Check if `platform_data` is NULL before using
`platform_data->domain_per_thread`. This avoids a segfault when `platform_data` is NULL (on platforms without a `platform_data` entry)
=> platform-aws: handle NULL platform_data for domain_per_thread

.github/workflows/distcheck.yaml
Run unit tests in github actions, for cuda and neuron, with different compilers, using `make check` with the plugin compiled in debug mode.
=> .github/workflows: run unit tests

.github/workflows/distcheck.yaml
Backport of #419 
Use the EFA installer to get the Libfabric and MPI dependencies. Previously, we thought we only needed Libfabric, but to build the functional tests, we need MPI and it's better to build the functional tests.
Signed-off-by: Raghu Raja <raghunch@amazon.com>
(cherry picked from commit 858f44861ec73bb8d68ea7c91422edc21f4c22da)
=> [v1.9.x-aws] distcheck: Use efa-installer for dependencies

src/platform-aws.c
EFA now reports WRITE_IN_ORDER_ALIGNED_128_BYTES for this platform and the plugin no longer has to override this check to support the low-latency protocols. Removing the hack so the protocol support is determined programmatically for both the send/recv and RDMA protocols.
=> aws: Do not skip the WRITE_IN_ORDER_ALIGNED_128_BYTES check for P5

src/platform-aws.c
Backport of #509 
Check if `platform_data` is NULL before using
`platform_data->domain_per_thread`. This avoids a segfault when `platform_data` is NULL (on platforms without a `platform_data` entry)
(cherry picked from commit 45a7e10e2732e39651bb67f72bfff45d0d90b908)
=> [v1.10.x-aws] platform-aws: handle NULL platform_data for domain_per_thread

configure.ac, include/nccl_ofi_config_bottom.h, include/nccl_ofi_param.h, m4/check_enable_memfd_create.m4, src/nccl_ofi_net.c, src/nccl_ofi_ofiutils.c, src/nccl_ofi_rdma.c, src/platform-aws.c
Autogenerated topology files will be the default on the AWS P5 platform that uses RDMA protocol. Also uses anonymous mem-backed file for autogenerated topology file.
~~Needs testing to ensure behavior is correct in ML apps with `fork()` behavior.~~ done
=> Enable autogenerated topology file by default for RDMA protocol

src/platform-aws.c
P5e will use the same autogenerated topology file approach as P5.
=> platform-aws: configuration for P5e instances

.github/workflows/distcheck.yaml
Build only the oldest and newest efa installer versions
=> ci: build oldest working EFA installer and latest 

include/nccl_ofi_param.h
For most use cases of interest, the eager protocol hurts performance more than it helps on Neuron platforms.  So we set the default eager size to 0 by default when on Neuron, skipping the eager protocol.
We should make this platform specific rather than the large hammer to set default values from the platform file today, which is something that we should really fix.  But, as always, we're a little short on time, so this will do for now.
(cherry picked from commit bfc2e7c877f4eca2ca574cdf8c8662ede68e6e33)
=> (v1.9.x backport) neuron: Disable rdma eager messages by default

src/nccl_ofi_api.c
Since 4763d60, RDMA protocol does not support the old blocking connection establishment API. Issue an error message and fail, rather than hanging.
=> api: fail when using connect/accept_v4 with RDMA protocol

src/nccl_ofi_api.c
Backport of #529 
Since 4763d60, RDMA protocol does not support the old blocking connection establishment API. Issue an error message and fail, rather than hanging.
(cherry picked from commit a725e08a7b5523aaf9ce67992bfb5c7e0127ec3e)
=> [v1.11.x-aws] api: fail when using connect/accept_v4 with RDMA protocol

src/platform-aws.c
With switching to this plugin implementation, we want to take advantage of the RDMA protocol on trn1/trn1n platforms without setting environment variables.
This commit sets RDMA protocol as default for trn1/trn1n platforms.
=> platform: Set RDMA protocol as default for trn1/trn1n platforms

Makefile.am
This resets the file ownership to root in the dist tarballs
=> dist: set `TAR_OPTIONS` to remove ownership info

.ci/aws/Jenkinsfile
The trainium tests are unstable, and causing CI to fail frequently, slowing down plugin development.
This reverts commit 59bfaa40636eeb7cc84fed064cb8cfa04c05f2a1.
=> Revert ".ci/aws: Add trainium tests to CI"

configure.ac
Updating version number after release of v1.11.0-aws.
=> [v1.11.x-aws] update version number to v1.11.1a1-aws

src/nccl_ofi_interface_nvidia.c
Since the beginning of the project, the network name reported by the plugin has been "AWS Libfabric".  Which has a space in it, making people be careful about shell escaping for no real upside.  Change the default to Libfabric, but also still allow "AWS Libfabric" and also "OFI", by changing the name string during plugin load.
An alternative implementation is to do the name change during the plugin init call, as NCCL loads the plugin, calls init() on it, and only then does the string comparison.  I decided not to go that route with this patch because the init function is shared between Nvidia and Neuron stacks and since the init function doesn't take a pointer to the plugin structure, it would still have to update all available structures.  So it was slightly more work to deal with …
=> nvidia: Change default network name to "Libfabric"

src/nccl_ofi_net.c
nccl_net_ofi_plugin_init refers to the rdma pointer array, but this code is shared between rdma and sendrecv, so the error message should be generic.
=> Fix naming of array in nccl_net_ofi_plugin_init

include/nccl_ofi_param.h
This reverts commit 346be40c777c996932e9474d781dc6fb8dafbc56.
Revert commit since plans are to follow master branch on neuron platforms. Since benefit of increase has not been verified yet, revert change for now.
=> Revert "param: increase CQ read count to 16 for performance"

include/nccl_ofi_topo.h, src/nccl_ofi_topo.c
Before, plugin would group NICs around trainium device, or error our in case of accelerator is not a NVIDIA GPU or a trainium device. This patch is implemented by applying the following two changes:
The NIC grouping code for RDMA protocol groups NICs around
accelerators. To find the accelerators, the grouping code uses
hard-coded accelerator identifies. Supported hard-coded accelerators
are for NVIDIA GPUs and trainium devices.
In case of an unknown accelerator, the grouping code would fail and
error out.
This patch modifies the code such that each libfabric NIC is exposed
as one device to the user of the plugin in case of absense of known
accelerators around which a libfabric NIC can be grouped.
Since a TRN accelerator is composed of multiple cores, the number of
trainium accelerators …
=> Expose each libfabric NIC as one NIC device to the user in case of non-NVIDIA platforms

.github/workflows/cache_efa_installer.yaml
Once a day, download efa installer and store it in actions cache. Other actions can use this instead of downloading from network.
=> ci: cache efa installer

.github/workflows/cache_efa_installer.yaml
Unfortunately, this couldn't be tested without introducing the action to the repo in the master branch so that the action appeared in the UI.  It was implemented with a script issue. This fixes that script issue, and can be tested before merging now that the initial action was introduced to the repository.
https://github.com/aws/aws-ofi-nccl/actions/runs/10604329005
=> ci: fix efa installer caching

src/nccl_ofi_rdma.c
A later revision of PR #438 introduced a NULL ptr bug in the `endpoint_per_comm = 1` code. Since this option isn't enabled by default, we weren't testing it.
=> fix(rdma): endpont_per_comm: NULL ptr bug

src/tuner/nccl_ofi_tuner.c
Enable tuner initialization message to be displayed on all NCCL_DEBUG=INFO and display the logs as part of the default subsystem (INIT)
=> tuner: Enable tuner init msg on INFO logs

include/nccl-headers/neuron/error.h, include/nccl-headers/neuron/net.h, include/nccl_ofi.h, include/nccl_ofi_api.h, include/nccl_ofi_cuda.h, include/nccl_ofi_deque.h, include/nccl_ofi_ep_addr_list.h, include/nccl_ofi_freelist.h, include/nccl_ofi_idpool.h, include/nccl_ofi_log.h, include/nccl_ofi_math.h, include/nccl_ofi_memcheck.h, include/nccl_ofi_memcheck_asan.h, include/nccl_ofi_memcheck_nop.h, include/nccl_ofi_memcheck_valgrind.h, include/nccl_ofi_mr.h, include/nccl_ofi_msgbuff.h, include/nccl_ofi_ofiutils.h, include/nccl_ofi_param.h, include/nccl_ofi_platform.h, include/nccl_ofi_pthread.h, include/nccl_ofi_rdma.h, include/nccl_ofi_scheduler.h, include/nccl_ofi_sendrecv.h, include/nccl_ofi_topo.h
Stacked PRs:
* #578
* #568
* #567
* #566
* #577
* #576
* #574
* #575
* #572
* #571
* #570
* #573
* #569
* #565
* #564
* #563
* #560
* #558
* #557
* #556
* #555
* __->__#554
--- --- ---
the canonical token is __cplusplus not _cplusplus. When this is
incorrect, linkage fails as cxx will perform name mangling when
including these headers, resulting in a function with that mangle not
existing.
=> fix(tree): use correct __cplusplus guards

include/nccl_ofi_rdma.h, src/nccl_ofi_rdma.c
Rebased and reworked https://github.com/aws/aws-ofi-nccl/pull/321 on master.
The commits are largely the same with adaptations to recent changes around MR (with the addition of the cache) and fix for a bug that was causing an fi_av_insert() on the control QP's address to fail (as the conn message did not carry the correct address).
=> Separate endpoint for control messages

src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
Stacked PRs:
* #578
* #568
* #567
* #566
* #577
* #576
* #574
* #575
* #572
* #571
* #570
* #573
* #569
* #565
* #564
* #563
* #560
* #558
* #557
* #556
* __->__#555
--- --- ---
c++ requires literals not sit directly next to other literals and must
be separated by at least one whitespace token.
=> fix(tree): add spaces around PRIu64

include/nccl_ofi.h, include/nccl_ofi_config_bottom.h, include/nccl_ofi_freelist.h, include/nccl_ofi_memcheck.h, include/nccl_ofi_rdma.h, src/nccl_ofi_api.c, src/nccl_ofi_rdma.c
Stacked PRs:
* #578
* #568
* #567
* #566
* #577
* #576
* #574
* #575
* #572
* #571
* #570
* #573
* #569
* #565
* #564
* #563
* #560
* #558
* #557
* __->__#556
--- --- ---
static_assert is a c++ keyword, so when not using c++, create a macro
under the same name that aliases _Static_assert to static_assert. This
means static_assert can be used in both cases.
=> feat(tree): add static_assert shim macro

src/platform-aws.c
Stacked PRs:
* #578
* #582
* #568
* #567
* #566
* #577
* #576
* #574
* #575
* #572
* #571
* #570
* #573
* #569
* #565
* #564
* #563
* #560
* #558
* __->__#557
--- --- ---
When using designated initializer lists, under C++ only, a warning will
be emitted if the declaration order does not match the initialization
order if any fields are missing in the initializer list. Reorder these
structs to initialize all fields in their declaration order.
=> fix(aws): align declaration and init order

src/nccl_ofi_rdma.c
Stacked PRs:
* __->__#558
--- --- ---
void pointer arithmetic is illegal in c++; cast to uintptr, do the
offset, then cast to void* to pass to libfabric.
=> fix(rdma): fi_{send,write}data: do arithmetic on uintptr

.github/workflows/distcheck.yaml
Stacked PRs:
* #592
* #578
* #568
* #567
* #566
* #591
* #588
* #595
* #594
* #593
* #589
* #587
* #577
* #576
* #586
* #585
* #574
* #575
* #571
* #570
* #573
* #569
* #565
* #564
* #563
* #560
* __->__#582
--- --- ---
pull_request triggers remain unchanged/unfiltered.
=> chore(.github/workflows): constrain push triggers to known branches

m4/ax_check_enable_debug.m4
prefer dwarf debug symbols for usage with nsight, don't use -O0 as it prevents the proper usage of fortify-source, don't omit frame pointers.
=> feat(build): better --enable-debug defaults

include/nccl_ofi_freelist.h, include/nccl_ofi_memcheck.h
Stacked PRs:
* #592
* #578
* #568
* #567
* #566
* #591
* #588
* #595
* #594
* #593
* #589
* #587
* #577
* #576
* #586
* #585
* #574
* #575
* #571
* #570
* #573
* #569
* #565
* #564
* #563
* __->__#560
--- --- ---
=> fix(freelist): use uintptr_t for pointer arithmetic

src/nccl_ofi_rdma.c
This commit fixes a bug introduced by commit 64d8baf "rdma: Move control messages to own endpoint".
The domain member of the plugin RDMA device struct is not available for free disposal. It only stores an actual domain in case only one domain is created per device, i.e., when the domain-per-thread feature is disabled. In this case, the domain is copied over from the device object into the plugin RDMA endpoint object. Afterwards, only the domain member of the endpoint should be accessed. Reason is that the device object does not provide an domain in case domain-per-thread feature is disabled.
However, said commit above accesses domain member of device object in any case. This commit fixes this bug by accessing the domain member of the endpoint instead.
*Description …
=> Fix: access domain from ep during mr on device

src/platform-aws.c
In order to use the RDMA protocol on TRN1, users need to issue a reboot of their instance. If a reboot is not issued, the plugin will fail to initialize. Therefore, we want to set the default protocol to SEND RECEIVE so that users can use this plugin out of the box without having to reboot their instance.
- Set default protocol on TRN1 platform to be send receive
=> platform: trn1 default protocol send receive

include/nccl_ofi_config_bottom.h
```
fix(tree): import libfabric's container_of macro
Newer versions of libfabric are no longer defining this in
"rdma/fabric.h", but we were relying on it transiently. Bring it in-tree
to unblock compilation against libfabric master.
```
=> fix(tree): import libfabric's container_of macro

m4/check_pkg_valgrind.m4
AC_LANG_PROGRAM creates main for you, so putting `int main(void) {}` inside of another `int main(void){}` can fail the check due to warnings, even when the header is available.
=> fix(valgrind): fix autotools mistake

.github/workflows/distcheck.yaml
Downgrades clang and drops the use of cache-apt-pkgs. All actions still complete in about five minutes without caching.
=> CI updates

src/nccl_ofi_ofiutils.c
fi_endpoint(3) states that fi_setopt/_getopt calls return FI_ENOPROTOOPT when a provider does not support a requested option. Certain setopt options also return FI_EOPNOTSUPP if a particular mode forced by setting an option is not supported (such as, with FI_OPT_CUDA_API_PERMITTED being set to false when a provider requires CUDA API to support FI_HMEM_CUDA). Checking for both as we have the same error outcome in either case.
Fixes #606
=> util: Use FI_ENOPROTOOPT to check for a provider's support for option

include/nccl_ofi_log.h, src/nccl_ofi_api.c, src/nccl_ofi_idpool.c, src/nccl_ofi_mr.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c, src/platform-aws.c, src/tuner/nccl_ofi_tuner.c, tests/functional/nccl_message_transfer.c, tests/functional/test-common.h, tests/unit/freelist.c, tests/unit/scheduler.c
GCC is willing to enforce printf-style format checks if the typedef for the log function pointer is tagged with the appropriate attribute. Clang behaves oddly, only generating warnings in the tests.  Which is weird, but at least get warnings for GCC is a huge win.
With printf warning checks, we find many issues that are also fixed in this patch.
=> Fix log format string behavior

include/nccl_ofi.h, include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
Change the protocol selection logic when the platform file does not specify a protocol.  Instead of always defaulting to sendrecv if the user / platform file didn't specify a protocol, try to figure out when rdma is a good default.  We still are conservative with enabling the rdma protocol, to avoid changing the default in as many places as posible.
With the change, the protocol selection order is:
1. if the user set NCCL_OFI_PROTOCOL, use that.
2. if the platform init set nccl_ofi_selected_protocol, use that.
3. If the rdma protocol reports multiple nics per device and initialized successfully, use that.
4. If the sendrecv protocol initialized successfully, use that.
5. If the rdma protocol initialized successfully, use that.
By submitting this pull request, I confirm that my …
=> Improve protocol selection logic

.ci/aws/Jenkinsfile
Nightlies show that the trn1n tests are stable with neuron 2.20 release.
=> .ci/aws: re-Add trainium tests to CI

m4/check_var_redzone.m4
We were mistakenly adding redzones to our freelist entries in release builds due to an incorrect check for enabled memory checkers.
=> fix(m4): set redzone size to 0

configure.ac, include/nccl_ofi.h, include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, src/Makefile.am, src/nccl_ofi_compat.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
Previous to this patch, endpoints were never freed, but just had most resources released when the ref count reached zero.  This was because the use of pthread thread specific data store meant that only the thread that created the ep could remove it from the thread specific data store.  Since we couldn't guarantee that, we never actually removed data from the store.
This patch switches from pthread thread specific storage to using a hash table indexed by the thread id.  Note that we use gettid() instead of pthread_self(), because pthread_t is a opaque structure that is not comparable and so can't really be used as a hash key.  If we want to support OSes other than Linux, then we can add more ways to get the unique thread id.
By submitting this pull request, I confirm that my contribution …
=> Fully destroy endpoints when refcount is 0

src/nccl_ofi_rdma.c
FI_ORDER_NONE (defined as 0) is deprecated. Prefer to just leave it unset to avoid deprecation warnings when building against newer libfabric. This should be zeroed out when hints are constructed, anyway, so this buys us compatibility with libfabric-git without any change in behavior.
=> fix(rdma): stop setting FI_ORDER_NONE

src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c, src/nccl_ofi_topo.c
Stacked PRs:
* #624
* __->__#594
--- --- ---
prefer `struct foo bar = {}' to `struct foo bar = { 0 }' to avoid
-Wmissing-field-initializers warnings.
=> fix(tree): use empty brace initializers for zero-initialization

configure.ac
> Linking against pthread and adding the compiler/linker/preprocessor option for
> pthreads are different things when using a modern libc. Without the
> compiler/preprocessor options, various builtin `#define`s are not set. Notably,
> this should change the behavior around errno in a multithreaded context within
> glibc; _REENTRANT will now be defined and errno is now thread-local.
> 
> See 4e45dd8a for an example of a bug that this would have prevented.
See also:
+ Background: https://developers.redhat.com/articles/2021/12/17/why-glibc-234-removed-libpthread
+ 4e45dd8a for a bug that this would have caught.
+ Why in both CFLAGS and CPPFLAGS? https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-pthread
+ Why in LDFLAGS? …
=> fix(build): ensure -pthread is passed

configure.ac
``` text
Automake manual:
> This is required if any libraries are built in the package. See
> Particular Program Checks in The Autoconf Manual.
add this for correctness.
```
Ranlib is already being used, but this just adds the automake hook to ensure
that it can be resolved..
By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.
=> fix(build): add missing AC_PROG_RANLIB

src/nccl_ofi_rdma.c
Stacked PRs:
* #568
* #567
* #566
* #591
* #588
* #595
* #594
* #593
* #589
* #587
* #577
* #576
* __->__#586
* #585
* #574
* #575
* #571
* #570
* #573
* #569
* #565
* #563
--- --- ---
=> fix(rdma): avoid enum/integral comparison

include/nccl_ofi_param.h
Stacked PRs:
* #568
* #567
* #566
* #591
* #588
* #595
* #594
* #593
* #589
* #587
* #577
* #576
* #586
* #585
* #574
* #575
* #571
* __->__#570
* #573
* #569
* #565
* #563
--- --- ---
=> feat(param): add uint parameter macro

src/nccl_ofi_rdma.c
Stacked PRs:
* #568
* #567
* #566
* #591
* #588
* #595
* #594
* #593
* #589
* #587
* #577
* #576
* #586
* #585
* __->__#574
* #575
* #571
* #570
* #573
* #569
* #565
* #563
--- --- ---
Previously, this used ~0 as the invalid signal. This defaults to a
signed type, which breaks under -wsign-compare. Prefer to use
COMM_ID_MASK as the marker.
=> fix(rdma): use COMM_ID_MASK as invalid id

src/tuner/nccl_ofi_tuner.c
Stacked PRs:
* #568
* #567
* #566
* #591
* #588
* #595
* #594
* #593
* #589
* #587
* #577
* #576
* #586
* #585
* #574
* #575
* #571
* #570
* #573
* __->__#569
* #565
* #563
--- --- ---
=> fix(tuner): avoid gotos

include/nccl_ofi_math.h, src/nccl_ofi_cuda.c, src/tuner/nccl_ofi_tuner.c
Stacked PRs:
* #568
* #567
* #566
* #591
* #588
* #595
* #594
* #593
* #589
* #587
* #577
* #576
* #586
* #585
* #574
* #575
* #571
* #570
* #573
* #569
* __->__#565
* #563
--- --- ---
=> fix(tree): use decltype instead of typeof for cxx

include/nccl_ofi_param.h, src/tuner/nccl_ofi_tuner.c
Stacked PRs:
* #568
* #567
* #566
* #591
* #588
* #595
* #594
* #593
* #589
* #587
* #577
* #576
* #586
* #585
* #574
* #575
* #571
* #570
* __->__#573
* #569
* #565
* #563
--- --- ---
cpp requires explicit cast to double here.
=> fix(tuner): fix implicit conversions

src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
Stacked PRs:
* #568
* #567
* #566
* #591
* #588
* #595
* #594
* #593
* #589
* #587
* #577
* #576
* #586
* __->__#585
* #574
* #575
* #571
* #570
* #573
* #569
* #565
* #563
--- --- ---
=> fix(tree): add fallthrough switch markers

src/nccl_ofi_sendrecv.c
Stacked PRs:
* #568
* #567
* #566
* #591
* #588
* #595
* #594
* #593
* #589
* #587
* #577
* __->__#576
* #586
* #585
* #574
* #575
* #571
* #570
* #573
* #569
* #565
* #563
--- --- ---
=> fix(sendrecv): add missing nccl-headers include

src/nccl_ofi_interface_neuron.c, tests/functional/nccl_message_transfer.c, tests/unit/ep_addr_list.c, tests/unit/freelist.c, tests/unit/idpool.c, tests/unit/scheduler.c
Stacked PRs:
* #568
* #567
* #566
* #591
* #588
* #595
* #594
* #593
* #589
* #587
* __->__#577
* #576
* #586
* #585
* #574
* #575
* #571
* #570
* #573
* #569
* #565
* #563
--- --- ---
const variables have internal linkage by default under c++; nvidia
interface requires it not be const because its modified during init.
Remove const for neuron, too.
=> fix(neuron): remove const from ncclNetPlugin_v{4,5} syms

src/platform-aws.c
Stacked PRs:
* #568
* #567
* #566
* #591
* #588
* __->__#595
* #594
* #593
* #589
* #587
* #577
* #576
* #586
* #585
* #574
* #575
* #571
* #570
* #573
* #569
* #565
* #563
--- --- ---
commit ce214aa rearranged fields such that the written initializers were
valid on most modern compilers, but it went unnoticed that this is
insufficient for AL2's ancient toolchain, which fails with:
> sorry, unimplemented: non-trivial designated initializers not supported
provide all members for all entries to fix this.
=> fix(platform-aws): fill all platform values

.github/workflows/distcheck.yaml
Pulls have been occasionally failing distcheck jobs since 83f563cf moved
these jobs from codebuild "self-hosted" runners to just run atop the gha
standard runners with docker. Try using ECR instead in the hopes that we
are not rate limited there.
Example failure: https://github.com/aws-nslick/nccl-net-ofi/actions/runs/11063619034/job/30740033833#step:2:26
=> fix(ci): prefer ecr to dockerhub

configure.ac
Stacked PRs:
* #568
* #567
* #566
* #591
* #588
* #595
* #594
* #593
* __->__#589
* #587
* #577
* #576
* #586
* #585
* #574
* #575
* #571
* #570
* #573
* #569
* #565
* #563
--- --- ---
Yet another autotools fix: If any warning/devel CFLAGS would invoke
warnings in headers used to detect dependencies, those dependencies will
fail with a highly misleading/confusing error message:
> configure: Found .git directory.  Adding -Werror to CFLAGS.
> checking if running on EC2 instance... yes
> checking if want AWS platform optimizations... yes
> checking for Libfabric 1.18.0 or later... no
> configure: error: On AWS platforms, Libfabric 1.18.0 or later is required
ie: it is not that Libfabric 1.18 was not found, it was that its headers
produced warnings. Fix this by resolving all dependencies …
=> fix(build): check features before mangling CFLAGS

configure.ac
Stacked PRs:
* __->__#624
* #594
--- --- ---
Tell the compiler to treat symbols marked explicitly as
NCCL_OFI_EXPORT_SYMBOL as preemptible, but not others. This gives the
compiler the freedom to assume that no external LD_PRELOAD'd library can
inject itself as an implementation of any given function in the library,
which means the compiler has the freedom to optimize across function.
=> feat(build): disable semantic interposition

src/nccl_ofi_net.c
159bfed1 introduced changes to the way that initialization and protocol
selection works. This commit corrects some duplicated print statements
that refer to rdma when they meant to refer to sendrecv protocol, and
also ensures that the branch for doing first-stage sendrecv
initialization is taken in the case that RDMA initialization fails for
any reason, such that it can be used as a fallback. Also ensure that if
either the selected protocol string or the plugin is null, that
initialization is aborted rather than segfaulting.
=> fix(init): fix sendrecv fallback logic

configure.ac, include/nccl_ofi.h, include/nccl_ofi_config_bottom.h, include/nccl_ofi_idpool.h, include/nccl_ofi_math.h, include/nccl_ofi_param.h, include/tracing_impl/nvtx.h, src/nccl_ofi_api.c, src/nccl_ofi_ep_addr_list.c, src/nccl_ofi_idpool.c, src/nccl_ofi_interface_neuron.c, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_scheduler.c, src/nccl_ofi_sendrecv.c, src/nccl_ofi_topo.c, src/platform-aws.c, src/tuner/nccl_ofi_regions.c, src/tuner/nccl_ofi_tuner.c, tests/functional/nccl_message_transfer.c, tests/unit/ep_addr_list.c, tests/unit/freelist.c, tests/unit/idpool.c, tests/unit/scheduler.c
CI is moving too slowly, and rebasing triggers too many rebuilds, to continue to use stacked PRs. This is a single PR that is combining all of the following PRS: 
* b45d7e8c  (#588) (approved, marked as merged)
* 07801496  (#589) (initially unapproved, changes made as requested, approved and marked as merged)
* 247e96a9  (#595) (approved, marked as merged)
* f50eecd1  (#593) (approved, marked as merged)                  
* 2b2e91e9  (#587) (approved, marked as merged)     
* 441e1e8a  (#577) (approved, marked as merged)           
* 1040fef1  (#576) (approved, marked as merged)  
* 5faa97dc  (#586) (approved, marked as merged)  
* 1ecfffbc  (#574) (approved, marked as merged)  
* 8cb419b7  (#570) (approved, marked as merged)                 
* ab14b170  (#573) (approved, marked as merged) …
=> Combined -Wextra -Werror Commits

src/platform-aws.c
Platform TRN2N requires platform settings, e.g., to enable RDMA protocol which is not the default for cases when plugin is used with one rail.
=> Add platform data settings for TRN2N

include/nccl_ofi_rdma.h, src/nccl_ofi_rdma.c
We hit a bug where the sender sends a long run of eager messages and
ends up outpacing the receiver by more than the width of the message
buffer, causing an error.
In this patch, receiver will send a control message to sender at least
every `msgbuff_size - max_requests` messages, and sender will pause if
it hasn't received a control message within this duration.
=> fix(rdma): send periodic control messages to sync sender/receiver

configure.ac, m4/ax_check_compile_flag.m4, src/nccl_ofi_ofiutils.c, src/nccl_ofi_sendrecv.c, src/platform-aws.c
Fix GCC static analyzer warnings, then enable -fanalyzer in our distcheck builds.
```
* 5995ec0e origin/fanalyzer-fixes feat(build): add -fanalyzer when --enable-werror
| 
| Steal ax_check_compile_flag from autoconf archive, then use it to check
| if we're building with a compiler that accepts -fanalyzer. If so, enable
| it when --enable-werror is active.
| 
| 
|  configure.ac                |  7 +++++-
|  m4/ax_check_compile_flag.m4 | 53 +++++++++++++++++++++++++++++++++++++++++++
|  2 files changed, 59 insertions(+), 1 deletion(-)
|
* b13cd735 fix: sendrecv/listen: silence leak warning.
| 
| gcc14 incorrectly flagged this as a leak as it was unable to reason
| about the way that we are storing into a listen_comm_t, but have
| allocated a sendrecv_listen_comm_t. …
```
=> feat(build): add -fanalyzer when --enable-werror

include/nccl_ofi_param.h, include/nccl_ofi_scheduler.h, src/nccl_ofi_rdma.c, src/nccl_ofi_scheduler.c, tests/unit/scheduler.c
This change modifies the current scheduling policy such that we either round-robin on each rail or a pair of rails or a triplet of rails or a quadruplet of rails based on the min_stripe_size. Within the group of rails the message is divided by the stripe_size and multiplexed on each rail.
The num_stripes to be multiplexed is calculated using the below formula,
num_stripes = min ( ceil ( msg_size / min_stripe_size ) , num_rails )
=> Add Multiplexed-round-robin scheduler

include/nccl_ofi_param.h
This reverts commit bfc2e7c877f4eca2ca574cdf8c8662ede68e6e33.
Eager gets re-enabled on neuron platforms, i.e., commit above is reverted, since current neuron features benefit from sending data eagerly due to missing pre-posting feature.
=> Revert "neuron: Disable rdma eager messages by default"

.ci/aws/Jenkinsfile
Previously, the p3dn AL2 ami building was broken, so we pinned it to a fixed AMI that happened to not have the EFA Installer in it. Now that the p3dn AMI building is fixed, make the CI use AMI's with EFA Installers already baked into them. This will speed up our CI, and will reduce the amount of infra related errors that we see.
=> .ci/aws: All CI use ami with EFA Installer

.github/workflows/distcheck.yaml
Allow manually triggering the distcheck build matrix on a specific branch. This is mostly useful on our forks, where it's possible through the "actions" tab to select the PR-CI job and submit a run request against your branch, without requiring creating a draft PR that sends clogs emails and spawns jenkins ci jobs.
=> feat(ci): add workflow_dispatch to distcheck

include/nccl_ofi_rdma.h, src/nccl_ofi_rdma.c
Commit 840769e8 moved the device lock from the rdma/sendrecv classes to the base device class.  Somehow, I missed removing the device lock field from the rdma device and missed updating one use.  This commit fixes both of those problems.
=> Fix use of uninitialized lock

include/nccl_ofi.h, include/nccl_ofi_rdma.h, src/nccl_ofi_rdma.c
This changes flush() implementation in such a way that local RDMA read is requested to all NIC rails for multi-rail cases. This is to make sure all data traffic paths are safely flushed from all NICs to GPU.
=> rdma: do local RDMA read on all NIC rails for flush()

include/nccl_ofi.h, include/nccl_ofi_platform.h, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c, src/platform-aws.c
Posting a couple patches that I've had in a branch trying to clean up domain / threading logic.  Add some accessor functions for looking up one object type from another.  Also move the domain_per_thread field into the plugin, trying to remove the number of unnecessary global variables.
=> Couple of accessor function / code cleanups

include/nccl_ofi_rdma.h, src/nccl_ofi_rdma.c
Eliminating the waits for eager messages can cause the sender and
receiver to go out-of-sync during a long run of eager messages. For
example, at an extreme, the sender could send 1024 eager messages, which
are queued by Libfabric and marked complete. Then if the sender received
a control message for message 0 from the receiver, it couldn't be
unambiguously associated with the first message or the 1024th message,
which both have the same sequence number, since the sequence number is
only 10 bits.
A patch intended to keep them in sync (2479540) also did not resolve the
issue. Without `FI_ORDER_SAS` semantics (which the plugin does not
request), the completions can be reordered, and the receipt of of sync
ctrl message does not guarantee that previous ctrl messages have
completed, which can …
=> rdma: Revert commits eliminating eager waits

include/nccl_ofi.h, include/nccl_ofi_idpool.h, include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
Pull out the cleanup patches from https://github.com/aws/aws-ofi-nccl/pull/665.  I'm not convinced that 665 is a real failure, but want something simple enough we can get some CI confidence.
=> Cleanups from adding a domain interface

include/nccl_ofi_param.h, src/nccl_ofi_scheduler.c, tests/unit/scheduler.c
Currently we  use 3 stripes for the below case:
(3*stripe_size) < payload size < (4*stripe_size)
After this commit we enforce the num_stripes always rounds down to the nearest lower power of 2.
We also set the default stripe size to be 128K instead of 64K since we see the most optimal results during testing.
=> fix: Change multiplexer scheduler to use two rails instead of three

include/nccl_ofi_param.h, src/Makefile.am, src/nccl_ofi_param.c, src/nccl_ofi_sendrecv.c
In preparation for moving to C++, make sure we're closer to following the [One Definition Rule](https://en.wikipedia.org/wiki/One_Definition_Rule).  There was one major offender, duplicate symbol names between the sendrecv and rdma transports.  While we still need to clean up the naming in the rdma transport, this PR prefixes every private symbol in the sendrecv transport with `sendrecv_`.
The other potential badness was the param code, if the compiler did not inline those functions.  To work around that, we do some ugly hacking to put all the param access functions in a single `nccl_ofi_param.c` file, and `nccl_ofi_param.h` only creates declarations most of the time.  The implementation is ugly, but we want to rewrite this code anyway, so let's limp until we're using C++ and can write …
=> Fix a number of duplicate definition names

include/nccl_ofi_platform.h, src/nccl_ofi_rdma.c, src/nccl_ofi_topo.c, src/platform-aws.c
The device sorting code in the aws platform code for mrail groups  would cause NCCL to abort / run slowly because the sorting happened too late in the code, and the leader nic in the generated topology file didn't match the new leader after sorting, which is the one returned in getProperties.  This patch pulls the sorting logic up into the topology grouping logic so that we avoid that bug, and also cleans up some other issues found while auditing that code.
=> Fix device sorting on aws platforms

include/nccl_ofi_param.h, include/nccl_ofi_rdma.h, src/nccl_ofi_rdma.c
PR #543 has moved the control message to its own dedicated
endpoint on a single rail. As a result, the control message is not sent on
all rails in a round-robin fashion anymore. This has impacted performance
in some cases, so we want the option to still distribute the control messages
across all rails.
This PR is providing an environment variable to choose between a) using a
single dedicated endpoint for control messages, sharing the CQ with the data
endpoint on rail 0; or b) use as many additional endpoints for the control
messages as the number of rails, sharing the CQs with the data endpoints, and
use the scheduler to round robin the control messages across all rails.
=> rdma: add option to round robin the ctrl msg, and use shared CQs for control and data endpoints

src/nccl_ofi_net.c, src/platform-aws.c
Switch printing information about global registration scope, DMA-BUF support, and ordering from INFO to TRACE, as they happen for every endpoint created, and with the endpoint per communicator code, this results in hundreds of prints, even for a 32 GPU job.
Add a startup time print for the global registration and dma-buf state, since those may prove useful.
For a 4 node allreduce test, this reduces the output from 4062 lines to 2974 lines, a reduction of 26%, and was inspired by having to parse through files from our 16 node runs, where it's basically all endpoint properties prints.
=> Reduce repetitive INFO printing

m4/check_pkg_cuda.m4
```
595ec88d cuda: add stubs/ to search path
b0d7e8a2 cuda: support dynamically linking libcudart
```
```
1 file changed, 14 insertions(+), 2 deletions(-)
m4/check_pkg_cuda.m4 | 16 ++++++++++++++--
modified   m4/check_pkg_cuda.m4
@@ -15,6 +15,17 @@ AC_DEFUN([CHECK_PKG_CUDA], [
AC_ARG_WITH([cuda],
[AS_HELP_STRING([--with-cuda=PATH], [Path to non-standard CUDA installation])])
+  AC_ARG_ENABLE([cudart-dynamic],
+    [AS_HELP_STRING([--enable-cudart-dynamic],
+                    [link cudart dynamically (default=link statically)])],
+    [],
+    [enable_cudart_static=no])
+
+  cudartlib="-lcudart_static"
+  if test "x${enable_cudart_static}" != "xyes"; then
+     cudartlib="-lcudart"
+  fi
+
AS_IF([test -n "${with_cuda}"], [NCCL_NET_OFI_DISTCHCK_CONFIGURE_FLAGS="$NCCL_NET_OFI_DISTCHCK_CONFI …
```
=> cuda: build flag for dynamically or statically linking cudart

src/platform-aws.c
Platform TRN2 requires platform settings, e.g., to enable RDMA protocol which is not the default for cases when plugin is used with one rail.
=> Add platform data settings for TRN2

.ci/aws/Jenkinsfile
Signed-off-by: Sai Sunku <sunkusa@amazon.com>
(cherry picked from commit 8a0686f79a7c81cfbcc84d5ab0b3415164735843)
=> [v1.12.x] .ci/aws: Switch CI to persistent clusters with containers

include/nccl_ofi_param.h
This commit disables dmabuf by default. Due to the current libfabric
release cadence around the 2.x release, libfabric@8708b5c is not
contained on any current libfabric upstream release. For EFA users atop
efa-installer 1.35 (libfabric 1.22), this would mean that if we make a
1.13.x release, we would be putting the default EFA user onto the
problematic dual gdr+dmabuf MR flow.
No perf or correctness issues have been seen with the dmabuf flow, and
this should be reverted as soon as libfabric makes a release or
efa-installer cherry-picks the fix.
=> defaults: make dmabuf opt-in

src/nccl_ofi_rdma.c
In the endpoint per communicator path, we keep shared CQs in the device to be used by all endpoints, so we don't want to release the CQ when we release an endpoint. This is fixing a bug that was causing the CQ to be released in `ep_rail_release` by mistake, that resulted in a segfault when the CQ was used again.
=> fix: ep release in endpoint per comm

include/nccl_ofi_param.h, src/nccl_ofi_rdma.c
Set a priority traffic class (LOW_LATENCY) for the control queue pair. Providers should silently fall back to TC_UNSPEC in the case that LOW_LATENCY is not available, so there's no fallback in this code. The traffic class interface was added in Libfabric 1.9.0 and configure requires at least Libfabric 1.11.0, so there's no need to add backward compatibility #ifdefs.
=> rdma: Set LOW_LATENCY traffic class for control

include/nccl_ofi_param.h
#695 disabled dmabuf by default to work around libfabric release scheduling. This reverts that commit.
=> reenable dmabuf by default

include/nccl_ofi_log.h, include/nccl_ofi_mr.h, src/nccl_ofi_mr.c, src/nccl_ofi_net.c, tests/functional/nccl_message_transfer.c, tests/unit/mr.c
When a user registers multiple small buffers within same system page, current logic of MR cache results in only the first buffer registered, and the registered handle of the first buffer is returned for all other small buffers registrations.
Later when the handle is used for send / recv operations of actually unregistered small buffer regions, EFA device
returns errors regarding invalid local key. 
The changes include:
- Register iovec memory regions aligned to system page size, by using aligned base and bound when creating mr keys.
- Make cache->system_page_size min of reported system page size and cache page size.
- Add unit test for new mr key creation behavior.
- Adjust message transfer test to trigger the error case.
By submitting this pull request, I confirm that my contribution is …
=> MR: Enforce page-aligned buffer registration for iovec and add corresponding test case

src/tuner/nccl_ofi_regions.c, tests/unit/show_tuner_decisions.c
This patch has the below changes for the region based tuner for p5en
- Enable region based tuner for P5en.
- add vertices for region based tuner for all_reduce bitmask 0x0 and 0x7.
- add vertices for region based tuner for all_gather bitmask 0x7.
- add vertices for region based tuner for reduce_scatter bitmask 0x7.
=> feat: Region-based tuner support for P5en

src/tuner/nccl_ofi_regions.c
Since PAT is not supported on NCCL 2.21.5-1,
in this case fallback to NCCL internal tuner.
Change the tuner v2 api to fallback to internal tuner in case the ALGO is PAT
=> fix: Fallback to internal tuner on NCCL-2.21.5 for PAT

.github/workflows/distcheck.yaml, m4/ax_platform_aws.m4, src/nccl_ofi_net.c, src/nccl_ofi_ofiutils.c
p5en bring-up has exposed a set of interconnected bugs across libfabric
and the plugin to the point that it's become difficult to reason about
how fixes apply retroactively to older libfabric releases. Bump the
required version to 1.22 when building with platform-aws for our 1.13.x
series to enforce that users aren't running a mixture of versions that
developers haven't tested.
=> platform-aws: bump libfabric requirement to 1.22

src/nccl_ofi_cuda.c
This was missed in review. It doesn't work this way. In C++20, the following is legal:
```cpp
enum foo { bar, baz };
using enum foo;
```
But it does not support the glob syntax done here, and this is also missing the `enum` specifier required, and it also doesn't work with C++17. It's unnecessary in this file, anyway, we can just use the bare names here. Delete it so that this file can be parsed with `-x c++` without causing build failures.
=> fix(cuda): delete broken using directives

include/nccl_ofi.h, include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
Add a domain object to the transport interface, to reflect the need for fi_domain (and the related MR cache / rkey pool) to either be a single domain per process or a domain per initializing thread, depending on platform.  Previously, this was kind of hacked into the code, with extra fi_domain pointers in various structs.  Cut a bunch of that out, and move a bunch of the logic into one place, so that the two protocols behave the same.
=> Add domain object to transports

.gitignore
Add the recently added tuner region unit test binary to the list of files that git should ignore.
=> Add tuner region unit test to gitignore

include/nccl_ofi_tracepoint.h, include/tracing_impl/lttng.h, include/tracing_impl/nvtx.h, src/nccl_ofi_rdma.c
This PR adds:
- a separate lttng tracepoint for eager send instead of using the same one used for write
- an lttng tracepoint for the eager send completion
- tracepoints for ctrl send and its completion event
Plus it adds as parameters the device to the event for recv completion of ctrl message and the sequence number for recv completion event of a write message.
=> lttng: tracepoints for eager and ctrl messages

include/tracing_impl/nvtx.h
Event was previously associated with NULL domain, hindering ability to match with parent recv request
(cherry picked from commit a1c9db98b6b94cbecd8e95d2647815676f8ed111)
=> [v1.13.x-aws] nvtx: associate eager recv with NVTX domain

src/tuner/nccl_ofi_regions.c
Adding the tuner regions for All Gather 0x0 and Reduce Scatter 0x0 These regions were removed from the region based tuner because of the bug in the polygon extend logic. After the bug is fixed, adding back the regions for AG0x0 and RS0x0.
=> fix : Add regions for AG 0x0 and RS 0x0 for P5en

src/tuner/nccl_ofi_regions.c
Currently the Ring-LL region for AG0x0 and RS0x0 starts with the point {0, 16} and extends till {TUNER_MAX_SIZE, TUNER_MAX_RANKS}. But the polygon was not completely closed without a point on the y-axis. Added a points {0, TUNER_MAX_RANKS}. This ensures the polygon is closed correctly.
*Testing*
Tested that the tuner is making the correct decisions by running unit tests show_tuner_decisions with AG0x0 and RS0x0 
=> fix : Converge the Ring-LL region at TUNER_MAX_RANKS

include/nccl_ofi_rdma.h, src/nccl_ofi_rdma.c
The LL128 protocol causes an interesting pattern where there's a long string of large-ish messages and then a "leftover", most notable on power of 2 message sizes like are used in benchmarks. If that leftover bit is eager sized, you end up with an eager message queued behind a bunch of writes, which doesn't gain you anything in latency hiding the receive request, but then costs you the fixup on the remote side.
This patch implements an overly simplistic version of runting, which skips eager if there is already a write outstanding on the communicator.  This is wrong for a couple reasons.  First, we should probably use a BDP or similar to determine how much data should be in flight before we skip the eager protocol. Second, we should really decrement the counter on cqe processing time, but …
=> rdma: Skip eager protocol when writes outstanding

include/nccl_ofi_param.h
This reverts commit 224593f119a62f614106eac6718e2e1769f21b29.
Our shared development cluster seems to have issues with dmabuf when
running NCCL tests, for a handful of niche situations, ie: two nodes,
with MPI_Comm_split equal to the number of GPUs, at 16GB+. Other
environments seem not to have issues with the same workload, but out of
an abundance of caution and due to a lack of root cause, this is being
reverted again.
=> Reapply "defaults: make dmabuf opt-in"

.github/workflows/distcheck.yaml, configure.ac, include/nccl_ofi_config_bottom.h, include/nccl_ofi_mr.h, include/nccl_ofi_rdma.h, include/tracing_impl/nvtx.h, m4/check_pkg_mpi.m4, tests/functional/Makefile.am, tests/unit/scheduler.c
> feat(build): Add full C++ build mode
> 
> Rather than relying on -Wc++-compat, add a full build flag that uses all
CXXFLAGS and parses the source truly as C++.
=> add `--enable-cpp` build flag

src/tuner/nccl_ofi_regions.c
Extend the region of PAT-SIMPLE to be used on smaller message size, since that gives better performance on P5en.
=> fix : Extend PAT-SIMPLE to small message sizes

contrib/debian-template/rules
efa-config is necessary to populate ldconfig cache for libfabric, rather than libfabric specifying this itself. This means its insufficient for aws-ofi-nccl to simply depend on libfabric, because pulling in libfabric as a build dependency doesn't pull in efa-config, which is necessary to actually resolve the library. Add a gross hack that runs the entire build with LD_LIBRARY_PATH set. It's an understatement to say that this is not ideal.
=> packaging: add a hack for efa-config/libfabric

contrib/fedora/aws-ofi-nccl.spec
add libcudart.so to `__requires_exclude` by default by either appending to the
existing value or setting it if unset. Dependency tracking is still possible if
enable_cudart_dep_tracking is defined externally.
=> packaging/rpm: default-disable cudart dep tracking

include/nccl_ofi_freelist.h, include/nccl_ofi_rdma.h, include/nccl_ofi_scheduler.h, include/nccl_ofi_sendrecv.h, src/nccl_ofi_freelist.c, src/nccl_ofi_rdma.c, src/nccl_ofi_scheduler.c, src/nccl_ofi_sendrecv.c, tests/unit/freelist.c
Updates the interface of freelist to return an elem struct that contains
a buffer pointer and (optionally) memory registration info. Also updates
sendrecv, rdma, and scheduler codes to use the new interface.
This separation paves the way for storing freelist user data in GPU
memory.
=> freelist: separate out metadata from user data

contrib/debian-template/rules
there is a chain of unfortunate hacks on top of unfortunate hacks that result in the potential for broken packages to be generated.
1. the EFA installer pipeline does not use pbuilder/cowbuilder/etc to build each package in a chroot with only its stated dependencies. Instead, a single AMI is booted once and all packages are built in the same AMI lifetime. LTTNG apparently existed in this environment, for whatever reason.
2. Rather than explicit configuration ala cmake, we use autotools where it's idiomatic to enable features if software is available in the system path, and otherwise disables it. We did not explicitly state these options before when building packages.
3. due to libfabric-aws not shipping a symvers/symbols file, and also due to the fact that builds atop EFA installer need …
=> fix: packaging/deb: explicitly disable optionals

.gitignore, include/Makefile.am, include/platform-aws.h, src/platform-aws.c, tests/unit/Makefile.am, tests/unit/aws_platform_mapper.c
This was originally just a patch to add unit tests for the regex handling, but also tagged on a commit to change the p5 match to match all p5 or later platforms, because it's a reasonable example.  Ended up splitting the name into a name and regex, otherwise every time you changed the regex (like the p5 extension), you had to update the unit test, and that was just annoying. Especially during the inevitable messing up regex cycle.
=> aws: Improve platform lookup handling

.ci/aws/Jenkinsfile
This PR does the following:
* Decreases timeout from 24h to 8h, which will allow 8 jobs started at the same time to all pass (no impact now that jobs take 1 hour)
* Increase the amount of history retained from 90d to 360d
=> .ci/aws: Jenkinsfile updates

include/nccl_ofi_msgbuff.h, include/nccl_ofi_param.h, include/nccl_ofi_rdma.h, src/nccl_ofi_rdma.c
Bounce buffers are used to receive both eager messages and ctrl messages -- in the latter case, the name "bounce buffer" doesn't make sense. Thus, rename to the more generic "rx_buff".
=> rdma: rename bounce to rx_buff

src/nccl_ofi_rdma.c
In insert_rdma_recv_req_into_msgbuff(), when a request can not be added to the msg buff because it was already in  progress, we intend to return a NULL request so NCCL can retry the operation. Instead, we were returning this error (which translates to ncclSystemError) causing the application to fail. The send side logic handles this correctly.
=> rdma: Do not fail recv when returning a NULL request

tests/unit/aws_platform_mapper.c
this test did not bind the global logger to a pointer, which caused a deref when run under ENABLE_TRACE builds.
=> unit/platform-mapper: ENABLE_TRACE segfault fix

src/nccl_ofi_ofiutils.c
https://github.com/aws/aws-ofi-nccl/issues/753
Return an error code to prevent the code proceeding after failure
=> fix(ofiutils): set error code before failing

include/nccl_ofi_rdma.h, src/nccl_ofi_rdma.c
Separate out bounce buffer freelists into a smaller-sized freelist for
control messages and a larger size for data (eager) messages
=> rdma: add separate bounce buffer freelist for data (eager) messages

src/nccl_ofi_rdma.c
The `num_inflight_writes` counter tracks the number of inflight RDMA
write operations. It is used in deciding whether to send a message
eagerly.
Currently, we decrement the counter when freeing the corresponding send
request. There is one case where we free a send request, resulting in
decrementing `num_inflight_writes`, before we reach the point where we
increment this counter. In this case, we pass `dec_inflight_reqs =
false` to `free`.
So, only decrement the writes counter if this flag is true.
=> fix(rdma): fix decrement of `num_inflight_writes` counter

include/nccl_ofi_sendrecv.h, src/nccl_ofi_sendrecv.c
The sendrecv code includes a number of places that were referencing the device object solely to get the max_tag value.  Simplify things and reduce cache usage by including a copy of max_tag in the endpoint structure.
This is general cleanup, but part of a patch series working towards removing a bunch of locking from the code to a high level lock, but cleanups like this also help minimize the random cache lines we're loading.
=> sendrecv: Include copy of max_tag in endpoint

include/nccl_ofi_param.h, src/nccl_ofi_rdma.c
Add an environment variable OFI_NCCL_FORCE_NUM_RAILS, which will force the number of rails to be the given value (0 means follow the default). If the value is less than the number of NICs found, only the first value NICs will be used.  If the value is more than the number of NICS found, then this will create multiple rails per NIC, with the requirement that the number of rails be a multiple of the number of NICs.
The goal of this patch is to allow P5/P5e and P5en interoparate without lots of rail count detection code.
=> rdma: Add ability to force rails count value

src/nccl_ofi_net.c, src/nccl_ofi_rdma.c
Since NCCL generally uses a different thread for initializing the plugin and creating communicators, the quick hack of leaving a mostly configured endpoint from init just resulted in us leaking resources; that endpoint was never actually going to be used.  The whole reason for the refcount hack in init was a bug in EFA on P5en at launch where destroying and rapidly creating a new QP when the old QP had rx buffers attached could cause an error.
Rather than keep the whole endpoint around and leaking resources, just delay the parts of the operation that were causing races until after init, when the first communicator is created.  Now, endpoint creation during init() doesn't post buffers and is immediately destroyed, avoiding the whole leak.  And because either listen or connect will be …
=> rdma: simplify init / delay posting rx buffers

.ci/aws/Jenkinsfile
Jenkins has a default step to checkout the code base from SCM, which took around 30s. But we defined next step to be workspace cleanup.
This change is to skip the default step and only checkout the code base as we defined in the pipeline step
=> .ci/aws: Skip default SCM checkout

.gitignore, tests/functional/.gitignore, tests/functional/Makefile.am, tests/unit/.gitignore, tests/unit/Makefile.am
Adopt a policy that the project gitignore only applies to files common to all developers. Add a comment about this, explain how to ignore files globally (across all repos, not just aws-ofi-nccl) and locally (for aws-ofi-nccl only, but in a way that does not sync with others).
Reduce the set of ignore rules to follow that -- use the github autotools gitignore template, alongside a few rules for our specific automake config.
Continuation of #773 
=> build: clean up .gitignore

include/nccl_ofi.h, src/nccl_ofi_net.c
Remove the functionality to create an endpoint per thread.  Originally, this was used to create a full domain/endpoint/cq set of objects per thread that created a communicator, but that got messy as the rdma transport created multiple endpoints per thread based on the comm in use.  So we ended up in a place where we were creating a domain per thread (sometimes) and an endpoint per thread (always), which was messy but worked.
Now that there's an explicit domain object and we create a domain per thread, all the endpoint per thread stuff was really duplicative, so just remove it.
=> core: Don't create an endpoint per thread

include/nccl_ofi.h, src/nccl_ofi_api.c, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
When aborting with no connection established, there were QPs leaked if any domain and endpoint left open.
This patch adds domain and endpoint cleanup logic at the beginning of rdma and sendrecv device release (which will be called by `nccl_net_ofi_plugin_fini()` for each device) to prevent the QP leak.
Note the logic can be triggered without #772.
=> fix: unload: Cleanup active domains and endpoints

3rd-party/Makefile.am, 3rd-party/nccl/cuda/include/nccl/net.h, 3rd-party/nccl/cuda/include/nccl/net_device.h, 3rd-party/nccl/cuda/include/nccl/net_v9.h, 3rd-party/nccl/neuron/include/nccl/net.h, include/nccl_ofi.h, include/nccl_ofi_api.h, src/nccl_ofi_api.c, src/nccl_ofi_interface_nvidia.c, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c, tests/functional/nccl_connection.c, tests/functional/nccl_message_transfer.c, tests/functional/ring.c, tests/functional/test-common.h
This PR is to support the v9 interface of the NCCL plugin interface:
1. imports new headers from NCCL v2.24.3 which contains the definition of the new net-plugin v9 API . The primary changes for NCCL are:
1. NIC fusion / vitual NIC support
2. API supports indication when completion is not needed ( e.g. LL128)
3. DeviceProps supports max transfer size for p2p/coll operations 
1. adds plugin support for the new net-plugin v9 API. This involves updating the unit-tests to use the v9 API, exposing a ncclNetPlugin_v9 symbol and implementing the getProperties() API for v9.
make passed
NCCL test all_reduce_perf completed without error
=> Support NCCL plugin v9 interface

src/nccl_ofi_rdma.c
The plugin sets the `FI_TC_LOW_LATENCY` traffic class parameter for control endpoints. We were passing the wrong argument to `nccl_ofi_ofiutils_init_connection`, resulting in the traffic class setting being ignored.
=> fix(rdma): fix traffic class parameter in endpoint creation

src/nccl_ofi_ofiutils.c
The AWS Libfabric team pointed out that we were being way too loose with our provider matching when looking for rails, in a way that could result in us finding multiple provider entries for the same underlying NIC.  This patch's primary goal is to improve the filtering logic for providers by doing a deeper match, as suggested by the team.
This required writing yet another loop to pull entries out of a provider list, so at the same time, I refactored that code to have a single function that did the list management bits and simpler filtering functions for deciding what goes and what stays.  This is marginally more readable, but should make adding additional provider list manipulations much easier.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> ofi: Improve provider filtering / matching

src/tuner/nccl_ofi_regions.c
Since the regions are not well defined and have many outliers at two nodes, 
we should default to the internal tuner on two nodes.
=> fix : Default to nccl internal tuner on two nodes

include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
With this patch series, the rdma transport passes basic tests with the efa-direct fabric in the efa provider.  The primary issues were that both transports claimed support for FI_MR_LOCAL when they didn't actually support FI_MR_LOCAL and that the rdma transport did not support FI_CONTEXT2.  The sendrecv transport obviously doesn't work with efa-direct, however this patch series fixes the FI_MR_LOCAL issues in sendrecv, because fixing it in only one transport didn't make sense.
=> Add all the features required to support efa-direct

3rd-party/nccl/cuda/include/nccl/err.h, 3rd-party/nccl/cuda/include/nccl/types.h, include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, src/nccl_ofi_api.c, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c, src/tuner/nccl_ofi_regions.c
Cherry-picked the below commits to the 1.14.x branch
```
[1.14.x-staging 351db36] rdma: Refactor process_completions()
Author: Brian Barrett <bbarrett@amazon.com>
Date: Mon Feb 10 18:53:36 2025 +0000
1 file changed, 107 insertions(+), 102 deletions(-)
[1.14.x-staging 88c77bc] rdma: Fix FI_MR_LOCAL support
Author: Brian Barrett <bbarrett@amazon.com>
Date: Tue Feb 11 22:08:54 2025 +0000
2 files changed, 79 insertions(+), 23 deletions(-)
[1.14.x-staging 58e0d59] sendrecv: Fix FI_MR_LOCAL support
Author: Brian Barrett <bbarrett@amazon.com>
Date: Wed Feb 12 02:42:30 2025 +0000
2 files changed, 162 insertions(+), 51 deletions(-)
[1.14.x-staging 1eee789] rdma: Support FI_CONTEXT and FI_CONTEXT2
Author: Brian Barrett <bbarrett@amazon.com>
Date: Mon Feb 10 18:55:30 2025 …
```
=> 1.14.x staging

include/nccl_ofi_rdma.h, src/nccl_ofi_rdma.c
Reverting the commit - https://github.com/aws/aws-ofi-nccl/commit/731ebfa9177771ea69ddcae8561efa43aef7345c
on the release branch.
=> Revert "rdma: Support FI_CONTEXT and FI_CONTEXT2"

src/nccl_ofi_rdma.c
After the freelist separation between the eager and data message, we should use a freelist of at-least one byte to avoid assertion on the eager message when running with OFI_NCCL_EAGER_MAX_SIZE=0
=> fix(rdma): Set minimum size of the eager message freelist to one

include/nccl_ofi_param.h, include/nccl_ofi_rdma.h, src/nccl_ofi_freelist.c, src/nccl_ofi_rdma.c, src/platform-aws.c
Two changes that ended up being the same code: fix 0 byte eager max size and add support for disabling eager messages completely.
0 byte eager support broke with #614, with a number of problems in the code.  First, freelist code doesn't work with 0 byte entry size.  #789 got us closer, fixing the assert, but some versions of the EFA provider (like that in 1.22 with zero copy) will return an EINVAL when trying to post a receive with len = 0.  We split the eager size configuration into the `eager_rx_buff_size` and `eager_send_size` explicitly so that the buffer size can be larger than the max send size, and make sure that the `eager_rx_buff_size` is always larger than 0.
Previously, the EAGER_MAX_SIZE environment variable was an unsigned integer, meaning that the smallest legal value was 0. …
=> Add support for disabling eager (and fix 0 byte eager max size)

include/nccl_ofi_param.h, include/nccl_ofi_rdma.h, src/nccl_ofi_freelist.c, src/nccl_ofi_rdma.c, src/platform-aws.c
Parts of the freelist assume entry_size is larger than 0 bytes, but the interface does not check for size and does not specify restrictions either way.  Improve the situation by overriding a 0 byte entry size to be 8 bytes (plus any additional size increases caused by the alignment and redzone requirements).  This seems better than a bunch of 0 byte checks through the rest of the code.
(cherry picked from commit 74fc0ae4ac08c6dba79ff2907231a7a500e2efda)
=> freelist: Handle 0 byte entry_size

src/nccl_ofi_rdma.c
Commit 8487235 added support for FI_CONTEXT and FI_CONTEXT2, but neglected to fix the request lookup in the error path.  This patch fixes the error handling path, and adds an op_context to request lookup function so that we don't do this particular silly again.
=> rdma: Fix request lookup on error

.ci/aws/Jenkinsfile
https://sim.amazon.com/issues/Samwise-40
This patch eliminates PortaFiducia's setups that are unncessary when running tests on containers.
=> Configure PortaFiducia to run in lean setup

include/nccl_ofi_rdma.h, src/nccl_ofi_rdma.c
The primary goal of this patch series is to fix another bug introduced with https://github.com/aws/aws-ofi-nccl/pull/614 that https://github.com/aws/aws-ofi-nccl/pull/794 didn't fix, specifically an issue with how NCCL 2.24 and earlier behaved with 0 byte send/recv from user registered buffers.  In those configurations, NCCL would pass an mhandle that was valid but not one that covered the base pointer of the buffer.  This patch fixes that by using the flush buffer for the source / dest of 0 byte send / recv, so that we always have a valid MR for the buffer.
That was simplest by moving the flush buffer into the domain, so that we didn't have to add a ton of flush buffers, one for each new communicator.  However, that simplified the code just enough that static analysis suddenly found lots …
=> Fix 0 byte sends/receives with user buffer registration

include/nccl_ofi.h, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
Commits 27548d4 and a1ac0f5 fixed providers that required memory registrations when FI_MR_LOCAL was set, but also broke providers that clear FI_MR_LOCAL (such as HPE's provider), because I did not account for the mr_local handling in the send/recv transport.
We don't have a great way to test that case from AWS, the vast majority of transfers will either be HMEM (which creates an MR anyway) or control messages (which have a freelist which creates an MR), and the Libfabric specification allows passing an MR descriptor to a local operation even if the provider clears the FI_MR_LOCAL bit.  Therefore, the best path forward seems to be removing the code to skip registration if FI_MR_LOCAL is cleared, and always creating an MR.
By submitting this pull request, I confirm that my contribution is …
=> Remove support for not creating local MRs

include/nccl_ofi.h, include/nccl_ofi_param.h, include/nccl_ofi_rdma.h, src/nccl_ofi_api.c, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c
**Background**:
When using LL (Low Latency) or LL128 protocols, NCCL sets the request pointer to NCCL_NET_OPTIONAL_RECV_COMPLETION in irecv() calls. This indicates that the plugin can complete a receiver request early without plugin explicitly polling the CQ to validate data arrival. This is achievable because NCCL itself following LL protocol semantics will validate data arrival by checking the flag bytes.
**Plugin Optimization Details:**
This change set early completion by default to be enabled when data progress model is FI_PROGRESS_AUTO.
1. Receiver Side:
1. Marks request completion immediately after CTRL message send completion
1. Does not wait for RDMA write operation completion
1. Sender Side:
1. Uses fi_write instead of fi_writedata, to eliminate …
=> rdma: Support early completion of recv() requests

.ci/aws/Jenkinsfile, include/nccl_ofi.h, include/nccl_ofi_param.h, include/nccl_ofi_rdma.h, src/nccl_ofi_api.c, src/nccl_ofi_net.c, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
Cherry-picked below commits into 1.14.x branch
```
9d90c0e  rdma: Support early completion of recv() requests
4117397 ofi: add data progress model detection
a20854e Remove support for not creating local MRs
167e6dc rdma: Overwrite buffers for 0 byte messages
161cb12 rdma: Fix flush buffer cleanup
4195fa8 rdma: Move flush buffer to domain object
21ac264 rdma: Simplify MR paths
f898cb9 rdma: Simplify MR argument passing
d22b961 rdma: Make MRs be domain oriented (instead of EP)
8ee095e rdma: Remove ofi domain pointer from endpoint
4bfb9e0 rdma: Remove control rail MRs from MR
1c3b82f .ci/aws: Configure PortaFiducia to run in lean setup
ba5850a rdma: Disable eager by default
```
skipped following from master
```
71a1e68 neuron: add inf2e.32xlarge
26ed86b rdma: Fix …
```
=> v1.14.x: Cherry pick commits from master

RELEASENOTES.md, configure.ac
Correct the NCCL version to [NCCL 2.26.2-1](https://github.com/NVIDIA/nccl/releases/tag/v2.26.2-1) 
=> release: v1.14.x fix the NCCL version in RELEASENOTES

configure.ac, src/Makefile.am
The NGC containers have added some logic to try and support multiple plugins by renaming the OFI plugin to libnccl-net-aws.so.  Ignoring the naming for a second, it's clearly useful for us to conform to Sylvain's original expectation that everyone named plugins as libnccl-net-<network>.so and providing a symlink to the generic name where appropriate.  This patch causes us to generate the plugin as libnccl-net-ofi.so and create a symlink from libnccl-net-ofi.so to libnccl-net.so for backwards compatibility.
=> dist: Change default library to libnccl-net-ofi.so

configure.ac, m4/check_pkg_hwloc.m4
A patch series that most importantly removes -fanalyzer from our picky flags, because it will wrongly complain about memory leaks and NULL de-references on even the simplest of inherited object test codes.  We'll miss it, but not as much as we'd miss having working inheritance.
Found some C cruft and some autoconf warnings while touching this code (and trying, in vain, to find a set of analyzer warnings that were useful and not broken).  So those are fixed, too.
=> Remove -fanalyzer (which is broken with G++)

src/Makefile.am
f71aea22 changed the default library name from libnccl-net.so to libnccl-net-ofi.so, and then created a symlink from libnccl-net-ofi.so to libnccl-net.so.  The commit missed the upgrade path, where the install directory already contained a libnccl-net.so file, causing the symlink creation to fail.
This commit removes the libnccl-net.so file/symlink before creating the symlink, fixing the upgrade path.
=> build: Remove libnccl-net before creating symlink

src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp
**Commit 1**:
`rdma`: Lower provider not faound message to INFO
Not finding any provider in rdma initialization is not necessarily an error that users should be concerned by. When a transport isn't requested by the platform or user, both sendrecv and rdma transports are initialized. Given the restrictive requirements of the rdma transport, not finding a provider is a reasonable outcome. Log level set to INFO, instead of WARN will be sufficient. For other error codes, keeping them as WARN.
**Commit 2**:
`sendrecv`: Set FI_RMA for tcp provider
Regarding issue: https://github.com/ofiwg/libfabric/issues/10882 that `fi_mr_reg` call to the TCP provider will fail unless the `attr->requested_key` is unique for each call, while fix in Libfabric is in progress and will be …
=> Fix compatibility issues with tcp provider

.ci/aws/Jenkinsfile
Following the [config schema in PortaFiducia](https://code.amazon.com/packages/PortaFiducia/blobs/4ec5d2da102e8e459270f1b1cb3a332c9f8273d9/--/tests/configs/config_schema.yaml?__session=eyJwa2ciOiJQb3J0YUZpZHVjaWEiLCJ0YWJzIjpbeyJmaWxlIjoidGVzdHMvY29uZmlncy9jb25maWdfc2NoZW1hLnlhbWwjTDI0Ni1MMjUyIn0seyJmaWxlIjoidGVzdHMvdGVzdF9vcmNoZXN0cmF0b3IucHkifSx7ImZpbGUiOiJodHRwczovL2NvZGUuYW1hem9uLmNvbS9zZWFyY2g%2FdGVybT10ZXN0X2xpYmZhYnJpY19wcm92aWRlcitycCUzQVBvcnRhRmlkdWNpYSJ9LHsiZmlsZSI6InRlc3RzL2NvbmZpZ3MvbGliZmFicmljX3ByX3Rlc3QueWFtbCNMMTUifV19#L246-L252), adding tcp provider test coverage on g4dn
Current g4dn PR CI takes 17 minutes to run, comparing to the longest pull is 45 minutes, so adding tcp provider test won't  increase PR CI time.
By …
=> .ci/aws: Add tcp provider test on g4dn

.ci/aws/Jenkinsfile
Currently PortaFiducia is installed at each test stage of every PR even when there are no changes deployed to PortaFiducia. This patch enables reusing existing PortaFiducia's installation on the cluster when there are no changes in the downloaded PortaFiducia tarball. This saves approximately 45s of runtime per test stage.
=> .ci/aws: Enable PortaFiducia's installation reuse when applicable

include/nccl_ofi_param.h
This reverts commit 13d728effb7ea12c2043b8b31def0d38a5092eb7.
We don't want to disable Eager in a public release branch yet before validating the performance changes. Reverting it in only v1.14.x branch. And will be included in v1.14.1 release
local nccl-test with libfabric `main` and `v1.22.x` both passed
=> Revert "rdma: Disable eager by default"

configure.ac, src/nccl_ofi_net.cpp, src/nccl_ofi_rdma.cpp
Removes the `-fno-exceptions` C++ compiler flags. NCCL currently does not build with the flag, so removing it here should not have a performance impact and will make it easier to handle errors from constructors/deconstructors and STL libraries.
Also removes checking for NULL after allocating with `new`. Since `(std::nothrow)` was not being used to specify non-throwing allocators, errors in the constructor would just throw an exception rather than return NULL, making the NULL checks unnecessary. With `-fno-exceptions` removed, the exception will now be propagated up the stack.
=> Remove -fno-exceptions

.github/workflows/distcheck.yaml
Print the test suite log when "make check" has a failure, so that there's more debugging output on what caused the faiulre.  Also run "make check" before "make distcheck", since distcheck is a superset of the check tests.
=> ci: Make "make check" more verbose

include/nccl_ofi_freelist.h, src/nccl_ofi_freelist.cpp, src/nccl_ofi_rdma.cpp, src/nccl_ofi_scheduler.cpp, src/nccl_ofi_sendrecv.cpp, tests/unit/freelist.cpp
Add support to freelist for an optional callback for entry
initialization. This will be called when an entry is allocated from
memory, but not for subsequent `entry_alloc/entry_free`.
This allows the callback to perform more expensive initialization of
freelist entries that are not needed when the entry is simply reused.
Also use the callback in sendrecv and rdma protocols.
=> freelist: add entry initialization/fini callbacks

include/nccl_ofi_rdma.h, src/nccl_ofi_rdma.cpp
Fix mr_key type to be uint64_t, as per libfabric definition - https://github.com/ofiwg/libfabric/blob/11163b6da4ceca95b4135d9c316d9ee9de91e63b/include/rdma/fi_domain.h#L134
=> rmda:Fix mr_key to be uint64_t

.ci/aws/Jenkinsfile
OFI NCCL functional tests were skipped on p5 instance type because of kernel panics seen a few weeks ago. The issue was mitigated with GDRCopy version update. Enabling the tests now that the issue is mitigated.
=> .ci/aws: Enable OFI NCCL functional tests on p5 instance type

.ci/aws/Jenkinsfile
This patch removes NCCL version from Jenkinsfile and specifies the same in PortaFiducia. This eliminates multiple definitions and the workflow necessary to update NCCL versions at multiple places when required. 
The idea is to have the version required by the PR CI should be built in the AMI which is easier to maintain when there is a single place of definition.
=> .ci/aws: Remove NCCL version definition from Jenkins file

include/nccl_ofi_param.h, include/nccl_ofi_scheduler.h, src/nccl_ofi_rdma.cpp, src/nccl_ofi_scheduler.cpp, tests/unit/scheduler.cpp
Three changes all around control message handling:
* Split the eager and control message posted rx limit settings, and greatly increase the number of posted control rx buffers.
* Split the round-robin behavior for short and long messages, to avoid a degenerate case where control messages used one NIC and large messages used another, leading to bandwidth limitations)
* Enable using all rails for control messages by default.
=> Control message scheduling improvements

src/nccl_ofi_net.cpp
The domain cleanup code iterates over `domain_table` and calls `domain->release()`, which removes `domain` from the table. This invalidates the iterator that was pointing to `domain`, causing a use-after-free when reusing the iterator.
As a quick fix, increment the iterator (so it is pointing to the next item) before calling `domain->release()`.
=> net: fix iterator use-after-free during domain cleanup

include/nccl_ofi_tracepoint.h, include/tracing_impl/lttng.h, include/tracing_impl/nvtx.h, src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp
Add and updated tracepoints for improved analysis 
- add RecvEnd, SendEnd to Lttng
- add comm field to Recv  segment completion trace
- change comm_id to comm for Recv tracepoint to align with other tracepoints
=> Add and update tracepoints for improved analysis 

include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, src/nccl_ofi_rdma.c, src/nccl_ofi_sendrecv.c
Reimplemented the following 2 master branch changes in C only style.
related PR - https://github.com/aws/aws-ofi-nccl/pull/833
```
2157b0a sendrecv: Add mr_handle structure to track mr_key
381b605 rmda:Fix mr_key to be uint64_t
```
nccl-test passing for both tcp and non-tcp provider with libfabric 2.1.x branch.
=> [V1.14.x] Add mr_handle structure to track mr_key

include/nccl_ofi.h, include/nccl_ofi_idpool.h, src/nccl_ofi_idpool.cpp, src/nccl_ofi_net.cpp, src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp, tests/unit/idpool.cpp
Refactors the nccl_ofi_idpool implementation to C++, creating a nccl_ofi_idpool_t class with std::vector and std::mutex member variables and thread-safe wrappers to interact with the std:vector. Updates all usage of the previous nccl_ofi_idpool C implementation to use the new class.
=> Refactor nccl_ofi_idpool to C++

.ci/aws/Jenkinsfile, .github/workflows/distcheck.yaml
Cherry-pick following CI changes into V1.14.x branch
```
9761e70 .ci/aws: Remove NCCL version definition from Jenkins file
48ee8dd .ci/aws: Enable OFI NCCL functional tests on p5 instance type
e9402e8 ci: Make "make check" more verbose
```
=> [V1.14.x] Cherry-pick CI changes

include/Makefile.am, include/stats/histogram.h, include/stats/histogram_binner.h, tests/unit/.gitignore, tests/unit/Makefile.am, tests/unit/histogram.cpp, tests/unit/histogram_binner.cpp
Add basic in-memory histogram classes to track events and time intervals.  This was useful to me in looking at some of the cq completion behaviors, so thought we should make it available for other analysis work as well.
=> Add histogram interface

include/nccl_ofi.h, include/nccl_ofi_rdma.h, include/nccl_ofi_scheduler.h, src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp
Two not entirely related cleanups to how we handle rail ids in the rdma transport.  The first changes the signed indexes for rail ids into unsigned, since we can never have negative (or even 0) rails.
The second adds a back reference index to the domain rail structure (to match other rail structures), as part of a plan to eventually move CQs to domains, where they belong in the RDMA transport.
=> rdma: Rail id handling cleanups

include/nccl_ofi_param.h, m4/check_pkg_cuda.m4, src/nccl_ofi_net.cpp
This commit enables DMA-BUF by default, except for EFA generations 1-3.  See comment in ofi_nccl_net.c for information on why we do not enable DMA-BUF on older EFA generations.
=> config: Enable DMABUF by default (Except on EFA gen 1-3)

src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp
In commit 35264d2, we changed the error processing code so that `fi_cq_err_entry` was left uninitialized (instead of zero-initialized) on call to `fi_cq_readerr`. However, per the Libfabric spec, the `err_data_size` field of `fi_cq_err_entry` needs to be set to zero (or a valid buffer provided):
> If err_data_size is 0 on input, or the fabric was opened with release
> < 1.5, then any buffer referenced by err_data will be ignored on input.
ref: https://ofiwg.github.io/libfabric/v2.1.0/man/fi_cq.3.html
Fix by zeroing out the whole struct, as we did before.
=> rdma: fix uninitialized value on fi_cq_readerr call

src/nccl_ofi_net.cpp
The Libfabric strings include the 0x prefix for the device id, which our simple string match didn't account for.
=> Fix EFA device id for DMA-BUF search

include/nccl_ofi_api.h, src/nccl_ofi_api.cpp, src/nccl_ofi_interface_neuron.cpp, src/nccl_ofi_interface_nvidia.cpp
Change our API version name scheme so that all interface functions include a version in the function name.  The version is the version in which that api was introduced (rather than the previous scheme, in which the version in the name was the last version in which the API was used).  This should make adding new API calls easier, in that the only required change will be adding a new API, and we no longer have to rename the old API to add the version.
This is motivated by the discussions in https://github.com/aws/aws-ofi-nccl/pull/820.
=> Rework API version management

include/nccl_ofi_param.h, src/nccl_ofi_rdma.cpp
While the eager protocol did not have an impact on nccl-tests performance, it did have a sizeable (30% difference in step time for Maxtext Llama2 70B on P5) impact on applications.  So re-enable the eager protocol, and adjust the early completion detection to automatically adjust to eager enablement.
We need to come back to the early completion protocol and find a way to have early completion and eager co-exist in the general case, but that's future work.
=> rdma: Re-enable eager messages

include/nccl_ofi_param.h, src/nccl_ofi_net.c
GB200 and friends require DMA-BUF support for GPUDirect support.  We know there's an issue with DMA-BUF on older generations of EFA, so blocklist them.  But otherwise enable DMA-BUF support by default.
=> v1.14.x: Enable DMA-BUF support, except on EFA generations 1-3

include/nccl_ofi.h, include/tracing_impl/lttng.h, src/nccl_ofi_api.cpp, src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp
Rework of #820, updating the API of send/receive to v9 based on changes made in #853 . 
The default value of the size parameter in send/receive has been changed from `int` to `size_t`.
=> api: Update and increment send/recv functions to V9

include/nccl_ofi_rdma.h, src/nccl_ofi_rdma.cpp
sheduler was in device level and used two locks. One is freelist lock and the other is scheduler->rr_lock. When a device has multiple threads and is shared by them, there is lock contention problem in send posting. As a short term solution, move scheduler to domain not to share the scheduler resources by multiple threads.
N/A
sheduler was in device level and used two locks. One is freelist lock and the other is scheduler->rr_lock. When a device has multiple threads and is shared by them, there is lock contention problem in send posting. As a short term solution, move scheduler to domain not to share the scheduler resources by multiple threads.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> scheduler: move schduler to domain level

topology/g5.48xl-topo.xml
Since G5 platforms did not support PCIe technologies properly, the NIC generated by NCCL in the topology file reported a numa domain of -1. NCCL further assigns it the same system ID as the CPU. CPUs with the same system ID are not connected to each other during topology generation. This results in a seg fault during topology path computation as GPUs are not able to find a path to the NIC.
=> topo: add NIC to numa domain on g5.48xlarge platforms

include/nccl_ofi_ofiutils.h, include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, src/nccl_ofi_ofiutils.cpp, src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp
We currently do not create more than one cq per (OFI) domain, so the cq was effectively at the domain level anyway. This commit updates cq references to point to the domain (rail) instead of the endpoint.
=> rdma,sendrecv: refactor completion queue to the domain

contrib/scripts/generate_debian_changelog.sh, include/nccl_ofi.h, include/nccl_ofi_ofiutils.h, include/nccl_ofi_platform.h, include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, include/nccl_ofi_system.h, include/platform-aws.h, include/tracing_impl/lttng.h, src/nccl_ofi_api.cpp, src/nccl_ofi_net.cpp, src/nccl_ofi_ofiutils.cpp, src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp, src/nccl_ofi_system.cpp, src/platform-aws.cpp, topology/g5.48xl-topo.xml
Cherry-picked below commits from head of master branch:
```
ad2cf10 rdma: Do not send close message for unused r_comm
4825229 rdma: Refactor recv_comm_process_all_finalizing
a7dedd7 aws: Provide a more appropriate GUID to NCCL
3b1171d system: Add utility to generate a unique node identifier.
c887c00 rdma: Allow for devices with varying number of rails
9010983 rdma,sendrecv: refactor completion queue to the domain
a19783c topo: add NIC to numa domain on g5.48xlarge platforms
e8e1641 Revert "build: remove git mailmap usage"
cc47fda scheduler: move schduler to domain level
8c0c882 api: Update and increment send/recv functions
```
Which should make `v1.15.x` match the head of `master` (as of the time of cutting this PR).
---
With force push added:
```
ba9b7c9 platform: Generalize log message …
```
=> [v1.15.x] Cherry-pick commits to have v1.15.x match head of master

include/nccl_ofi.h, src/Makefile.am, src/nccl_ofi_nccl_compat.cpp, src/nccl_ofi_topo.cpp
The topology code in NCCL 2.21 added a host_hash field for multi-node NVL support.  We missed that the host_hash isn't added to the final topology when we provide a minimal topology for multi-rail.  This is fine on single-node NVL, but breaks multi-node NVL.  While the right fix may be to have NCCL properly merge here, fixing the issue in the plugin by providing a host_hash is going to be a faster time to solution.  Copy the host_hash code from NCCL so that we always generate the same hash as NCCL would have.
Long term, the right solution for us is to use the vNIC code in recent versions of NCCL (which happen to be the versions that we will support for multi-node NVL, where this bug matters).
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> topo: Add host_hash field to generated topology

include/tracing_impl/nvtx.h
Commit 1c97c90 changed the macro `NCCL_OFI_TRACE_RECV_NVTX` argument name to `comm`, which conflicted with that name's use inside the macro. Change the name to `r_comm` to avoid the conflict.
=> nvtx: fix build error due to argument name

src/Makefile.am
Currently, `libnccl-net-ofi.la` does not depend on any C++ source files
(instead depending on an internal library, `libinternal_net_plugin.la`),
and so is built as a C library (using `gcc` instead of `g++`), which
means it is not linked against the C++ standard library. Add `--tag=CXX`
to force C++ linkage.
=> build: Force C++ library linkage for `libnccl-net-ofi`

include/nccl_ofi_param.h, src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp
The efa-direct path was using a smaller default CQ size (1K). Update fi_cq_open to use the same CQ size as the EFA RDM path by explicitly setting cq_attr->size.
=> fix: Set CQ size to match EFA RDM path

3rd-party/Makefile.am, 3rd-party/nccl/cuda/include/nccl/net.h, 3rd-party/nccl/cuda/include/nccl/net_device.h, 3rd-party/nccl/cuda/include/nccl/net_v10.h, 3rd-party/nccl/cuda/include/nccl/types.h, include/nccl_ofi.h, include/nccl_ofi_api.h, include/nccl_ofi_param.h, include/tracing_impl/nvtx.h, src/Makefile.am, src/nccl_ofi_api.cpp, src/nccl_ofi_interface_nvidia.cpp, src/nccl_ofi_nccl_compat.cpp, src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp, src/nccl_ofi_topo.cpp
Cherry-picked below commits from head of master branch:
```
fd4cbfb fix: Set CQ size to match EFA RDM path
2729a5f build: Force C++ library linkage for `libnccl-net-ofi`
4c548c5 nvtx: fix build error due to argument name
085f9c9 api: Integrating v10 api
f16f5bd update: Adding v10 api to 3rd party headers
3a85eba topo: Add host_hash field to generated topology
```
Which should make `v1.15.x` match the `HEAD~1` of master as of the time of cutting this PR (excluding commit `param: Change min_stripe_size default from 128K to 64K` #878).
=> [v1.15.x] Cherry-pick recent commits

src/nccl_ofi_rdma.cpp
A common fi_write and fi_writedata mesage is used for an error from either function, but always describes the function name as fi_writedata.
This is confusing when fi_write generated the error.
=> Fix confusing error message for fi_write and fi_writedata

.github/workflows/update-containers.yaml, docker/base/Dockerfile.al2023, docker/base/Dockerfile.codechecker, docker/base/Dockerfile.ubuntu
- Created new workflow to build and maintain Docker containers, updated weekly
- Each build type has its own container in GitHub Container Registry:
* aws-ofi-nccl-al2023
* aws-ofi-nccl-ubuntu
* aws-ofi-nccl-codechecker
=> ci: Update workflow to use pre-built docker containers

.github/workflows/distcheck.yaml
There is no use case for Neuron builds without AWS platform. Since AWS
platform builds of the plugin require EFA installer 1.34 or later, do
not attempt a Neuron build with older EFA installer.
Follow-up commit includes EFA installer 1.34 for increased testing coverage.
=> actions: Do not build Neuron without platform-aws

src/Makefile.am
Currently, `libnccl-net-ofi.la` does not depend on any C++ source files (instead depending on an internal library,
`libinternal_net_plugin.la`) when build for neuron platforms, and so is built as a C library (using `gcc` instead of `g++`), which means it is not linked against the C++ standard library. Add `--tag=CXX` to force C++ linkage.
This fix has previously added for non-neuron platforms. This PR adds same fix when neuron is enabled.
=> fix: Force C++ library linkage for `libnccl-net-ofi` on neuron

include/nccl_ofi.h, src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp
- device->get_ofi_info(): get fi_info * associated with this device
- domain->get_ofi_domain(): get fid_domain * associated with this plugin
domain
- domain->get_ofi_cq(): get fid_cq * associated with this plugin domain
For RDMA protocol, these accessors return objects associated with the
"leader NIC" of the multi-rail group.
This will be useful for the upcoming connection manager, which can take
a `nccl_net_ofi_domain_t` object as a parameter, instead of individual
Libfabric objects.
=> Add accessors to device and domain for OFI objects

tests/unit/.gitignore, tests/unit/Makefile.am, tests/unit/aws_platform_mapper.cpp, tests/unit/dlopen_c_test.c, tests/unit/ep_addr_list.cpp, tests/unit/freelist.cpp, tests/unit/histogram.cpp, tests/unit/idpool.cpp, tests/unit/mr.cpp, tests/unit/msgbuff.cpp, tests/unit/scheduler.cpp, tests/unit/test-logger.h
This test checks whether plugin library can be loaded with dlopen from c application . The reason is that plugin formerly didn't link against libstdc++ and relied on application to provide required linkage. This has been fixed by recent commit but test was not added.
This test should only be merged after PR https://github.com/aws/aws-ofi-nccl/pull/897, which fixes above mentioned issue on neuron platforms, has been merged.
=> test: Add unit test verifying c application can dlopen library

src/platform-aws.cpp, tests/unit/aws_platform_mapper.cpp
Updating hard coded latency values for p5 and p6 to 35 us based on an empirical search and analysis difference configurations. 
=> update: Updating latency value for p5 and p6 based on empirical search

contrib/python/ofi_nccl/tuner/cli/wrapper.py, include/tuner/nccl_ofi_tuner_common.h, src/tuner/nccl_ofi_regions.cpp, src/tuner/nccl_ofi_tuner.cpp
Backport p6-b200 tuner to `v1.15.x` release branch:
```
8c3ccff tuner: build p6 region based tuner
```
=> [v1.15.x] Backport p6-b200 tuner

include/nccl_ofi_param.h, src/nccl_ofi_rdma.cpp
The close message was intended to enable a future optimization to the plugin's eager protocol (not yet implemented) where sender will not wait to receive a control message from receiver before marking a send complete. Instead, sender waits for a close message when the communicator is closed, indicating it is safe to close the communicator resources.
During testing of fault-tolerance (NCCL restart after abort), we found situations where the plugin hangs while waiting for a close message, specifically when some ranks enter an abort state (due to having inflight requests) and some don't.
Until we have a long-term fix for this, we disable the close message by default.
=> rdma: disable close message by default

README.md
We included this in the release notes and README in the `v1.14.x` release branch, but did not update the README in master.
Previous added in #807 to the `v1.14.x` release branch for the `v1.14.0`  release.
=> doc: Add Ubuntu 24.04 to the supported distro list

README.md
We included this in the release notes and README in the v1.14.x release branch, but did not update the README in master.
Back-porting this change to the `v1.15.x` release branch.
(cherry picked from commit 4037f5e6c454d9f2099792d54106dcb683ad9740)
=> [V1.15.x] Cherry-pick Ubuntu 24.04 README update 

src/nccl_ofi_rdma.cpp
Recently (57f424b), we delayed posting of rx buffers from endpoint creation until connection establishment routines were called. This resulted in us never posting rx buffers for endpoints created in endpoint-per-communicator mode, resulting in a hang.
=> rdma: Fix endpoint-per-communicator rx buffer posting

include/nccl_ofi.h, include/nccl_ofi_pthread.h, src/nccl_ofi_api.cpp, src/nccl_ofi_net.cpp, src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp, tests/functional/.gitignore, tests/functional/Makefile.am, tests/functional/inflight_close.cpp
Closing a communicator that still has requests inflight will deactivate
the domain, preventing use of all other communicators on the domain for
anything except closing the communicator.
This is necessary because, when closing a communicator, the only way to
ensure user memory is no longer accessed is to close the corresponding
endpoint.
This PR also contains some marginally related bug fixes along the way.
Marked as a draft because the new domain inactive functionality needs testing.
=> rdma, sendrecv: deactivate domain when closing inflight communicators

configure.ac
Following the v1.15.0 release from the v1.15.x release branch, bump the release branch version to v1.15.1a1.
=> release: begin 1.15.1 cycle

include/nccl_ofi_api.h, src/nccl_ofi_api.cpp, src/nccl_ofi_interface_neuron.cpp
init and fini functions are exposed by multiple APIs. The implementation slightly differs but for both functions, common functionality is factored out by this commit. This readability as well as avoids future bugs since it minimizes exact same code at multiple places.
=> api: refactor base init/fini functionality into subroutines

src/Makefile.am, src/tuner/nccl_ofi_tuner.cpp, tests/functional/Makefile.am, tests/unit/Makefile.am
As the title says, enable the tuner by default on supported AWS platforms, by including the tuner code in the net plugin.  This will cause NCCL 2.21 and later to load the tuner by default unless a more specific tuner is specified by the user ([see the NCCL docs](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-tuner-plugin)).
=> Enable the AWS tuner by default on AWS platforms

configure.ac
Update the v1.16.x version number to v1.16.0a1 to differentiate the release branch from the head of master.
=> Update version number in v1.16.x release branch

include/nccl_ofi.h, include/nccl_ofi_ep_addr_list.h, include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, src/nccl_ofi_api.cpp, src/nccl_ofi_net.cpp, src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp
Draft PR for a first iteration of using proper C++ inheritance in the OFI NCCL plugin.
Replaces the C-style inheritance of having a base endpoint instance as the first member of the transport endpoint types with the C++ approach of making nccl_net_ofi_ep_t a parent class with virtual functions that the transport endpoint types override. This also refactors the allocation and free functions for the base and transport endpoint types to be constructors and destructors.
Some changes this draft PR does not yet include:
1. Moving endpoint constructor and destructor helper functions to be private member functions. For example,  `nccl_net_ofi_rdma_ep_t`'s constructor calls helper functions `init_rail_ofi_resources` and `init_rx_buffers`, which are currently free functions in `nccl_ofi_rdma.cpp` …
=> Refactor endpoint types to use C++ inheritance

include/nccl_ofi_tracepoint.h, include/tracing_impl/lttng.h, src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp
Updated as of June 19, 2025.
In order to more easily differentiate between SENDRECV and RDMA transport
LTTng ProcessCompletions traces associated with send requests or with
recv requests, this splits ProcessCompletions into separate
ProcessCompletionsSendRecv and ProcessCompletionsRdma traces.
ProcessCompletionsRdma adds the request type (enum
nccl_net_ofi_rdma_req_type_t) as a field to the LTTng tracepoint
(req_type). Now, when processing ProcessCompletionsRdma traces you can
identify send requests which will have req_type NCCL_OFI_RDMA_SEND
(enum value of 2) and recv requests which have req_type
NCCL_OFI_RDMA_RECV (enum value of 3).
The SENDRECV transport analog to the RMDA transport request type is the
request direction (enum nccl_net_ofi_sendrecv_req_direction_t). …
=> lttng: Add req_type to ProcessCompletions trace

.github/workflows/distcheck.yaml
Currently the github actions workflow installs all the packages during runtime. Instead we want to install all the packages except aws-ofi-nccl plugin within a docker container and use this container during runtime.
This commit updates the PR-CI to use the pre-built containers instead of installing the stack during runtime.
=> ci: Update workflow to use pre-built docker containers - Part 2

src/tuner/nccl_ofi_regions.cpp
Adjust P6 region tuner switch point for 0x0 32 rank with large message sizes so that it can choose Ring instead of Nvlstree algorithm for a better performance.
=> tuner: Adjust P6 region tuner for 0x0 32 rank

contrib/python/ofi_nccl/tuner/cli/main.py, contrib/python/ofi_nccl/tuner/cli/wrapper.py, include/internal/tuner/nccl_defaults.h, src/tuner/nccl_ofi_regions.cpp
1. Add channel count to tuner unit test output matrix
2. Add logic to controls nChannels at mid msg sizes [4,32] MB for P6
1. Unit test:
(`nchannels` is what tuner returns to NCCL. when nchannels==0, NCCL has another maxChannel variable to load the channel counts)
2.  4/8/16 node improvements are shown below(1MB incremental datapoints), this gives confidence that the nChannel decisions will mostly improve performance at larger ranks as well.  
```
❯ uv run show-tuner-decisions ~/workspace/aws-ofi-nccl/p6_nchannel_tuner/src/.libs/libnccl-net-ofi.so --min-ranks-per-node 8 --max-ranks-per-node 8 --min-nnodes 16 --max-nnodes 16 --show-channels 2>&1 | grep -A 100 "collective  algo   proto platform"
collective  algo   proto platform
nodes ranks message_size nchannels
16    128   32 …
```
=> tuner: tune nChannels at mid msg sizes for P6

include/nccl_ofi_param.h
This reverts commit 34c256e942ca274b9fd1238464d07b37c53ad43f due to decrease in performance seen in 16 node case at certain message sizes.
=> Revert "param: Change min_stripe_size default from 128K to 64K"

src/nccl_ofi_ofiutils.cpp
The Libfabric manual
(https://ofiwg.github.io/libfabric/main/man/fi_endpoint.3.html) states that `FI_TRANSMIT` should be used for `fi_ep_bind`, not `FI_SEND`. The two are synonymous today, but updating to match the spec.
=> ofiutils: Use `FI_TRANSMIT` to bind CQ to EP

src/nccl_ofi_rdma.cpp
When `NCCL_TOPO_FILE` is already set in the environment (either by the user, or by the parent process in case of `fork()`), print an INFO log message instead of a TRACE log message.
=> rdma: Add INFO print when topo file is already set

README.md
Update README.md to reflect fact that we no longer support Ubuntu 20.04 as a supported operating system.
=> doc: Remove Ubuntu 20.04 as supported operating system

configure.ac
Following the v1.16.0 release from the v1.16.x release branch, bump the release branch version to v1.16.1a1.
=> release: Begin 1.16.1 cycle

.ci/aws/Jenkinsfile
*Issue #, if available:* V1825888675
*Description of changes:* Deprecate U20 tests and upgrade to U22
=> Deprecate U20 in ECT PR CI

.github/workflows/distcheck.yaml
There's not a great reason to filter CI on PRs, and the filters cause large PRs to not run GH actions, which isn't what we want.
=> ci: Do not filter paths for PRs

include/nccl_ofi.h, src/nccl_ofi_net.cpp, src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp
When a domain is invalidated (due to communicator close with inflight requests, remove the domain from domain table, so future calls to `get_ep` do not reuse the domain. This allows creating new communicators without having closed all previous communicators.
Tested in the abort case -- this code seems to allow creation of new communicators, even if previous communicators weren't fully cleaned up.
=> Remove invalidated domain from domain table

include/nccl_ofi.h, include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, src/cm/nccl_ofi_cm_resources.cpp, src/nccl_ofi_net.cpp, src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp
Replaces the C-style inheritance of having a base domain instance as the first member of the transport domain types with the C++ approach of making nccl_net_ofi_domain_t a parent class with virtual functions that the transport domain types override. Refactors the allocation and free functions for the base and transport domain types to be constructors and destructors, and adds helper member functions for interacting with protected member variables.
Also refactors all stand-alone functions that should belong to the RDMA domain type to become member functions. Helper functions for the RDMA domain constructor and destructor were kept as protected functions.
Comparing this PR against my endpoint refactor PR #851, I returned to using the `this` keyword consistently in domain member functions …
=> Refactor domain types to use C++ inheritance

.ci/aws/Jenkinsfile
*Issue #, if available:* P253686625
In this PR, we introduced p5en instance type to the CI test matrix. Currently, it shares the same configuration as p5
---
=> .ci/aws: Introduce P5en to CI

include/nccl_ofi.h, include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, src/nccl_ofi_net.cpp, src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp
Follow-up on #851 and #938 to further refactor the endpoint classes. Updates endpoint code to match decisions made in the domain C++ refactor such as:
* re-introduce using the `this` keyword in endpoint members
* refactor transport-specific endpoint destructors to not cleanup resources (always expect an endpoint instance to be cleaned up before calling `delete`).
* update C-style casts in endpoint members to C++ casts (`static_cast` and `reinterpret_cast`)
Also refactors the stand-alone `sendrecv_endpoint_abort` function to be a SENDRECV endpoint member function.
=> Follow-up on endpoint c++ refactor

src/nccl_ofi_rdma.cpp
Fails gracefully when r_comm is null in the following paths:
1. On eager receive. This can happen in a race condition where an eager
message arrives after the recv comm has been closed, and the recv
comm did not yet have any inflight requests (so the domain was not
invalidated). However, it is not expected to happen given the way
NCCL's communicator abort currently works, where all existing
communicators are closed before a new communicator is created.
2. On write-with-immediate completion. This should never happen, because
a write implies the receiver sent the control message, so there
should be an `irecv` inflight, which means we should invalidate the
domain in this case.
This is a follow-up to #953.
By submitting this pull request, I confirm that my contribution is made under the terms …
=> rdma: Improve error handling for null r_comm for receives

src/platform-aws.cpp, tests/unit/aws_platform_mapper.cpp
To properly support using the OFI NCCL plugin on the AWS `p5.4xlarge` instance type, adds a new platform configuration specifying to use the SENDRECV transport protocol, and setting "gdr_required" to false.
=> aws: add platform config for p5.4xlarge

configure.ac
Following the v1.16.2 release from the v1.16.x release branch, bump the release branch version to v1.16.3a1.
=> release: Begin v1.16.3 cycle

.github/workflows/generate-release-draft.yml
Update release name for automated release process from `v1.*.*` to `AWS OFI NCCL v1.*.*` according to MCM instruction.
=> fix: Update release name for automated release process

src/nccl_ofi_ofiutils.cpp
According to the latest [libfabric documentation](https://github.com/ofiwg/libfabric/blob/ae8d1461d4e1bca88bdb0f59c7f5d172ef3eb1fe/man/fi_mr.3.md?plain=1#L725-L728), provider may need to use the requested key for local MRs. With [PR #833](https://github.com/aws/aws-ofi-nccl/pull/833), we are able to provide keys no matter whether the provider ignores them. Thus, we enable requested key for local MRs in case the provider need to use it.
This change has been tested with both Libfabric v1.22.0 and Libfabric V2.1.0 on P6 platform, and all passed.
=> ofiutils: enable requested key for local MRs

src/platform-aws.cpp
Enable domain-per-thread by default on all AWS instance types. We previously only enabled it for AWS Trainium instance types, but we noticed a performance degradation when NCCL creates multiple proxy threads using the same EFA device.
As a consequence, this commit will disable support for user registration
by default. We will need to do some refactoring to re-enable user
registration mode with domain-per-thread.
=> param: Enable domain-per-thread by default for AWS platforms

.ci/aws/Jenkinsfile, src/platform-aws.cpp
Enable domain-per-thread by default on all AWS instance types. We previously only enabled it for AWS Trainium instance types, but we noticed a performance degradation when NCCL creates multiple proxy threads using the same EFA device.
As a consequence, this commit will disable support for user registration by default. We will need to do some refactoring to re-enable user registration mode with domain-per-thread.
(cherry picked from commit 241e29ee5b4697abfb16d2050ea6847dba8963fc)
=> [v1.16.x] param: Enable domain-per-thread by default for AWS platforms

src/platform-aws.cpp
Reorder the `p5/p5e` entry to be before `p-series` entry, and simplify the "p5en and later" regex for `p-series` entry.
=> platform: reorder p5/p5e entry and update p-series entry

contrib/fedora/aws-ofi-nccl.spec
According to Fedora packaging documentation, the "%ldconfig_scriptlets" macro does not have any effect on Fedora, and packages that put linker configuration files in /etc/ld.so.conf.d must call "ldconfig" in "%post" and "%postun". This updates the aws-ofi-nccl.spec RPM spec file with the correct "ldconfig" calls.
Fedora docs: https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_snippets
> Packages which place linker configuration files in /etc/ld.so.conf.d MUST call ldconfig in %post and %postun (on all Fedora releases) even if they install no actual libraries. They MUST NOT use the %ldconfig, %ldconfig_post, %ldconfig_postun or %ldconfig_scriptlets macros to do this, since these macros do not have any effect on Fedora. Instead simply call ldconfig directly in both %post …
=> packaging/rpm: remove ldconfig_scriptlets in RPM spec

configure.ac, src/Makefile.am
To ensure that the "libnccl-net.so" and OFI NCCL plugin tuner paths can properly be cached by "ldconfig", this replaces the symbolic links from those paths to the "libnccl-net-ofi.so" shared library with separate shared library files.
=> build: Replace net/tuner plugin symlinks with libs

include/nccl_ofi_cuda.h, include/nccl_ofi_dmabuf.h, include/nccl_ofi_ofiutils.h, include/nccl_ofi_rdma.h, m4/check_pkg_cuda.m4, src/nccl_ofi_cuda.cpp, src/nccl_ofi_dmabuf.cpp, src/nccl_ofi_net.cpp, src/nccl_ofi_rdma.cpp
This commit optimizes rdma flush performance using the result of rdma read to determine flush completion.
We start by allocating a page-size gpu memory and setting it to a sentinel value. The flush operation will trigger a read from this gpu memory to the host buffer. Further to test if the flush request has completed, check if the host buffer has been updated to the sentinel value.
=> rdma: Optimize flush performance

contrib/debian-template/control, contrib/debian-template/rules
To align the OFI NCCL plugin DEB library installation path with the paths of other packages the plugin gets bundled with, this removes automatically configuring the DEB package to follow Debian multi-arch guidelines, and instead hard-codes the DEB library path to "/opt/amazon/ofi-nccl/lib".
=> packaging/deb: remove multi-arch from deb package library path

src/platform-aws.cpp, tests/unit/aws_platform_mapper.cpp
The changes include:
- Adding `NCCL_NETDEVS_POLICY=max:1` to a new P5en/P6-B200 platform entry, which have two NICs and two GPUs per PCIe switch in topology provided to NCCL.
- Adding new p6e-gb200 unit test case for the existing "p-series" platform entry.
(Note: The changes are the same as 2474f73 earlier.)
=> platform: Add NCCL_NETDEVS_POLICY to default environment variables

src/tuner/nccl_ofi_regions.cpp
This change only updates those for 0x0 collectives on p6.
=> tuner: update all 0x0 p6 tuner regions.

include/Makefile.am, include/cm/nccl_ofi_cm_resources.h, include/nccl_ofi.h, include/nccl_ofi_ofiutils.h, include/nccl_ofi_rdma.h, include/nccl_ofi_sendrecv.h, include/ofi/resource_wrapper.h, src/cm/nccl_ofi_cm_resources.cpp, src/nccl_ofi_ofiutils.cpp, src/nccl_ofi_rdma.cpp, src/nccl_ofi_sendrecv.cpp
To ensure that Libfabric resources managed by transport datatypes are automatically cleaned up during stack unwinding, this wraps Libfabric resources in unique_ptr with custom destructors that call "fi_close". Adds and refactors existing "ofiutils" helper functions to create and initialize the unique_ptr Libfabric resources.
I only used the unique_ptr wrapper for classes that own the associated Libfabric resource, and continued using raw pointers for classes that just use the resource owned by someone else. I also avoided updating functions to take in the unique_ptr type as an argument, and instead continue to handle the raw Libfabric resource pointers (using the unique_ptr ".get()" function).
To support the unique_ptr requirement to not be copyable, this updates the RDMA transport …
=> ofi: manage Libfabric resource lifecycle with smart pointers
