aws/aws-ofi-nccl

- tests/test-common.h
With change to provide request context while sending connect message, it
would be simpler to reduce number of send messages by 1. This would
allow enough buffers to be available for all send messages.
> MPI tests: Modify number of inflight send requests

- README.md
- RELEASENOTES.md
> Updates to Readme and Release Notes

- README.md
- include/nccl_ofi.h
- src/nccl_ofi_net.c
Modify plugin API definition as per NCCL2.4.2
> Nccl 2.4.2

- tests/nccl_connection.c
- tests/nccl_message_transfer.c
> MPI tests: Fix compiler warnings about unused variables

- README.md
- include/nccl_ofi.h
- src/nccl_ofi_net.c
> Remove FI_SOURCE dependency

- RELEASENOTES.md
> Documentation: Modify RELEASENOTES to include v0.9.2

- README.md
- include/nccl_ofi.h
- include/stack.h
- src/nccl_ofi_net.c
> Rebase aws with master to incorporate master commits in AWS branch

- README.md
- RELEASENOTES.md
> Release v1.0.0

- README.md
- RELEASENOTES.md
> [AWS] Release v1.0.0

- src/nccl_ofi_net.c
RDMAV_FORK_SAFE environment variable makes the rdma-core library
fork-safe. This significantly increases cost of memory registration when huge
pages are enabled.
To prevent data corruption, the EFA provider registers an atfork handler
which will abort the process whenever it believes rdma-core is not
fork-safe.
NCCL applications heavily re-use the buffers for communication and
thus are not sensitive to increased memory registration costs.
To prevent NCCL based applications from getting aborted when using
fork(), plugin explicitly enables RDMAV_FORK_SAFE environment variable.
cr https://code.amazon.com/reviews/CR-27719603
By submitting this pull request, I confirm that my contribution is …
> OFI-NCCL: Enable RDMAV_FORK_SAFE environment variable

- configure.ac
> OFI-NCCL: Fix typo for enabling trace messages

- configure.ac
> [aws] OFI-NCCL: Fix typo for enabling trace messages

- src/nccl_ofi_net.c
This PR contains 2 bug fixes patches:
First avoids to modify input parameter and second uses correct iterator index for selecting user-preferred provider.
> Aws: Bug fixes

- README.md
- include/nccl_ofi_param.h
- src/nccl_ofi_net.c
- tests/nccl_connection.c
- tests/nccl_message_transfer.c
- tests/ring.c
This PR enables plugin to detect and provide multiple NIC devices to NCCL. It also adds filtering mechanism to avoid unwanted interfaces and addressing formats for TCP provider.
> Aws: Support multi NICs environment

- README.md
- include/nccl_ofi_param.h
- src/nccl_ofi_net.c
- tests/nccl_connection.c
- tests/nccl_message_transfer.c
- tests/ring.c
This PR enables plugin to detect and provide multiple NIC devices to NCCL. It also adds filtering mechanism to avoid unwanted interfaces and addressing formats for TCP provider.
> Support multiple NICs environment

- Makefile.am
- RELEASENOTES.md
- configure.ac
- include/nccl_ofi.h
- src/Makefile.am
- src/nccl_ofi_net.c
- topology/Makefile.am
- topology/p4d-24xl-topo.xml
* Explicitly specify P4d hardware topology
* Let EFA provider define the bandwidth speed of devices.
> [Aws] Support P4d Platform

- README.md
- src/nccl_ofi_net.c
- tests/nccl_connection.c
- tests/nccl_message_transfer.c
- tests/ring.c
- tests/test-common.h
Add support for NCCL v2.8
Signed-off-by: David Addison <daddison@nvidia.com>
> [Aws] Support NCCL v2.8

- README.md
- src/nccl_ofi_net.c
- tests/nccl_connection.c
- tests/nccl_message_transfer.c
- tests/ring.c
- tests/test-common.h
Support NCCL v2.8.3
Signed-off-by: David Addison <daddison@nvidia.com>
> OFI-NCCL: Updated plugin to use NCCL Net V4 API

- src/nccl_ofi_net.c
For NCCL versions (v2.7.8 and less), flush() should exit sooner when
receiving 0-sized requests. We do not need to submit read requests or
test completions for 0-sized flush commands.
> OFI-NCCL: Return success for 0-sized flush messages

- .travis.yml
> OFI NCCL: Disable PSM3 from libfabric build

- README.md
- RELEASENOTES.md
> Documentation update for Release v1.1.2

- README.md
- RELEASENOTES.md
- src/nccl_ofi_net.c
> Aws: Documentation update from Release v1.1.2 and minor code cleanups

- CODEOWNERS
Add the reviewers from the file for reviewing each PR submitted to the
branch.
> OFI-NCCL: Add CODEOWNERS file

- CODEOWNERS
Add the reviewers from the file for reviewing each PR submitted to the
branch.
> [aws] OFI-NCCL: Add CODEOWNERS file

- src/nccl_ofi_net.c
This makes use of compatibility checks in Libfabric and only enables
the feature when it is needed.  When running with a newer kernel with
copy-on-fork support and recent rdma-core, additional fork safety
support is not required and so the variable is silently ignored.
Using FI_EFA_FORK_SAFE instead of FI_EFA_FORK_SAFE does the right
thing on both new and legacy systems.
Signed-off-by: Greg Inozemtsev <ginozemt@amazon.com>
NCCLOFI-273
Version of #82 for `master`.  Tested on P4dn with all providers.
> Use FI_EFA_FORK_SAFE environment variable to enable fork safety support

- RELEASENOTES.md
- configure.ac
NCCLOFI-294
Release note update for v1.1.5
> Release 1.1.5aws

- RELEASENOTES.md
- configure.ac
- include/nccl_ofi.h
- src/nccl_ofi_net.c
NCCLOFI-294
Release note update for v1.1.5
> Release 1.1.5

- src/nccl_ofi_net.c
Issue https://github.com/aws/aws-ofi-nccl/issues/85
NCCL calls ofi_conect, then ofi_acept when checking for GPU GDR support
In case if underlying provider is synchronous, this lead to deadlock,
as actual transfer can occur only if receiver side is ready to accept packet.
This change checks if connection initiated to self and eliminates waiting for
send completion in this case.
> Fix deadlock in case if underlying provider uses rendezvous mode

- include/nccl_ofi.h
- src/nccl_ofi_net.c
- tests/nccl_connection.c
- tests/nccl_message_transfer.c
- tests/ring.c
- tests/test-common.h
> Support NCCL v2.12

- include/nccl_ofi.h
- src/nccl_ofi_net.c
> Fix compile issue on centos and rhel7 platforms

- RELEASENOTES.md
- configure.ac
> Documentation: Update version string and RELEASENOTES for v1.2.0aws

- RELEASENOTES.md
- configure.ac
> Documentation: Update version string and RELEASENOTES for v1.2.0

- src/nccl_ofi_net.c
These cherry-pick cleanly.  Previous review: #103.
> Port fi_cq_readerr changes from aws to master

- RELEASENOTES.md
- configure.ac
> Documentation: Update version string and RELEASENOTES for v1.3.0

- configure.ac
- m4/ax_check_enable_debug.m4
Signed-off-by: Greg Inozemtsev <ginozemt@amazon.com>
> Add enable_debug flag to configure

- RELEASENOTES.md
- configure.ac
> Documentation: Update version string and RELEASENOTES for v1.4.0

- RELEASENOTES.md
- configure.ac
> Documentation: Update version string and RELEASENOTES for v1.4.0aws

- src/nccl_ofi_net.c
- tests/nccl_connection.c
- tests/nccl_message_transfer.c
- tests/ring.c
> Remove duplicate flush checks and minor bug fixes in unit tests.

- src/nccl_ofi_net.c
- tests/nccl_connection.c
- tests/nccl_message_transfer.c
- tests/ring.c
Clean cherry-pick from recent `aws` merge.
> Remove duplicate flush checks and minor bug fixes in unit tests

- src/nccl_ofi_net.c
> OFI-NCCL: Fix compilation issues for CUDA version < 11.3

- src/nccl_ofi_net.c
- tests/test-common.h
> Fix a couple type mismatches

- Config
- configure.ac
- include/nccl_ofi.h
- src/Makefile.am
- src/nccl_ofi_net.c
- tests/Makefile.am
- tests/test-common.h
This patch set adds support for AWS Trainium to the aws branch.
> Add support for AWS Trainium

- README.md
- configure.ac
- include/nccl-headers/error.h
- include/nccl-headers/net-ofi/net_ofi_v2.h
- include/nccl-headers/net-ofi/net_ofi_v3.h
- include/nccl-headers/net-ofi/net_ofi_v4.h
- include/nccl-headers/net-ofi/net_ofi_v6.h
- include/nccl-headers/net.h
- include/nccl-headers/net_neuron.h
- include/nccl-headers/net_v2.h
- include/nccl-headers/net_v3.h
- include/nccl-headers/net_v4.h
- include/nccl-headers/net_v5.h
- include/nccl-headers/net_v6.h
- include/nccl_ofi.h
- include/stack.h
- src/Makefile.am
- src/compat_v2.c
- src/compat_v3.c
- src/compat_v4.c
- src/compat_v5.c
- src/compat_v6.c
- src/nccl_ofi_net.c
- tests/nccl_connection.c
- tests/nccl_message_transfer.c
- tests/ring.c
- tests/test-common.h
* Most of the patches except 1 adds support for different NCCL versions to the plugin repository.
* "[Set Neuron Device in MR Attributes](https://github.com/aws/aws-ofi-nccl/commit/29b2cb654690ff1ca3bb738caa362dca63a146bf)" patch prevents an improper libfabric usage.
> Support different NCCL versions using a single plugin build.

- include/nccl_ofi.h
- include/nccl_ofi_param.h
- src/nccl_ofi_net.c
- tests/test-common.h
Merge changes from master to aws branch, including reworking the connect deadlock patch to work with the new non-blocking connect API.
> Merge changes from master to aws branch

- configure.ac
- include/nccl-headers/net-ofi/net_ofi_v2.h
- include/nccl_ofi.h
- include/nccl_ofi_param.h
- m4/ax_check_ec2_instance.m4
- m4/ax_platform_aws.m4
- src/Makefile.am
- src/compat_v2.c
- src/nccl_ofi_net.c
- src/platform-aws.c
This is a series of patches to the aws branch to try and factor out the obviously AWS-specific bits from the critical path, so that we can merge the aws and master branches.
> Refactor AWS branch to make it mergable with master branch

- src/platform-aws.c
Signed-off-by: Michael Axtmann <axtmannm@amazon.com>
(cherry picked from commit ffd2930e9fbf471e16718e58f5552e4bb3fe6745)
> Avoid topology update if NCCL_TOPO_FILE is already set

- Config
- RELEASENOTES.md
Sync the release notes and Config between the master and aws branch.  This should be the final branch merge; we can delete the aws branch on GitHub after this commit.
> Sync docs between branches

- configure.ac
This branch will be used for new aws-ofi-nccl release.
> New Release Branch - v1.6.x

- src/nccl_ofi_net.c
Explicitly duplicate the info entries of the info list in the dup_conns situation rather than building an infinite loop list, to simplify cleanup and allow send/recv to work without changes. This allows us to remove the custom free function and just use fi_freeinfo().
Filter the list for the TCP case before duplicating, because why do all the duplicating work outlined above on providers that we are going to filter out.
> Remove dup_conns infinite info loop

- RELEASENOTES.md
> Add v1.6.0 to release notes

- RELEASENOTES.md
Merge from v1.6.x RELEASENOTES.md to master branch
> [master] Add v1.6.0 to release notes

- configure.ac
Change aws-ofi-nccl plugin contact point email address to al-ofi-nccl-team@amazon.com
> Change aws-ofi-nccl plugin contact point email address

- README.md
> Add `--enable-platform-aws` config flag to README

- RELEASENOTES.md
- configure.ac
> Prep for 1.7.0aws release

- configure.ac
- m4/check_pkg_libfabric.m4
Backport https://github.com/aws/aws-ofi-nccl/pull/212 to the 1.7.x-aws branch.
> Backport PR 212

- configure.ac
> Update version for a 1.7.0 release

- configure.ac
1.7.0 has shipped; on to 1.7.1a1.
> Update 1.7.x branch version number

- include/nccl_ofi.h
- src/nccl_ofi_net.c
> Fix compilation, declare support_gdr as extern

- README.md
Add details covering hwloc, changes to our release process, and the use of dlopen to the README.
This is blocking on https://github.com/aws/aws-ofi-nccl/pull/224, so that it becomes true.
> Update docs to cover recent updates

- .gitignore
- README.md
- include/nccl_ofi.h
- include/nccl_ofi_cuda.h
- m4/check_pkg_cuda.m4
- src/Makefile.am
- src/nccl_ofi_cuda.c
- src/nccl_ofi_net.c
- src/nccl_ofi_rdma.c
- src/nccl_ofi_sendrecv.c
- tests/functional/Makefile.am
- tests/functional/cuda_check.c
Backport https://github.com/aws/aws-ofi-nccl/pull/224 and https://github.com/aws/aws-ofi-nccl/pull/227 from master to v1.7.x-aws.
> Backport dlopen and readme changes to v1.7.x-aws

- RELEASENOTES.md
> Prep release notes for 1.7.1 release

- configure.ac
> Set version to 1.7.1

- include/Makefile.am
> Add ofi_nccl_cuda.h to dist tarball

- src/nccl_ofi_rdma.c
1. After adding a bounce request to message buffer, it can be used and (unlikely) freed by another thread, so don't use bounce_req after adding it to message buffer.
2. Always decrement bounce buffer count when receiving eager message, and increment when reposting bounce buffer after eager copy.
> Fix resource leak and race condition in bounce buffer handling code

- configure.ac
> dist: bump version to 1.7.2rc1

- include/nccl_ofi.h
- include/nccl_ofi_freelist.h
- include/nccl_ofi_math.h
- src/nccl_ofi_cuda.c
- src/nccl_ofi_freelist.c
- src/nccl_ofi_net.c
- src/nccl_ofi_rdma.c
- src/nccl_ofi_scheduler.c
- src/nccl_ofi_sendrecv.c
- src/nccl_ofi_topo.c
This PR pulls in the following changes from master to v1.7.x-aws:
* https://github.com/aws/aws-ofi-nccl/pull/235
* https://github.com/aws/aws-ofi-nccl/pull/242
* https://github.com/aws/aws-ofi-nccl/pull/239
* https://github.com/aws/aws-ofi-nccl/pull/243
* https://github.com/aws/aws-ofi-nccl/pull/246
* https://github.com/aws/aws-ofi-nccl/pull/247
I did not cherry-pick the CONTEXT2 change (https://github.com/aws/aws-ofi-nccl/pull/237), but this otherwise syncs the two branches.
> Cherry-pick master commits to 1.7.2

- README.md
- RELEASENOTES.md
> dist: Update docs for 1.7.2 release

- configure.ac
> dist: Set version to 1.7.2

- configure.ac
> dist: Set version to 1.7.3rc1

- src/platform-aws.c
In a56f5604 code was added to disable NVLS on AWS platforms due to a failure mode in NCCL itself when using NVLS on a platform that didn't use collectives offload (including EFA).  With NCCL 2.18.5, that issue has been fixed.
This patch detects the version of NCCL in use (which requires some dlsym hackery) and only disables NVLS on NCCL versions prior to 2.18.5.
> Don't disable NVLS for NCCL 2.18.5 or later

- src/nccl_ofi_net.c
Like noted in the comment, we do not need to set
`FI_OPT_CUDA_API_PERMITTED` for Neuron devices. Configury could use some work to only check for this in m4/check_pkg_libfabric.m4 when CUDA is available/requested, but the CUDA and libfabric check macros are independent and I don't want to pollute that quite yet.
We also need to rename the `support_gdr` flag to support_hmem or the like, but I will batch that up with a couple other cosmetic changes that make the naming more general.
> neuron: Do not call fi_setopt() to disable CUDA ops in the Neuron path

- src/platform-aws.c
With this patch, Neuron compiles without warnings.
> Clean up Neuron warnings

- src/nccl_ofi_rdma.c
- src/nccl_ofi_sendrecv.c
- src/nccl_ofi_topo.c
.. and a couple other minor cleanups as separate commits. I can separate them out into a separate PR if folks prefer.
Testing: neuron-bench sweeps run successfully. Kicking off a CI trigger here for P* testing. 
> topo: Detect Neuron devices as accelerators in addition to GPUs

- src/platform-aws.c
As a temporary workaround, do not force NCCL_PROTO=simple on P5 when using the RDMA protocol.  EFA on P5 will write correct data to the buffer, but may deliver the correct data multiple times before EFA generates the completion (in the write w/ immediate case).  NCCL is ok with this behavior, because the plugin won't mark the request as complete until the completion is generated and won't reuse buffers until the request is marked complete.
We only narrowly enable on P5 when using the RDMA transport because the EFA Libfabric provider may segment messages at non-128 byte points when using send/recv operations in the case where the endpoint 128_BYTE_ALIGNED constants are set.
> aws: Do not force NCCL_PROTO=simple on P5

- configure.ac
1.7.3 has shipped; on to 1.7.4!
> dist: Update version to 1.7.4a1

- doc/efa-env-var.md
*Issue #, if available:* N/A
*Description of changes:* Add documentation that gathers best practices in terms of env vars for EFA to share a prescriptive, easy to consume doc.
> Add EFA cheatsheet

- src/nccl_ofi_freelist.c
The freelist data buffer is registered using
`nccl_net_ofi_alloc_mr_buffer`, and so needs to be deregistered using the companion deregistration function. This caused a segfault in an error condition.
> Use correct deregistration function if freelist alloc fails

- RELEASENOTES.md
Update docs to reflect all the changes since 1.7.3-aws.
> Update 1.7.4-aws docs

- configure.ac
> Update version to 1.7.4-aws

- configure.ac
> Update version to 1.7.5a1

- src/nccl_ofi_api.c
- src/nccl_ofi_rdma.c
Lots of argument checks are expensive in the critical path.  Refactor the argument checking so that we always validate inputs from NCCL, but use asserts for validating our internal data structure linking.
Since I'm moving the code around a bit, also change the error messages when group receives with an invalid 'n' are found.
> Clean up argument checking in communication calls

- src/nccl_ofi_rdma.c
We had the exception in one of two relevant places. This adds it to the other place.
> Add local read exception for zero-sized eager messages

- src/platform-aws.c
Hopper GPUs do not require a network flush, but NCCL versions <2.19.1 still enable flush by default on any GPU type.
For GPU generations earlier than Hopper, NCCL always enables flush, while for Hopper GPUs flush is enabled or disabled depending on the value of the NCCL_NET_FORCE_FLUSH environment variable. The default value for this variable is 1 for NCCL versions <2.19.1, which forces flush when it is not needed, so it is safe to set it to 0 if it is not explicitly set.
> Set NCCL_NET_FORCE_FLUSH=0 on P5

- src/platform-aws.c
NCCL v2.19.3 reduced the chunk size used when running NVLS Tree
algorithm on greater than 4 nodes to 64KiB. This drastically impacted
performance on AWS (Ref: https://github.com/NVIDIA/nccl/pull/1112/
for some data). NCCL v2.20.3 has made this a tunable. Based on
empirical testing, a max chunk size of 512KiB recovers from the
regression and was also observed to be the default in v2.19.3.
Setting this unconditionally without relying on ncclGetVersion symbol
being available, since the parameter did not exist in versions prior
to v2.20.
> aws: Restore NCCL_NVLSTREE_MAX_CHUNKSIZE to 512KiB

- CODEOWNERS
- INSTALL.md
- Makefile.am
- README.md
See individual commits.
Reworked #334 over #335 . Also moved some content into https://github.com/aws/aws-ofi-nccl/wiki/Environment-Variables and https://github.com/aws/aws-ofi-nccl/wiki/Testing-and-Benchmarking
> More doc updates

- .gitignore
> Update .gitignore for Tuner

- .gitignore
- RELEASENOTES.md
- configure.ac
- include/Makefile.am
> Updates for the 1.8.0-aws release

- configure.ac
> Update version to 1.8.1a1

- src/nccl_ofi_api.c
- src/nccl_ofi_rdma.c
When progressing completions, we could get a completion error for a request before NCCL gets to calling test() explicitly for that request. Since NCCL tests for completions in order, this can lead to hangs when there are non-recoverable failures in the network and NCCL never receives a successful completion for the earliest request. With this change, completion errors are always passed up the stack so NCCL can abort the job and fail gracefully where possible.
This logic can further be enhanced based on provider-specific information from completion error entry to distinguish between fatal errors vs recoverable user errors, but that would not be portable.
Fixes #346
> Always propagate completion errors to NCCL

- include/Makefile.am
- include/nccl_ofi.h
- include/nccl_ofi_ofiutils.h
- include/nccl_ofi_rdma.h
- include/nccl_ofi_sendrecv.h
- src/Makefile.am
- src/nccl_ofi_net.c
- src/nccl_ofi_ofiutils.c
- src/nccl_ofi_rdma.c
- src/nccl_ofi_sendrecv.c
- src/nccl_ofi_topo.c
- src/platform-aws.c
https://github.com/aws/aws-ofi-nccl/pull/321 has a challenge with performance due to the cost of polling CQs in EFA today.  However, a bunch of the work will help other optimizations.  The last two commits were also a bit bigger than absolutely necessary.  This PR pulls out all the work except the creation of the extra QP/CQ, so that we can continue with other experiments.
> Refactoring initialization and rdma transport in prep for control qp work

- .github/workflows/distcheck.yaml
- CODEOWNERS
- m4/check_pkg_neuron.m4
Two commits for Neuron builds.
> Fix Neuron distcheck

- tests/functional/nccl_connection.c
- tests/functional/nccl_message_transfer.c
- tests/functional/ring.c
- tests/functional/test-common.h
Currently, functional tests are selecting one random device and testing that device only, so bugs that affect a single specific device (e.g., device 0) may pass unnoticed. 
This PR is removing the random selection and instead runs each test for all devices.
> Functional tests try all devices instead of just one random device

- src/nccl_ofi_rdma.c
Added some branch prediction hints when we check for unlikely error cases in the critical path. All but one are related to msgbuff calls.
> rdma: branch prediction hints in the datapath

- RELEASENOTES.md
- configure.ac
- include/nccl-headers/nvidia/tuner.h
- include/nccl-headers/nvidia/tuner_v1.h
- include/nccl-headers/nvidia/tuner_v2.h
- include/nccl_ofi_tuner.h
- src/nccl_ofi_rdma.c
- src/platform-aws.c
- src/tuner/nccl_ofi_model.c
- src/tuner/nccl_ofi_tuner.c
- tests/functional/nccl_message_transfer.c
- tests/functional/ring.c
> Cherry-picks for 1.9.0-aws release

- configure.ac
> Bumping library version to v1.9.1a1-aws

- RELEASENOTES.md
- configure.ac
> Updates for v1.9.1-aws release

- src/nccl_ofi_rdma.c
Move call to `prepare_recv_conn_resp_req` before entry point of `COMM_SEND_CONN` stage.
This resolves a potential memory leak where `prepare_recv_conn_resp_req` is called multiple times on EAGAIN.
Also fixup a similar case in `accept`, although there was no memory allocation there so no leak.
(cherry picked from commit 398b8537804ec30ee580218665b5be5908638720)
> [v1.9.x-aws] rdma: (fix) memory leak: don't alloc `recv_conn_resp_req` on EAGAIN

- .ci/aws/Jenkinsfile
- .ci/aws/common.groovy
> [v1.9.x-aws] Backport Jenkins CI Stability Fixes

- .github/workflows/distcheck.yaml
> add al2 gh action

- .ci/aws/common.groovy
When p3dn's fail to launch due to ICE, retry logic takes ~12 min (killing the existing p3dn's, terminating security groups, removing elastic IP's, and then waiting 6 minutes). PR CI will run faster overall if we can avoid going into the retry logic all together by sleeping before hand for 5 min.
> .ci/aws: Add 5 min sleep before launching p3dn

- .ci/aws/Jenkinsfile
- .ci/aws/common.groovy
(cherry picked from commit b988585b9504269a4ce5592c775e3a57b2e96db4)
> [v1.9.x-aws] .ci/aws: Attempt to add stable p3dn testing into CI

- RELEASENOTES.md
- configure.ac
> Update version number and changelog for v1.9.2-aws release.

- configure.ac
> 1.9.x: Bump version to 1.9.3a1-aws

- .gitignore
add some things to gitignore related to nix
By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.
> chore: gitignore update

- .github/workflows/distcheck.yaml
This check is failing; trying to update version to see if the failure is resolved.
> .github: update versions in codechecker workflow (Attempt #2)

- .github/workflows/distcheck.yaml
This check is failing; trying to update version to see if the failure is resolved.
(cherry picked from commit b3b53e129debf0f7bb411416443d4a53dc05d365)
> [v1.9.x-aws] update versions in codechecker workflow

- .github/workflows/distcheck.yaml
> .github/workflows: Remove EPEL from AL2 b/c it doesn't exist anymore

- RELEASENOTES.md
- configure.ac
> Update version number and changelog for v1.10.0-aws release

- configure.ac
> 1.10.x: Bump version to 1.10.1a1-aws

- src/nccl_ofi_sendrecv.c
reg_mr_base_comm calls reg_mr_base and register_mr_buffers. register_mr_buffers returns NULL if registration is unnecessary for a provider.  reg_mr_base_comm then inserts this NULL into the mr_cache, then a second call to register a local buffer results in an error that a duplicate registration was attempted.
To fix the problem, In the case where a provider does not require local memory registration, do not use the cache when such a registration is attempted.  In addition, avoid the locking around the cache.
> Skip caching local memory registrations when unnecessary for provider

- src/nccl_ofi_rdma.c
NCCL's topology detection will set NIC PCIe link speed based on the "leader" NIC for the GPU. For multi-rail platforms, we increase the link speed reported to NCCL to account for the other rails. This requires generating a topology file that will be passed to NCCL.
Therefore, only generate the topology file on multi-rail platforms (`num_rails > 1`).
> rdma: write topo file only for multi-rail platforms

- RELEASENOTES.md
- configure.ac
> Update version number and changelog for v1.11.0-aws release

- .ci/aws/Jenkinsfile
- .ci/aws/README.md
(cherry picked from commit 20150d532867cd8d4a4b93456207d659c9521e80)
> [v1.9.x-aws] .ci/aws: Merge config file with Jenkinsfile

- src/nccl_ofi_interface_neuron.c
v4 API may block infinitively when executed with RDMA protocol because communicator creation is (a) blocking operation by definition of v4 API and (b) performing 4-way handshake in case of RDMA protocol. Therefore, we force it to use SENDRECV protocol in case neuron specific API is used. We do not force SENDRECV protocol in case of NCCL API, since there is no known platform that uses RDMA protocol with v4 API. Note, on P5 instances, NCCL needs to needs to support more recent API anyways.
> init: Avoid hang by forcing SENDRECV in case of neuron v4 API usage

- .ci/aws/Jenkinsfile
> .ci/aws: Add g4dn testing to PR CI

- .ci/aws/Jenkinsfile
> .ci/aws: Make failures happen in correct stage

- .ci/aws/Jenkinsfile
> .ci/aws: Decrease NCCL_TEST iterations to 5

- include/tracing_impl/nvtx.h
- m4/check_pkg_nvtx.m4
> fix(tracing): use header-only nvtx3

- .ci/aws/Jenkinsfile
> .ci/aws: Unpin al2 p3dn ami

- tests/functional/nccl_message_transfer.c
- tests/unit/ep_addr_list.c
- tests/unit/freelist.c
- tests/unit/idpool.c
- tests/unit/scheduler.c
Stacked PRs:
* #568
* #567
* #566
* #591
* #588
* #595
* #594
* #593
* #589
* __->__#587
* #577
* #576
* #586
* #585
* #574
* #575
* #571
* #570
* #573
* #569
* #565
* #563
--- --- ---
> fix(test): fix typing issues

- include/tracing_impl/nvtx.h
Stacked PRs:
* #568
* #567
* #566
* #591
* #588
* #595
* #594
* __->__#593
* #589
* #587
* #577
* #576
* #586
* #585
* #574
* #575
* #571
* #570
* #573
* #569
* #565
* #563
--- --- ---
> fix(tracing/nvtx): silence -Wmissing-field-initializer warnings

- configure.ac
Stacked PRs:
* #568
* #567
* #566
* #591
* __->__#588
* #595
* #594
* #593
* #589
* #587
* #577
* #576
* #586
* #585
* #574
* #575
* #571
* #570
* #573
* #569
* #565
* #563
--- --- ---
> feat(build): add -Wextra to "picky" compiler flags

- include/nccl_ofi.h
- include/nccl_ofi_idpool.h
- src/nccl_ofi_idpool.c
- src/nccl_ofi_net.c
- src/nccl_ofi_rdma.c
- src/nccl_ofi_scheduler.c
- src/nccl_ofi_sendrecv.c
- src/nccl_ofi_topo.c
- src/platform-aws.c
- src/tuner/nccl_ofi_regions.c
- src/tuner/nccl_ofi_tuner.c
Stacked PRs:
* #568
* #567
* #566
* #591
* #588
* #595
* #594
* #593
* #589
* #587
* #577
* #576
* #586
* #585
* #574
* __->__#575
* #571
* #570
* #573
* #569
* #565
* #563
--- --- ---
> fix(tree): avoid sign comparison issues

- src/nccl_ofi_rdma.c
Clean up the code to always use the get_device_from_ep() accessor function instead of poking through data structures.
> rdma: Use get_device_from_ep() accessor

- .ci/aws/Jenkinsfile
cherry picked from commit 95f6376cadd99cd369e9a3de34be4374939f8c1d
> Cherry pick g4dn tests to v1.12.x-aws

- RELEASENOTES.md
- configure.ac
> Update version number and changelog for v1.12.0-aws release

- configure.ac
> [v1.12.x-aws] update version number to v1.12.1a1-aws

- src/platform-aws.c
> aws: Skip the WRITE_IN_ORDER_ALIGNED_128_BYTES check for P5en

- include/nccl_ofi_param.h
- src/nccl_ofi_sendrecv.c
> Fix abort when cache is disabled.

- src/nccl_ofi_net.c
As noted in the comment, until the relevant libfabric and EFA driver changes to dynamically query the speed for newer generation devices are more widely deployed, this commit overrides the link_attribute so that we report the correct property to NCCL. For P5en, this gets scaled up to 400Gbps for the aggregated NIC that we report to NCCL, so NCCL's topo discovery and graph generation work as expected.
> aws: Override libfabric link_attr for certain platforms

- .ci/aws/Jenkinsfile
> Switch CI to persistent clusters with containers

- .ci/aws/Jenkinsfile
> [v1.11.x] .ci/aws: Switch CI to persistent clusters with containers

- src/nccl_ofi_rdma.c
We always post multiple receive buffers at once, because we wait until the posted count reaches min_posted_bounce_buffesr before filling, and then fill to max_posted_bounce_buffers.  There's no need to ring the doorbell multiple times in this tight loop, so instead set FI_MORE for all but the last buffer we post.
> rdma: Set FI_MORE when posting receive buffers

- RELEASENOTES.md
- configure.ac
> release: v1.13.x aws

- include/nccl_ofi_mr.h
> mr: add comment clarifying fi_mr_attr/ckey punning

- RELEASENOTES.md
- configure.ac
> Update version number and changelog for v1.13.1-aws release

- .github/workflows/distcheck.yaml
- configure.ac
> Update config version to 1.13.2a1-aws

- src/platform-aws.c
Our platform map is getting a bit absurd as we duplicate a bunch of information for every product variant (I'm looking at you, P5, P5e, and P5en).  Instead, support a wild card (and really, any valid regex) in the platform data name.  This impleemntation is wildly inefficient, since we have to build a new regex engine every time through the loop, but we only do this at init, and the total number of platforms isn't that big, so let's not worry about that.
> aws: Use regex expansion for platform names

- include/tracing_impl/nvtx.h
> fix(nvtx): fix for domain/device refactoring

- RELEASENOTES.md
- configure.ac
Update version number and changelog for v1.13.2-aws release.
> Update version number and changelog for v1.13.2-aws release

- README.md
We included this in the release notes started v1.13.0, but forgot to update the README.
Fixes: #282
> doc: Add AL2023 to the supported distro list

- 3rd-party/nccl/cuda/include/nccl/err.h
- 3rd-party/nccl/cuda/include/nccl/types.h
- src/nccl_ofi_api.c
> Sync with latest err.h and types.h and fix a retval

- README.md
- RELEASENOTES.md
- configure.ac
Update the version number and changelog for v1.14.0 release
It is build on top of https://github.com/aws/aws-ofi-nccl/pull/787, the only change is adding:
```
- RDMA Transport Enhancements: Added NCCL receive request early completion support when 
provider data progress model is FI_PROGRESS_AUTO
```
> Update version number and changelog for v1.14.x release

- configure.ac
Update the AC_INIT PATCH version in configure.ac to be the next release version's alpha release.
> release: begin 1.14.1 cycle

- .ci/aws/Jenkinsfile
- This patch updates NCCL version to the latest released version v2.26.2-1
- https://github.com/NVIDIA/nccl/releases/tag/v2.26.2-1
> .ci/aws: Update NCCL version to v2.26.2-1

- .ci/aws/Jenkinsfile
- src/nccl_ofi_rdma.c
- src/nccl_ofi_sendrecv.c
1. TCP provider bugfix details in - https://github.com/aws/aws-ofi-nccl/pull/815
2. PR CI changes
local nccl-test with libfabric `main` and `v1.22.x` branch passed.
> Cherry-pick TCP provider bugfix

- RELEASENOTES.md
- configure.ac
Update version number and changelog for v1.14.1 release
> Update version number and changelog for v1.14.1 release

- configure.ac
Update the AC_INIT PATCH version to be the next release version's alpha release to prevent conflicts between development builds and release builds
> release: begin 1.14.2 cycle

- RELEASENOTES.md
- configure.ac
Usual configure and RELEASENOTES updates.
> 1.14.2 release

- configure.ac
Bump the version number for the next minor release
> release: begin 1.14.3 cycle

- include/nccl_ofi.h
- include/nccl_ofi_platform.h
- include/nccl_ofi_system.h
- include/platform-aws.h
- src/nccl_ofi_net.cpp
- src/nccl_ofi_rdma.cpp
- src/nccl_ofi_system.cpp
- src/platform-aws.cpp
c3c26fa aws: Provide a more appropriate GUID to NCCL
00c9ab0 system: Add utility to generate a unique node identifier.
8b042c0 rdma: Allow for devices with varying number of rails
> GUID property update

- src/nccl_ofi_rdma.cpp
rdma: Do not send close message for unused r_comm
There is a potential hang when NCCL aborts in the middle of communicator creation, and a send_comm is created without the corresponding recv_comm having been created. In this case, when closing the send comm, the plugin will wait for a close message from the recv comm, which will never arrive (because the recv comm was never returned to NCCL).
The upcoming revised connection management code solves this problem, for Libfabric providers supporting `FI_PROGRESS_AUTO`, by returning a recv comm immediately after sending the connect response message. Since this cannot be done for providers requiring `FI_PROGRESS_MANUAL` (due to the need to poll the CQ to ensure delivery), this workaround is needed.
In this workaround, an `r_comm` will not send a …
> rdma: Do not send close message for unused r_comm

- src/platform-aws.cpp
> platform: Generalize log message indicating network flush behavior

- contrib/python/ofi_nccl/tuner/cli/wrapper.py
- include/tuner/nccl_ofi_tuner_common.h
- src/tuner/nccl_ofi_regions.cpp
- src/tuner/nccl_ofi_tuner.cpp
Added p6 region based tuner for all combinations
All Reduce, All Gather and Reduce Scatter,  both 0x0 and 0x7s
```
0x0s
collective  algo   proto platform
nodes ranks message_size
16    128   32            AllGather  Ring      Ll     P5en
16    128   32            AllGather  Ring      Ll       P6
16    128   3744915       AllGather  Ring   Ll128     P5en
16    128   12815929      AllGather  Ring   Ll128       P6
16    128   2147483649    AllGather  Ring  Simple     P5en
16    128   2624702237    AllGather  Ring  Simple       P6
collective  algo   proto platform
nodes ranks message_size
16    128   32            ReduceScatter  Ring      Ll     P5en
16    128   32            ReduceScatter  Ring      Ll       P6
16    128   3744915       ReduceScatter  Ring   Ll128     P5en
16    128 …
```
> tuner: build p6 region based tuner

- RELEASENOTES.md
- configure.ac
Update the version number and changelog for v1.15.0 release
> Update version number and changelog for v1.15.0 release

- include/Makefile.am
- include/cm/nccl_ofi_cm.h
- include/cm/nccl_ofi_cm_reqs.h
- include/cm/nccl_ofi_cm_resources.h
- include/cm/nccl_ofi_cm_types.h
- include/nccl_ofi.h
- include/nccl_ofi_config_bottom.h
- include/nccl_ofi_param.h
- include/nccl_ofi_rdma.h
- include/nccl_ofi_sendrecv.h
- src/Makefile.am
- src/cm/nccl_ofi_cm.cpp
- src/cm/nccl_ofi_cm_reqs.cpp
- src/cm/nccl_ofi_cm_resources.cpp
- src/nccl_ofi_api.cpp
- src/nccl_ofi_rdma.cpp
- src/nccl_ofi_sendrecv.cpp
Adds a new connection management module shared between the two transports.
> Implement new connection establishment for SENDRECV and RDMA transports

- .github/workflows/distcheck.yaml
- configure.ac
- doc/topology-aware.md
- include/nccl_ofi_mr.h
- src/Makefile.am
- src/platform-aws.cpp
- src/tuner/nccl_ofi_regions.cpp
- tests/unit/mr.cpp
Cherry-picking following fixes for v1.16.0: 
- 923e47e43c91c1deeca2bfc7d6115ea8c76a2fbd / tuner: Adjust P6 region tuner for 0x0 32 rank
- 2d693bbaee17fbcc84d45330449ccf8cb9105ced / ci: Update workflow to use pre-built docker containers - Part 2
- 5231309699104d1b26a532906d6be2ef91af8d17 / doc: topology aware scheduling and rank mapping
- 05889cdafe67c693b284d4acf63a04b53b856d72 / tuner: Work around NCCL dlopen bug
- c45cbc1442d6bc9b8f17522899bc4ae455d712cd / build: Add libnccl-tuner-ofi.so symlink
- d6a172d785c39da720a288b9bac2279270be42d2 / mr: do not page align memory registrations on neuron platform
> [v1.16.x] Cherry pick fixes for v1.16.0

- README.md
- RELEASENOTES.md
- configure.ac
Updating RELEASENOTES.md and version number for v1.16.0 release
> Update version number and changelog for v1.16.0 release

- src/nccl_ofi_rdma.cpp
In case the close message is disabled, there is no reason to poll the
completion queue when closing communicators, so remove this unneeded
poll.
Before this commit, polling the completion queue during communicator
close can cause a crash in the comm abort flow, if a message is received
targeting an already-closed communicator, and the communicator had no
inflight requests when it was closed (so that it does not enter the
"domain invalid" state).  This commit should resolve the crash in the
expected case that all other communicators are also closed in the abort
flow (which is how NCCL's abort flow works today).
However, the case in which other communicators remain active after one
is aborted (which is unexpected, given how NCCL's communicator abort
works today) still needs to be solved. …
> rdma: Don't poll CQ on comm close if close message is disabled

- .github/workflows/generate-release-draft.yml
Updating the container address and thereby fixing the workflow for the source.
> Update container source for draft release workflow

- include/nccl_ofi_param.h
- include/platform-aws.h
- src/nccl_ofi_topo.cpp
- src/platform-aws.cpp
Cherry-picking commits for v1.16.1 release. 
> Cherry picking commits for v1.16.1

- RELEASENOTES.md
- configure.ac
Updating version number and release notes for v1.16.1 release
> Update version number and changelog for v1.16.1 release

- .github/workflows/generate-release-draft.yml
- docker/base/Dockerfile.ubuntu
Cherry-picking commits for v1.16.2 release.
> Cherry picking commits for v1.16.2

- RELEASENOTES.md
- configure.ac
Update version number and changelog for v1.16.2 release
> Update version number and changelog for v1.16.2 release

- RELEASENOTES.md
- configure.ac
Update version number and changelog for v1.16.3 release
> Update version number and changelog for v1.16.3 release

- tests/functional/ring.cpp
After requests are done, compare the reported sizes from test() with the sizes from the request.
This was done in nccl_message_transfer, and this change is for ring test.
This test has been run on 2, 3, and 4 nodes, and passed.
*Issue #, if available: The context is that there was an issue reported in the past that aws-ofi-nccl (or libfabric) does not correctly report the size when requests are completed.
*Description of changes: see above.
> test: compare test() reported size with requested

- configure.ac
Update the v1.17.x version number to v1.17.0a1 to differentiate the release branch from the head of master.
> Update version number in v1.17.x release branch

- include/nccl_ofi_rdma.h
- src/nccl_ofi_rdma.cpp
- src/tuner/nccl_ofi_regions.cpp
Updating v1.17.x branch with newer commits from master
> Update v1.17.x with commits from newer commits master

- src/tuner/nccl_ofi_regions.cpp
- Adding tuner updates to 0x0 collectives on v1.17.x
> Cherry Pick tuner updates on to v1.17.x
